window.PAGE_DATA = [
  {
    "id": 168199,
    "IDcode": "DDK-221",
    "title": "发情期之旅-仓本堇",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/20231224/ddk221pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-221"
  },
  {
    "id": 516898,
    "IDcode": "DDK-222",
    "title": "與父親在一起 與爸爸搞找乾爹～造人",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乱伦"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202511/06/690c74306b81af1f8539ce86/poster2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-222"
  },
  {
    "id": 564011,
    "IDcode": "DDK-223",
    "title": "縄·少女妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230716/JovnpcyF/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-223"
  },
  {
    "id": 564009,
    "IDcode": "DDK-224",
    "title": "クズ男宅に家庭访问！ドM洗脳してくれる変态ケースワーカーさん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230716/2Co8yY0K/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-224"
  },
  {
    "id": 101305,
    "IDcode": "DDK-225",
    "title": "被东北赶来的学生-青井莉奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "单体作品",
      "中出",
      "美少女电影",
      "手淫",
      "多P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202506/04/683f51fc0b69f1d816556079/cover.jpg",
    "actress": [
      "青井莉奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-225"
  },
  {
    "id": 547697,
    "IDcode": "DDK-226",
    "title": "ウチのクラスのマジメな美少女便器さん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231015/2nQkkvVm/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-226"
  },
  {
    "id": 562788,
    "IDcode": "DDK-227",
    "title": "処刑中毒女",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231126/Vr4OWjop/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-227"
  },
  {
    "id": 547131,
    "IDcode": "DDK-228",
    "title": "関西弁ポルノ小说家のチ〇ポなぶりハラスメント",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231218/9UzUyO17/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-228"
  },
  {
    "id": 546822,
    "IDcode": "DDK-229",
    "title": "人格崩壊オナホール加工 IN监禁病栋",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240115/pETmSlE7/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-229"
  },
  {
    "id": 546024,
    "IDcode": "DDK-230",
    "title": "缚肉ホルスタイン 超乳ボンレスファッカーズ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240319/GvUtUmt4/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-230"
  },
  {
    "id": 545770,
    "IDcode": "DDK-231",
    "title": "野外·不法投弃少女に连続中出し",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240416/Jid2hGMy/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-231"
  },
  {
    "id": 545315,
    "IDcode": "DDK-232",
    "title": "新任女教师 纯情肉便器",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240617/zkm2QYfE/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-232"
  },
  {
    "id": 11959,
    "IDcode": "DDK-233",
    "title": "淫蟲之家 - 上癮的女孩 ~ 雫月心桜",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "性虐癖",
      "美腳",
      "小隻馬",
      "SM",
      "深喉",
      "癡女",
      "舔陰",
      "淫亂",
      "中出",
      "美少女電影",
      "殘忍畫面",
      "劇情",
      "調教",
      "美少女",
      "按摩棒",
      "絕頂高潮",
      "叛逆少女",
      "緊縛",
      "苗條",
      "顏射",
      "暗黑系",
      "插入異物",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "口交",
      "潮吹",
      "自慰",
      "女上位",
      "白眼失神",
      "後入",
      "跳蛋"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2024-09-17",
    "cover_url": "https://picture.yoshiclub.xyz/20240915/a5f44ae1-e9ed-4105-924b-2d1dd0216c27.jpg",
    "actress": [
      "雫月心桜"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-233"
  },
  {
    "id": 9850,
    "IDcode": "DDK-234",
    "title": "欲望の森 まいごの全裸少女を森で見つけて性欲が抑えられない 由良かな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "凌辱",
      "美腳",
      "蘿莉控",
      "女學生",
      "小隻馬",
      "口爆",
      "SM",
      "奇異的",
      "深喉",
      "舔陰",
      "奇聞趣事",
      "露出",
      "中出",
      "舔腳",
      "美少女電影",
      "劇情",
      "抹油",
      "美少女",
      "M男・M女",
      "強姦",
      "辣妹/GAL系",
      "緊縛",
      "變態",
      "顏射",
      "痴漢",
      "手指插入",
      "艷遇",
      "騎乗位",
      "羞恥",
      "形象俱樂部",
      "野戰",
      "口交",
      "蘿莉",
      "拳擊交",
      "潮吹",
      "魔鬼系",
      "清純",
      "女上位",
      "白眼失神",
      "後入",
      "野外露天"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/03/688e73de98bc99dfdd032e5a/cover.jpg",
    "actress": [
      "由良佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-234"
  },
  {
    "id": 3473,
    "IDcode": "DDK-235",
    "title": "処刑中毒女 塩見彩",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "鬼畜片",
      "性虐癖",
      "凌辱",
      "ASMR顱内高潮",
      "美腳",
      "拘束・拷問",
      "口爆",
      "SM",
      "打屁股",
      "單體作品",
      "野性",
      "深喉",
      "喝尿",
      "脱糞",
      "刑架",
      "重口味",
      "口球",
      "舔陰",
      "淫亂",
      "中出",
      "極品美人",
      "御姐系",
      "紋身刺字",
      "調教",
      "早漏",
      "蠟燭",
      "按摩棒",
      "後入",
      "絕頂高潮",
      "淫蕩・硬核",
      "M男・M女",
      "無毛",
      "辣妹/GAL系",
      "港區女子",
      "緊縛",
      "苗條",
      "色白",
      "跳蛋",
      "暗黑系",
      "高顏值",
      "企畫",
      "插入異物",
      "顏射",
      "手指插入",
      "導尿",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "吞精",
      "巨尻",
      "口交",
      "拳擊交",
      "潮吹",
      "魔鬼系",
      "4K",
      "女上位",
      "白眼失神",
      "熟女",
      "大奶头",
      "女優",
      "性感",
      "心理驚悚",
      "紀念作"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "塩見彩"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDK-235"
  },
  {
    "id": 166344,
    "IDcode": "DDOB-009",
    "title": "性慾高漲卻只能自慰度日的阿姨幫你破童貞 青木玲",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-009"
  },
  {
    "id": 166376,
    "IDcode": "DDOB-011",
    "title": "むっちりBODYのエステおばさんに連続孕ませさせられました 風間ゆみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-011"
  },
  {
    "id": 166377,
    "IDcode": "DDOB-012",
    "title": "高学歴の保険セールスおばさんはデカチンと痛い行為が大好きなド猥褻なド変態奥様だった。 八ッ橋さい子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-012"
  },
  {
    "id": 213327,
    "IDcode": "DDOB-015",
    "title": "喜欢吃儿子的朋友的大鸡巴",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乱伦"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-015"
  },
  {
    "id": 526437,
    "IDcode": "DDOB-023",
    "title": "メンズを喰い散らかす爆乳Kカップ姊さんの接吻とセックスとパイズリ 有沢実纱",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-023"
  },
  {
    "id": 567752,
    "IDcode": "DDOB-025",
    "title": "ザーメンと唾液が大好きな筋トレおばさん森下美绪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-025"
  },
  {
    "id": 595697,
    "IDcode": "DDOB-030",
    "title": "AIイラマ学习机能搭载 人型オナホール 君岛式壱号 君岛みお",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://imgsiwa.com:5278/cvjpg/bW8SBvqL.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-030"
  },
  {
    "id": 526436,
    "IDcode": "DDOB-034",
    "title": "デカパイママ 豊満なおっぱいと猥亵なカラダ 吹石れな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-034"
  },
  {
    "id": 526435,
    "IDcode": "DDOB-035",
    "title": "人妻孕ませ肉便器 连続イラマ＆ファック 竹内瞳",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-035"
  },
  {
    "id": 522972,
    "IDcode": "DDOB-036",
    "title": "波多野结衣- お手コキママちゃん 妖艶な神の手コキで快楽射精",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sex8sex8sex8.com/20250410/bHpsIMiz/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-036"
  },
  {
    "id": 595612,
    "IDcode": "DDOB-040",
    "title": "こねくりママちゃん こねくりお手コキとお下品なフェラチオ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://imgsiwa.com:5278/cvjpg/sCflX9My.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-040"
  },
  {
    "id": 595465,
    "IDcode": "DDOB-045",
    "title": "年上の美人妻を种付けプレス",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/774dd240c4683e134485dc0f75ff1c64.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-045"
  },
  {
    "id": 589584,
    "IDcode": "DDOB-051",
    "title": "Madam Bondage Meat Urinal Bondage & Pursuit Pis 受孕 Domaso 已婚妇女",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://img.xxibaocdn.com/video/m3u8/2025/07/01/94286_cover_2025-07-01_233003.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-051"
  },
  {
    "id": 589491,
    "IDcode": "DDOB-054",
    "title": "加尿！喷肉小便池 喷潮的优雅女士泛滥！音羽绫子 - 音羽文子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://img.xxibaocdn.com/video/m3u8/2025/07/06/70660_cover_2025-07-06_041725.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-054"
  },
  {
    "id": 74889,
    "IDcode": "DDOB-055",
    "title": "ママの手淫で男潮吹きまくりなさい！ 滝川穗乃果",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "荡妇",
      "已婚妇女",
      "素人作品",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2019-07-19",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250110-1/9af027246ff67ba3fc926b62c2c7292b.jpg",
    "actress": [
      "滝川穗乃果"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-055"
  },
  {
    "id": 74574,
    "IDcode": "DDOB-056",
    "title": "美臀妈妈VS大鸡巴男人-黒川すみれ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "已婚妇女",
      "乱伦",
      "中出",
      "素人作品",
      "多P",
      "巨大阴茎",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "http://p.155250718p.com/upload/vod/20221020/ddob00056pl.jpg",
    "actress": [
      "黑川堇"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-056"
  },
  {
    "id": 547582,
    "IDcode": "DDOB-057",
    "title": "种付继母集团射精 丰满继母尽量干 篠崎环奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20200104-1/2cc16f9693140bf0ebf5317bf2fd85fa.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-057"
  },
  {
    "id": 212705,
    "IDcode": "DDOB-058",
    "title": "卑鄙的性行为-並木塔子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230924-47/55141d8c39f764a4e0361a4920bae143.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-058"
  },
  {
    "id": 98102,
    "IDcode": "DDOB-059",
    "title": "激イキ爆乳ママに犯されたい！ 宝田もなみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨乳",
      "已婚妇女",
      "乳交",
      "中出",
      "素人作品",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2019-10-19",
    "cover_url": "https://imgsiwa.com:5278/upload/vod/20210819-1/f508e6c613c8fa5a836e199a02fdb7c2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-059"
  },
  {
    "id": 75385,
    "IDcode": "DDOB-061",
    "title": "夫の前でむっちり妻を種付けファック牧村彩香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "已婚妇女",
      "中文字幕",
      "中出",
      "成熟的女人",
      "白天出轨"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "牧村彩香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-061"
  },
  {
    "id": 567496,
    "IDcode": "DDOB-062",
    "title": "潮吹きチ○ポ！ドSママのハード手手で大喷射！！小日向まい第01集",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-062"
  },
  {
    "id": 75519,
    "IDcode": "DDOB-063",
    "title": "母乳ママvs潮吹きM男 お下劣ママが発情母乳を撒き散らす 羽月希",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "中出",
      "母乳",
      "M男",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg2.com:3519/upload/vod/20241126-1/ca7c86f1cf41006d1af4ef82572a3256.jpg",
    "actress": [
      "羽月希"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-063"
  },
  {
    "id": 81656,
    "IDcode": "DDOB-065",
    "title": "ダルマ緊縛肉便器 ドМな人妻を公開種付け 藍川美夏",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "中出",
      "捆绑",
      "SM",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2020-01-19",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "蓝川美夏"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-065"
  },
  {
    "id": 81653,
    "IDcode": "DDOB-068",
    "title": "電撃！痺れマ○コ 奥さん、気絶しても痺れイキしてもらいますョ 遥あやね",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "成熟的女人",
      "已婚妇女",
      "中出",
      "淫乱，真实",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2020-03-19",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "遥彩音"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-068"
  },
  {
    "id": 81650,
    "IDcode": "DDOB-069",
    "title": "縛・メス尻ファック 有末香織",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "羞耻",
      "屁股",
      "捆绑",
      "SM",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2020-03-19",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "篠原友香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-069"
  },
  {
    "id": 209498,
    "IDcode": "DDOB-070",
    "title": "巨乳種付け肉ダルマ 織田真子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-070"
  },
  {
    "id": 213225,
    "IDcode": "DDOB-073",
    "title": "妈妈的大奶子-松本菜奈実",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乱伦"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230924-47/f09a1e54e816e242d1f2e89ccf0d7f2a.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-073"
  },
  {
    "id": 594086,
    "IDcode": "DDOB-092",
    "title": "分租套房的管理员是精力旺盛熟女 瞳凉",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-092"
  },
  {
    "id": 214294,
    "IDcode": "DDOB-098",
    "title": "危险的妈妈-翔田千里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乱伦"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-098"
  },
  {
    "id": 468686,
    "IDcode": "DDOB-105",
    "title": "有夠瘋狂！！露出投稿網站人氣H罩杯變態美人妻調教 藤木紗英",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "巨乳"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202502/04/67a20f29db8c77d79bb6970e/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-105"
  },
  {
    "id": 87390,
    "IDcode": "DDOB-110",
    "title": "【FANZA限定】豊潤熟奴● 天罰を下された哀れな人妻 よしい美希 パンティと生写真付き",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "单体作品",
      "中出",
      "胖女人",
      "拘束",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2022-07-20",
    "cover_url": "https://fm.sl25914.com/upload/vod/20230725-1/2c190a5d5f4b60826807305879446153.jpg",
    "actress": [
      "しみけん"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-110"
  },
  {
    "id": 87422,
    "IDcode": "DDOB-111",
    "title": "痴女最强の尻コキ女",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "单体作品",
      "屁股",
      "4K",
      "手淫",
      "乳液",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://fm.sl25914.com/upload/vod/20230726-1/f16ce9ffc970b1ac07593d7c5a25f0e7.jpg",
    "actress": [
      "永野司"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-111"
  },
  {
    "id": 87414,
    "IDcode": "DDOB-112",
    "title": "高身長のベロ舐め女 チ○ポ、フェラ好きのモデル妻 明日美かんな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "已婚妇女",
      "高",
      "乳液",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2022-08-16",
    "cover_url": "https://imgsiwa.com:5278/cvjpg/kvzW4TI8.jpg",
    "actress": [
      "希望美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-112"
  },
  {
    "id": 87433,
    "IDcode": "DDOB-113",
    "title": "熟女喪失 オバギャルの熟れた果肉 高園ゆり子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "水手服",
      "中出",
      "胖女人",
      "捆绑",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2022-08-16",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "三云ゆり子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-113"
  },
  {
    "id": 87450,
    "IDcode": "DDOB-114",
    "title": "性癖晒します。美し過ぎる潮吹き書道家 及川うみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "玩具",
      "潮吹",
      "女优按摩棒",
      "拘束",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2022-09-17",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20230726-1/e8fa013ce9ebc3c749a07d6bf7a50623.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-114"
  },
  {
    "id": 566511,
    "IDcode": "DDOB-116",
    "title": "ハイレグびんびん 悩杀嬲り",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/38371e167168d1fe8ba1919af05a1f21.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-116"
  },
  {
    "id": 88585,
    "IDcode": "DDOB-118",
    "title": "女M男娼-藤井レイラ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "单体作品",
      "手淫",
      "M男",
      "淫语",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-118"
  },
  {
    "id": 168200,
    "IDcode": "DDOB-120",
    "title": "欺負下劣的媽媽的玉砕大炎戒-小早川怜子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/20231224/ddob120pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-120"
  },
  {
    "id": 564232,
    "IDcode": "DDOB-121",
    "title": "セクシーヒップアタック 闷絶尻嫐り",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230623/YvqyyG3S/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-121"
  },
  {
    "id": 537378,
    "IDcode": "DDOB-122",
    "title": "ビッチM ブラックアクメ 兰华",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20230927/ddob122pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-122"
  },
  {
    "id": 564010,
    "IDcode": "DDOB-123",
    "title": "絶対【ヤラ】れる！民宿の女主人がケダモノすぎて",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230716/tOSOEUG8/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-123"
  },
  {
    "id": 105748,
    "IDcode": "DDOB-124",
    "title": "溫柔的色情媽媽打手槍誘發勃起",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "单体作品",
      "手淫",
      "淫语",
      "成熟的女人"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "みっちー",
      "绫瀬麻衣子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-124"
  },
  {
    "id": 547698,
    "IDcode": "DDOB-125",
    "title": "お手コキ家政妇",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231015/HGGtb8cX/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-125"
  },
  {
    "id": 562786,
    "IDcode": "DDOB-126",
    "title": "无敌のママ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231126/yC0mnv2a/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-126"
  },
  {
    "id": 547127,
    "IDcode": "DDOB-127",
    "title": "縄に寝取られた美容师妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231218/ulOq0lS9/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-127"
  },
  {
    "id": 546820,
    "IDcode": "DDOB-128",
    "title": "みんなの M男の为のメスイキ保育园",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240115/tGr50twq/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-128"
  },
  {
    "id": 561813,
    "IDcode": "DDOB-129",
    "title": "人の奥さんを妊娠させる会 鬼畜チ〇ポで子宫の奥まで鬼连射！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240219/w4dVcgz7/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-129"
  },
  {
    "id": 546023,
    "IDcode": "DDOB-130",
    "title": "高身长ママのお手コキびっち～",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240319/DdBy4SPC/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-130"
  },
  {
    "id": 545772,
    "IDcode": "DDOB-131",
    "title": "チンタマクラッシュ！褐色の日焼けビッチママ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240416/TC7idNpL/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-131"
  },
  {
    "id": 545479,
    "IDcode": "DDOB-132",
    "title": "絶顶肉便器",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240520/rYzkK2Mo/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-132"
  },
  {
    "id": 545311,
    "IDcode": "DDOB-133",
    "title": "高身长、巨乳、潮吹き、元女子陆上选手睾丸投げ！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240617/nX7ktOed/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-133"
  },
  {
    "id": 545173,
    "IDcode": "DDOB-134",
    "title": "地上最强のパイズリ女",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240716/UWK9RQ0t/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-134"
  },
  {
    "id": 11011,
    "IDcode": "DDOB-135",
    "title": "請深喉我，喉嚨渴望被FUCK ~ 清巳麗乃",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "性虐癖",
      "熟女",
      "拘束・拷問",
      "蕩婦",
      "口爆",
      "SM",
      "亂交 • 群P",
      "深喉",
      "刑架",
      "重口味",
      "口球",
      "兩男一女",
      "淫亂",
      "中出",
      "調教",
      "按摩棒",
      "絕頂高潮",
      "M男・M女",
      "女優",
      "緊縛",
      "變態",
      "插入異物",
      "手指插入",
      "導尿",
      "騎乗位",
      "形象俱樂部",
      "唾液敷面",
      "美乳",
      "吞精",
      "巨乳",
      "口交",
      "慾求不滿",
      "潮吹",
      "魔鬼系",
      "女上位",
      "白眼失神",
      "多P",
      "後入",
      "性感",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2024-08-21",
    "cover_url": "https://picture.yoshiclub.xyz/20241030/de9e3e69-3d85-4b88-a244-fd874562c2ad.jpg",
    "actress": [
      "清巳麗乃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-135"
  },
  {
    "id": 11949,
    "IDcode": "DDOB-136",
    "title": "淫乱ブーツ生中出し 美脚妻を連続ファックやりたい放題 松乃りの",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "多P",
      "美腳",
      "蕩婦",
      "美臀",
      "亂交 • 群P",
      "靴子",
      "人妻",
      "兩男一女",
      "淫亂",
      "中出",
      "絕頂高潮",
      "緊身衣",
      "女優",
      "緊縛",
      "苗條",
      "企畫",
      "騎乗位",
      "形象俱樂部",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "慾求不滿",
      "女上位",
      "熟女",
      "後入",
      "性感",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/20240916/de38ec17-0c9b-40ba-91e5-943d42370eb5.jpg",
    "actress": [
      "松莉乃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-136"
  },
  {
    "id": 176555,
    "IDcode": "DDOB-137",
    "title": "艶縛 安野由美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251112-1/9a7f96d925efee17e5067600614b0c58.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-137"
  },
  {
    "id": 7472,
    "IDcode": "DDOB-138",
    "title": "チ〇ポ大好きビッチママのお手コキフォーティーエイト 友田彩也香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "蠻橫嬌羞",
      "主觀視角",
      "美腳",
      "小隻馬",
      "美臀",
      "教學",
      "癡女",
      "淫語",
      "淫亂",
      "中出",
      "猥褻穿著",
      "丁字裤",
      "按摩棒",
      "戀物癖",
      "絕頂高潮",
      "辣妹/GAL系",
      "港區女子",
      "色白",
      "高顏值",
      "企畫",
      "女優",
      "插入異物",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "口交",
      "慾求不滿",
      "情趣內衣",
      "自慰",
      "女上位",
      "熟女",
      "後入",
      "濕身"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "友田彩也香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-138"
  },
  {
    "id": 5960,
    "IDcode": "DDOB-139",
    "title": "ガングロママの闇バイト ママにデカチン献上するだけの簡単なお仕事 蘭華",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "性虐癖",
      "美腳",
      "高妹",
      "口爆",
      "美臀",
      "亂交 • 群P",
      "單體作品",
      "野性",
      "重口味",
      "舔陰",
      "兩男一女",
      "淫亂",
      "中出",
      "舔腳",
      "御姐系",
      "按摩棒",
      "打手槍",
      "M男・M女",
      "辣妹/GAL系",
      "港區女子",
      "高顏值",
      "女王",
      "變態",
      "企畫",
      "暗黑系",
      "金髮",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "短髮",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "巨乳",
      "肌肉",
      "潮吹",
      "魔鬼系",
      "4K",
      "女上位",
      "後入",
      "性感",
      "心理驚悚",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/06/08/72fe63abe7136011dec4951307de4cbb.jpg",
    "actress": [
      "蘭華"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-139"
  },
  {
    "id": 5283,
    "IDcode": "DDOB-140",
    "title": "黑絲真空騷貨 172cm抖M美腿讓你爽到爆 ~ 鬆野蘭",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "美腳",
      "高妹",
      "蕩婦",
      "美臀",
      "單體作品",
      "感官作品",
      "舔陰",
      "淫亂",
      "中出",
      "舔腳",
      "劇情",
      "絕頂高潮",
      "辣妹/GAL系",
      "女優",
      "企畫",
      "苗條",
      "黑絲",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "巨乳",
      "局部特寫",
      "4K",
      "女上位",
      "高跟鞋",
      "熟女",
      "後入",
      "性感"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/27/68ae2ec1682e2e9281a548ea/cover.jpg",
    "actress": [
      "松野蘭"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-140"
  },
  {
    "id": 2692,
    "IDcode": "DDOB-141",
    "title": "騷氣爆棚的手活女王媽媽 ~ 安野由美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "口爆",
      "亂交 • 群P",
      "單體作品",
      "老太婆",
      "淫語",
      "重口味",
      "舔陰",
      "五十路",
      "按摩棒",
      "打手槍",
      "企畫",
      "手指插入",
      "騎乗位",
      "口交",
      "4K",
      "女上位",
      "熟女",
      "後入",
      "跳蛋",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202509/17/68ca661b7de28f4ede493335/cover.jpg",
    "actress": [
      "安野由美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DDOB-141"
  },
  {
    "id": 444274,
    "IDcode": "DETK-001",
    "title": "こわれものクズどもの性処理具",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250826-1/570705a6ae80f7a4cd49eb346207470a.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DETK-001"
  },
  {
    "id": 7488,
    "IDcode": "DETK-002",
    "title": "惡魔少女 從可愛迷妹到榨幹老色鬼的都市生存記！ ~ 由良佳奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "精選綜合",
      "蠻橫嬌羞",
      "美腳",
      "蘿莉控",
      "蕩婦",
      "小隻馬",
      "口爆",
      "癡女",
      "舔陰",
      "淫亂",
      "中出",
      "美少女電影",
      "劇情",
      "美少女",
      "明星臉",
      "勾引・誘惑",
      "打手槍",
      "絕頂高潮",
      "女優",
      "高顏值",
      "苗條",
      "企畫",
      "純粹的慾望",
      "手指插入",
      "艷遇",
      "騎乗位",
      "羞恥",
      "形象俱樂部",
      "美人",
      "口交",
      "蘿莉",
      "雙馬尾",
      "潮吹",
      "清純",
      "女上位",
      "後入"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2025-03-18",
    "cover_url": "https://picture.yoshiclub.xyz/20250316/294045e9-f55e-4abd-bf92-5fa902e42c25.jpg",
    "actress": [
      "由良佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DETK-002"
  },
  {
    "id": 7462,
    "IDcode": "DETK-003",
    "title": "溺れる女 老人介護は蜜の味 祈山愛",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "老頭子",
      "美腳",
      "美臀",
      "深喉",
      "癡女",
      "人妻",
      "中出",
      "女看護",
      "舔腳",
      "劇情",
      "美人妻",
      "純粹的慾望",
      "騎乗位",
      "羞恥",
      "形象俱樂部",
      "美人",
      "美腿",
      "巨尻",
      "口交",
      "女上位",
      "後入",
      "寢取"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "祈山愛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DETK-003"
  },
  {
    "id": 68780,
    "IDcode": "DETK-004",
    "title": "もなか 私は毒母から男を奪った、ざまあみろ 千石もなか",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "美少女电影",
      "戏剧",
      "高中女生",
      "制服",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "千石もなか"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DETK-004"
  },
  {
    "id": 411711,
    "IDcode": "FSTU-001",
    "title": "拳击健身教练 三穴同时运动 佐久间枫 佐久间枫",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251009-1/21c4b198096c2c690ffc0ea2130c67db.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-001"
  },
  {
    "id": 72528,
    "IDcode": "FSTU-003",
    "title": "ハイレグブーツファック 宇佐美すい",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "紧身衣",
      "恋腿癖",
      "单体作品",
      "中出",
      "乳液",
      "多P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250806-1/47413350709563e7096c66bf9cb2410e.jpg",
    "actress": [
      "宇佐美すい"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-003"
  },
  {
    "id": 72519,
    "IDcode": "FSTU-004",
    "title": "腰フリどスケベ ベリーダンサー 野々花さわ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "恋腿癖",
      "恋物癖",
      "单体作品",
      "女上位",
      "苗条",
      "多P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250806-1/eac521f9a20ac08ebddb80c9a129096c.jpg",
    "actress": [
      "野々花さわ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-004"
  },
  {
    "id": 7490,
    "IDcode": "FSTU-005",
    "title": "裸流空手 ドマゾ絶頂巨根組手 水澄せいら",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "豐滿",
      "凌辱",
      "性虐癖",
      "拘束・拷問",
      "報復",
      "口爆",
      "SM",
      "美臀",
      "亂交 • 群P",
      "深喉",
      "人妻",
      "兩男一女",
      "淫亂",
      "中出",
      "戰鬥行動",
      "劇情",
      "抹油",
      "調教",
      "按摩棒",
      "戀物癖",
      "M男・M女",
      "綁架",
      "緊縛",
      "變態",
      "美人妻",
      "暗黑系",
      "顏射",
      "插入異物",
      "手指插入",
      "騎乗位",
      "羞恥",
      "形象俱樂部",
      "美人",
      "美乳",
      "唾液敷面",
      "巨尻",
      "口交",
      "拳擊交",
      "潮吹",
      "女格鬥家",
      "女上位",
      "白眼失神",
      "多P",
      "後入",
      "濕身",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202509/28/68d84681d6fbef4e90ccfb1a/cover.jpg",
    "actress": [
      "水澄せいら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-005"
  },
  {
    "id": 6846,
    "IDcode": "FSTU-006",
    "title": "騷氣長靴集團交尾亂交 美腿大奶妹被榨幹 ~ 夏川步美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美腳",
      "拘束・拷問",
      "高妹",
      "口爆",
      "美臀",
      "靴子",
      "亂交 • 群P",
      "身體意識",
      "癡女",
      "舔陰",
      "兩男一女",
      "淫亂",
      "中出",
      "美少女電影",
      "劇情",
      "調教",
      "按摩棒",
      "打手槍",
      "絕頂高潮",
      "M男・M女",
      "辣妹/GAL系",
      "女優",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "脚控・戀足癖",
      "美腿",
      "巨尻",
      "巨乳",
      "口交",
      "潮吹",
      "乱交",
      "4K",
      "女上位",
      "多P",
      "後入",
      "跳蛋",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2025-04-12",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250414/2025041408325744_thumbnail.webp",
    "actress": [
      "夏川步美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-006"
  },
  {
    "id": 68877,
    "IDcode": "FSTU-007",
    "title": "ヨガインストラクター 喉奥エクササイズ 足立友梨",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "恋物癖",
      "滥交",
      "巨大阴茎",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "足立友梨"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-007"
  },
  {
    "id": 66032,
    "IDcode": "FSTU-008",
    "title": "淫乱ブーツ集団交尾 美脚ドマゾをザーメンSEX 水澄せいら",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "恋腿癖",
      "单体作品",
      "中出",
      "苗条",
      "滥交",
      "拘束"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/06/07/3cbd6486/vod.jpg",
    "actress": [
      "水澄せいら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-008"
  },
  {
    "id": 5259,
    "IDcode": "FSTU-009",
    "title": "淫蕩長靴群P亂鬥 褐色美腿辣妹精液狂歡 ~ 蘭華",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "凌辱",
      "美腳",
      "拘束・拷問",
      "高妹",
      "口爆",
      "SM",
      "靴子",
      "亂交 • 群P",
      "單體作品",
      "野性",
      "深喉",
      "癡女",
      "感官作品",
      "舔陰",
      "淫亂",
      "中出",
      "猥褻穿著",
      "抹油",
      "性感",
      "調教",
      "早漏",
      "按摩棒",
      "後入",
      "打手槍",
      "絕頂高潮",
      "無毛",
      "M男・M女",
      "辣妹/GAL系",
      "港區女子",
      "緊縛",
      "苗條",
      "企畫",
      "女優",
      "金髮",
      "手指插入",
      "騎乗位",
      "羞恥",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "巨乳",
      "肌肉",
      "潮吹",
      "4K",
      "情趣內衣",
      "女上位",
      "白眼失神",
      "多P",
      "大奶头",
      "唾液敷面",
      "跳蛋",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/06/21/4ea75b561626635677b0552422062b97.jpg",
    "actress": [
      "蘭華"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-009"
  },
  {
    "id": 4424,
    "IDcode": "FSTU-010",
    "title": "淫乱ブーツ集団交尾 美脚、美顔、美女をザーメンSEX 多田有花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "高妹",
      "口爆",
      "靴子",
      "單體作品",
      "人妻",
      "舔陰",
      "中出",
      "完全着衣",
      "按摩棒",
      "女優",
      "企畫",
      "阪道系",
      "短裙・迷你裙",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "脚控・戀足癖",
      "口交",
      "潮吹",
      "局部特寫",
      "4K",
      "女上位",
      "真人秀",
      "熟女",
      "後入",
      "跳蛋"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250718-1/73fed28d2524f8d88bf19e65ee3bc0d6.jpg",
    "actress": [
      "多田有花"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-010"
  },
  {
    "id": 192356,
    "IDcode": "FSTU-011",
    "title": "フェティッシュ女捜査官 FINAL ANSWER 塩見彩",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250718-1/48a5a4693fb5aabd640a889d85daea2f.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-011"
  },
  {
    "id": 3501,
    "IDcode": "FSTU-012",
    "title": "高身長食い込みレースクイーン ハイレグファックおま●こピットイン 松野蘭",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "真實拍攝",
      "蠻橫嬌羞",
      "美腳",
      "高妹",
      "美臀",
      "亂交 • 群P",
      "單體作品",
      "癡女",
      "舔陰",
      "兩男一女",
      "淫亂",
      "中出",
      "極品美人",
      "拜金女",
      "完全着衣",
      "明星臉",
      "絕頂高潮",
      "緊身衣",
      "辣妹/GAL系",
      "港區女子",
      "高顏值",
      "苗條",
      "企畫",
      "手指插入",
      "騎乗位",
      "超爆乳",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "巨乳",
      "4K",
      "女上位",
      "熟女",
      "後入",
      "性感",
      "3P・4P",
      "賽車女郎"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/22/37801a10/vod.jpg",
    "actress": [
      "松野蘭"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-012"
  },
  {
    "id": 3493,
    "IDcode": "FSTU-013",
    "title": "金玉どストライク 水川潤",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "鬼畜片",
      "性虐癖",
      "凌辱",
      "美腳",
      "拘束・拷問",
      "運動服裝",
      "SM",
      "美臀",
      "亂交 • 群P",
      "單體作品",
      "野性",
      "奇異的",
      "舔陰",
      "淫亂",
      "極品美人",
      "殘忍畫面",
      "完全着衣",
      "調教",
      "按摩棒",
      "淫蕩・硬核",
      "M男・M女",
      "運動女孩",
      "緊縛",
      "高顏值",
      "企畫",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "口交",
      "肌肉",
      "4K",
      "女上位",
      "白眼失神",
      "後入",
      "性感",
      "跳蛋",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250816/20250816032244487487_19100_thumbnail.webp",
    "actress": [
      "水川潤",
      "由爱可奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-013"
  },
  {
    "id": 2691,
    "IDcode": "FSTU-014",
    "title": "ノーパンパンストビッチなCA 響つかさ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "素股",
      "美腳",
      "拘束・拷問",
      "不倫",
      "高妹",
      "蕩婦",
      "濕身",
      "單體作品",
      "舔陰",
      "中出",
      "空姐",
      "極品美人",
      "御姐系",
      "拜金女",
      "完全着衣",
      "抹油",
      "按摩棒",
      "絕頂高潮",
      "港區女子",
      "高顏值",
      "苗條",
      "企畫",
      "顏射",
      "黑絲",
      "純粹的慾望",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "美腿",
      "脚控・戀足癖",
      "口交",
      "巨乳",
      "慾求不滿",
      "潮吹",
      "4K",
      "空姐制服",
      "女上位",
      "熟女",
      "後入",
      "性感",
      "跳蛋",
      "3P・4P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/17/588d9374/vod.jpg",
    "actress": [
      "永野司"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-014"
  },
  {
    "id": 174808,
    "IDcode": "FSTU-015",
    "title": "高身長バレリーナ ザーメンSEX 森あやみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-015"
  },
  {
    "id": 174859,
    "IDcode": "FSTU-016",
    "title": "ハイレグブーツファック 妃ひかり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/10/27/2ea20dc2ffb2098634409b1225ff68df.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=FSTU-016"
  },
  {
    "id": 82427,
    "IDcode": "GTJ-061",
    "title": "水野朝阳的捆绑SM体验",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "巨乳",
      "SM",
      "捆绑",
      "多P"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "水野朝陽"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-061"
  },
  {
    "id": 71327,
    "IDcode": "GTJ-065",
    "title": "宫崎彩鬼畜捆绑冲刺阴道",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "萝莉塔",
      "捆绑",
      "SM",
      "洗澡"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "宫崎彩"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-065"
  },
  {
    "id": 218226,
    "IDcode": "GTJ-066",
    "title": "処刑拷問-神納花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "SM"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-066"
  },
  {
    "id": 210316,
    "IDcode": "GTJ-068",
    "title": "串刺し拷問 七海ゆあ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "SM"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-068"
  },
  {
    "id": 589506,
    "IDcode": "GTJ-071",
    "title": "串烧叶月桃子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "SM"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "",
    "cover_url": "https://img.xxibaocdn.com/video/m3u8/2025/07/06/62077_cover_2025-07-06_015543.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-071"
  },
  {
    "id": 75058,
    "IDcode": "GTJ-072",
    "title": "絶対服従 拷問イラマチオ 七海ゆあ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "中出",
      "素人作品",
      "捆绑",
      "SM",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2019-07-19",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250110-1/595cfaededc2fa8756060cf168a864e3.jpg",
    "actress": [
      "七海ゆあ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-072"
  },
  {
    "id": 75124,
    "IDcode": "GTJ-073",
    "title": "絶対服従 拷問イラマチオ 葉月桃",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "中出",
      "素人作品",
      "捆绑",
      "SM",
      "深喉"
    ],
    "type": "有码",
    "company": "DOGMA",
    "publish_date": "2019-08-19",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250110-1/fd4b80138d0c9c7ee002dbd32f303773.jpg",
    "actress": [
      "叶月桃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GTJ-073"
  }
];