window.PAGE_DATA = [
  {
    "id": 181388,
    "IDcode": "GOOD-026",
    "title": "人妻「自撮り」NTR かほ（27歳）",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "DEEP'S",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/23/be3a299b/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GOOD-026"
  },
  {
    "id": 187572,
    "IDcode": "GOOD-029",
    "title": "人妻「自撮り」NTR みゆ(32歳)",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "DEEP'S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/29/68b1573a5f13d063bcc29549/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GOOD-029"
  },
  {
    "id": 4346,
    "IDcode": "GOUL-014",
    "title": "産休明けNTR 溢れ出る母乳、抑えられない欲求― 愛と快楽に溺れた中出し社内不倫。 真白りま",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨尻",
      "若妻",
      "慾求不滿",
      "三十路",
      "豐滿",
      "職場",
      "4K",
      "辦公室",
      "OL",
      "色白",
      "美乳",
      "制服",
      "口交",
      "性感",
      "熟女",
      "形象俱樂部",
      "單體作品",
      "NTR",
      "人妻",
      "美人妻",
      "野性",
      "淫亂",
      "淫妻",
      "出軌",
      "中出",
      "蕩婦",
      "美人",
      "美腿",
      "後入",
      "劇情",
      "不倫",
      "清純",
      "舔陰",
      "手指插入",
      "乳交",
      "偷竊",
      "黑絲",
      "女秘書",
      "女上位",
      "騎乗位",
      "女同事"
    ],
    "type": "",
    "company": "熟女人妻最強廠",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250723-1/00af268d8da9d7882c9df6f94857f0ba.jpg",
    "actress": [
      "真白りま"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GOUL-014"
  },
  {
    "id": 81640,
    "IDcode": "GRCH-350",
    "title": "親友の隣で中出しNTR ～無理やりイカされた私～ 長瀬広臣×山井すず",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "戏剧",
      "手指插入",
      "白天出轨",
      "淫妻",
      "给女性观众",
      "素人作品",
      "接吻"
    ],
    "type": "",
    "company": "",
    "publish_date": "2020-02-20",
    "cover_url": "https://fm.sl25914.com/upload/vod/20221031-1/c935643fec2f4a5c7674a931984ff4b7.jpg",
    "actress": [
      "山井すず",
      "长瀬広臣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GRCH-350"
  },
  {
    "id": 454209,
    "IDcode": "GS-2108",
    "title": "禁忌 人妻性癖开眼 05 续・人妻自拍NTR 被睡走报告影片26",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻"
    ],
    "type": "",
    "company": "GOGOS",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251023-1/192357097b0077c4152dc708b1712ff4.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GS-2108"
  },
  {
    "id": 8934,
    "IDcode": "GS-2114",
    "title": "禁忌 人妻性癖開眼 05 續 人妻自撮NTR寢取報告26 完全版 ~ 胡桃多惠 雨依燕",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P・4P",
      "奇聞趣事",
      "兩女一男",
      "慾求不滿",
      "真實拍攝",
      "KTV夜總會",
      "素人作品",
      "飯店",
      "雙飛",
      "羞恥",
      "自拍性愛",
      "女同性戀",
      "亂交 • 群P",
      "口交",
      "美人妻",
      "人妻",
      "NTR",
      "淫亂",
      "地味",
      "淫妻",
      "中出",
      "蕩婦",
      "後入",
      "企畫",
      "奇異的",
      "絕頂高潮",
      "家庭主妇",
      "女上位",
      "騎乗位"
    ],
    "type": "",
    "company": "GOGOS",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/25/68acc07c31eb0592de65c230/cover.jpg",
    "actress": [
      "胡桃多惠",
      "雨依燕"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GS-2114"
  },
  {
    "id": 561477,
    "IDcode": "GUPP-006",
    "title": "小松杏のすべて 女上司が妻子持ち部下を诱惑してNTR＆痴女ソープ调教プレイ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "妄想族",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240319/WV4AG8gP/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GUPP-006"
  },
  {
    "id": 13870,
    "IDcode": "GUPP-011",
    "title": "美麗寡婦NTR - 在丈夫靈前與姐夫發生變態性愛 中野まこ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "未亡人・寡婦",
      "苗條",
      "亂倫",
      "和服・浴衣・喪服",
      "緊縛",
      "拘束・拷問",
      "胸控・戀乳癖",
      "自宅",
      "美乳",
      "按摩棒",
      "巨乳",
      "口交",
      "性感",
      "潮吹",
      "NTR",
      "淫亂",
      "淫妻",
      "中出",
      "蕩婦",
      "劇情",
      "絕頂高潮",
      "自慰",
      "乱伦",
      "調教",
      "女上位"
    ],
    "type": "",
    "company": "妄想族",
    "publish_date": "2024-06-11",
    "cover_url": "https://picture.yoshiclub.xyz/20240619/9fedd6ce-ade3-480f-bd05-c8a6264b99fc.jpg",
    "actress": [
      "戶川奈美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GUPP-011"
  },
  {
    "id": 399708,
    "IDcode": "GUPP-027",
    "title": "嫉妒心爆棚的甜心爹地NTR和地雷系變性女的中出性愛 - 松下裡子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "妄想族",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202509/30/68dadf6ed6fbef4e90d1b68d/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GUPP-027"
  },
  {
    "id": 210873,
    "IDcode": "GVG-453",
    "title": "绿帽三人组-推川ゆうり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2020/11/14/acf0502bc6af37afa71a27501ea00af8.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GVG-453"
  },
  {
    "id": 71202,
    "IDcode": "GVG-887",
    "title": "为了治疗不孕不育人妻波多野结衣在丈夫面前被妇产科老头主任用下流肮脏的舌头狂舔",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "已婚妇女",
      "恋物癖",
      "淫妻",
      "中出",
      "素人作品",
      "接吻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230918-1/de2abacc1261d936ca4484dc209ae616.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GVG-887"
  },
  {
    "id": 84490,
    "IDcode": "GVH-341",
    "title": "巨乳母娘WNTR海外から帰国したデカチンの叔父に母と妹が親子丼SEXされまくってしまった悪夢の三日間 春菜はな/朝日りん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "多P",
      "白天出轨",
      "淫妻",
      "妹妹",
      "巨乳",
      "母亲"
    ],
    "type": "",
    "company": "GLORY QUEST",
    "publish_date": "2022-01-04",
    "cover_url": "https://fm.sl25914.com/upload/vod/20230110-1/89dd8854fa4bbb7535e70039721a0e66.jpg",
    "actress": [
      "春菜华"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GVH-341"
  },
  {
    "id": 535103,
    "IDcode": "GVH-516",
    "title": "义理ママと连れ子の阴キャシ○タNTR 宝田もなみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "GLORY QUEST",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240125/gvh516pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GVH-516"
  },
  {
    "id": 518772,
    "IDcode": "GVH-B689",
    "title": "我心爱的妻子在拍电影时被戴绿帽。 波多野结衣46",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "GLORY QUEST",
    "publish_date": "",
    "cover_url": "https://img.xxibaocdn.com/video/m3u8/2025/10/10/44517_cover_2025-10-10_044713.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=GVH-B689"
  },
  {
    "id": 166504,
    "IDcode": "HAR-072",
    "title": "「浮気したあなたが悪いのよ…」夫の目の前で他人に抱かれイキ狂う姿を見せつける復讐妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻",
      "中文字幕"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/2023/02/czk5yr1vcv3.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAR-072"
  },
  {
    "id": 215837,
    "IDcode": "HAVD-775",
    "title": "在丈夫的面前被侵犯-青木莉子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250512-12/47ff3bd4a00ee634bece88271fa8cd54.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAVD-775"
  },
  {
    "id": 589508,
    "IDcode": "HAWA-179",
    "title": "戴绿帽子验证 被不喜欢的中年父亲责备的妻子，最坏的情况会活下来吗？",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乱伦",
      "淫妻"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "",
    "cover_url": "https://img.xxibaocdn.com/video/m3u8/2025/07/05/54705_cover_2025-07-05_235734.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-179"
  },
  {
    "id": 539174,
    "IDcode": "HAWA-235",
    "title": "旦那とはナマでしないのに俺とは生ハメしてくれる近所の清楚系美人妻とのNTRプチ同栖日记 のぞみ27さい 东希美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "",
    "cover_url": "https://guzwiayz.com/20230316/5LJmNnQH/1.jpg?t=1679991772",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-235"
  },
  {
    "id": 167736,
    "IDcode": "HAWA-291",
    "title": "为满足男友的绿帽子欲望",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202507/07/686b1dfc43d6972716d1b84f/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-291"
  },
  {
    "id": 14516,
    "IDcode": "HAWA-320",
    "title": "NTR小同居日記，25歲的柊有希，住在附近的年輕受虐狂人妻不喝丈夫的精液，卻喝我的精液",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P・4P",
      "艷遇",
      "吞精",
      "苗條",
      "緊縛",
      "美腳",
      "拘束・拷問",
      "眼鏡",
      "亂交 • 群P",
      "口交",
      "兩男一女",
      "人妻",
      "NTR",
      "短髮",
      "淫亂",
      "淫妻",
      "出軌",
      "中出",
      "絕頂高潮",
      "清純",
      "美少女電影",
      "刺青紋身",
      "劇情"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "2024-05-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240523/20240523015832658658.jpg",
    "actress": [
      "柊有希"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-320"
  },
  {
    "id": 11719,
    "IDcode": "HAWA-331",
    "title": "【NTRプチ同棲日記】旦那とは絶対しないけど俺とはアナルSEXしたがる こづえ28歳",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P・4P",
      "老頭子",
      "吞精",
      "多P",
      "巨尻",
      "慾求不滿",
      "凌辱",
      "緊縛",
      "美腳",
      "拘束・拷問",
      "色白",
      "美乳",
      "按摩棒",
      "亂交 • 群P",
      "口交",
      "形象俱樂部",
      "潮吹",
      "兩男一女",
      "NTR",
      "人妻",
      "淫亂",
      "淫妻",
      "猥褻穿著",
      "出軌",
      "中出",
      "蕩婦",
      "後入",
      "美腿",
      "劇情",
      "顏射",
      "絕頂高潮",
      "美臀",
      "不倫",
      "舔陰",
      "脚控・戀足癖",
      "二穴同入",
      "手指插入",
      "舔腳",
      "肛交",
      "調教",
      "女上位",
      "丁字裤",
      "騎乗位"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251104-1/000d2df64d93135d836d09c2620b029a.jpg",
    "actress": [
      "美波梢"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-331"
  },
  {
    "id": 180676,
    "IDcode": "HAWA-337",
    "title": "旦那の精子は飲まないけど俺のは飲んでくれる近所の巨乳若妻とのNTRプチ同棲日記 ひまり26さい",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "Cosmos 映像",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/19/fa748f258087839f7abdd0efaa06f6ee.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HAWA-337"
  },
  {
    "id": 82605,
    "IDcode": "HBAD-141",
    "title": "我的新婚妻子早乙女露伊居然是女特工在我面前被毒贩们轮奸堕落",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "淫妻",
      "新娘，年轻妻子"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/07/02/e54c2e09/vod.jpg",
    "actress": [
      "早乙女露依"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-141"
  },
  {
    "id": 516319,
    "IDcode": "HBAD-144",
    "title": "在丈夫面前被OO，不小心爽到叫出",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202511/12/69140020312f492881570f5c/poster2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-144"
  },
  {
    "id": 212897,
    "IDcode": "HBAD-256",
    "title": "在丈夫面前被邻居轮奸-新山沙弥",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2021/08/19/4296b2ffbfb9228a6be199dfc33aa731.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-256"
  },
  {
    "id": 99023,
    "IDcode": "HBAD-313",
    "title": "夫の目の前で義父に犯された妻 美咲かんな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "强奸",
      "戏剧",
      "淫妻",
      "企画"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "2016-05-12",
    "cover_url": "https://pics.dmm.co.jp/mono/movie/adult/1hbad313/1hbad313pl.jpg",
    "actress": [
      "美咲佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-313"
  },
  {
    "id": 106280,
    "IDcode": "HBAD-465",
    "title": "被同事们当作狗调教的人妻女社员在丈夫面前被凌辱做爱-望月りさ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "OL",
      "调教",
      "淫妻",
      "新娘，年轻妻子",
      "素人作品"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202501/15/67873e335d57b64bfdd99593/cover.jpg",
    "actress": [
      "望月理沙"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-465"
  },
  {
    "id": 164951,
    "IDcode": "HBAD-505",
    "title": "姊妹NTR 我最爱的男友被姊姊睡了",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "HIBINO",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230918-1/da8eccba9bfd9adf3cbb6b2a5e9858e5.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HBAD-505"
  },
  {
    "id": 554888,
    "IDcode": "HEYZO-0921",
    "title": "小心被戴绿帽子金枪鱼她的改进计划",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://thjpg10.top/upload/vod/20241204-1/afb784523db6305cf011f5dda1470e50.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-0921"
  },
  {
    "id": 857,
    "IDcode": "HEYZO-1063",
    "title": "瞞著老公來玩3P淫妻 - 中杉真奈美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P・4P",
      "打手槍",
      "多P",
      "苗條",
      "美腳",
      "羞恥",
      "勾引・誘惑",
      "自宅",
      "胸控・戀乳癖",
      "美乳",
      "制服",
      "按摩棒",
      "巨乳",
      "口交",
      "性感",
      "熟女",
      "潮吹",
      "人妻",
      "NTR",
      "深喉",
      "淫亂",
      "淫妻",
      "出軌",
      "中出",
      "蕩婦",
      "後入",
      "企畫",
      "美臀",
      "顏射",
      "絕頂高潮",
      "舔陰",
      "手指插入",
      "女上位",
      "騎乗位"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "2016-01-19",
    "cover_url": "https://picture.yoshiclub.xyz/20240513/20240513090401334334.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-1063"
  },
  {
    "id": 1020,
    "IDcode": "HEYZO-1424",
    "title": "別人老婆的味道～理想的淫妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "熟女",
      "潮吹",
      "人妻",
      "淫妻",
      "出軌",
      "69",
      "中出"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "2017-03-10",
    "cover_url": "https://picture.yoshiclub.xyz/20240118/20240118020622450450.jpg",
    "actress": [
      "笠原あおい"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-1424"
  },
  {
    "id": 554558,
    "IDcode": "HEYZO-2462",
    "title": "平成出生的业馀剃光妻子丈夫责备2孔交换请求训练狂欢冈村夫妇版",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://thjpg10.top/upload/vod/20241016-1/17415cd7713c2d9b8f153d670f22531e.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-2462"
  },
  {
    "id": 1333,
    "IDcode": "HEYZO-2622",
    "title": "我最好的異性朋友竟然對我提出了NTR的請求",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻",
      "出軌",
      "69",
      "中出"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202502/20/67b6e15b4e7d663df484921f/cover.jpg",
    "actress": [
      "山岸詩織"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-2622"
  },
  {
    "id": 554674,
    "IDcode": "HEYZO-2642",
    "title": "san21SaraNijuichiampSena-sanNijuichi平成出生的W剃光业馀妻子是特别的4孔交换请求培训狂欢",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://thjpg10.top/upload/vod/20241112-1/b47d6bb970c4ac6527b246308d44b9dc.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-2642"
  },
  {
    "id": 1354,
    "IDcode": "HEYZO-2676",
    "title": "Miyu Morita 一个美丽的巨乳已婚女人，在游泳课上戴绿帽子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻",
      "出軌",
      "泳池",
      "中出",
      "巨乳"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://img1.souavzy.org/upload/vod/20240901-1/07298e91583dd0c05f5030f219a3b0ae.jpg",
    "actress": [
      "春風コウ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-2676"
  },
  {
    "id": 1363,
    "IDcode": "HEYZO-2685",
    "title": "AyaTanakaAyaTanaka如果你想要一份工作就去做吧对恶毒的制作人戴绿帽子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "出軌",
      "中出",
      "69",
      "淫妻"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://thjpg10.top/upload/vod/20250206-1/a5786ed7670cb8a5ce2cbd897bf0cfd2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-2685"
  },
  {
    "id": 158824,
    "IDcode": "HEYZO-3319",
    "title": "THE NTR 先輩の可愛い彼女をコッソリ寝取りアナルも頂く 寝取られ – オリビアグレース",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "HEYZO",
    "publish_date": "",
    "cover_url": "https://sex8sex8sex8.com/20250222/syDRxD9c/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEYZO-3319"
  },
  {
    "id": 563439,
    "IDcode": "HEZ-588",
    "title": "寝取られ妻 奥さん、その素敌なカラダでおもいっきり楽しみましょうよ！！NTRデラックス 14名",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230912/GDnoeAAd/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-588"
  },
  {
    "id": 547420,
    "IDcode": "HEZ-610",
    "title": "“あなた见ないで！！”他人棒でイキまくった生性交狂いのNTR美人妻12人4时间",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231115/JYPV8HtZ/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-610"
  },
  {
    "id": 550714,
    "IDcode": "HEZ-665",
    "title": "“对不起你”被戴绿帽子和中出NTR特别12人的美丽妻子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://img1.souavzy.org/upload/vod/20250209-1/c7338a25b18abb298ab9ffadd4cf988b.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-665"
  },
  {
    "id": 13866,
    "IDcode": "HEZ-667",
    "title": "ウチの妻娘、炎上する ～借金返済NTR～",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "苗條",
      "美少女",
      "美腳",
      "胸控・戀乳癖",
      "自宅",
      "母親的朋友",
      "美乳",
      "欠債肉償",
      "按摩棒",
      "亂交 • 群P",
      "巨乳",
      "性感",
      "口交",
      "潮吹",
      "NTR",
      "淫亂",
      "淫妻",
      "中出",
      "後入",
      "企畫",
      "少女",
      "絕頂高潮",
      "美少女電影",
      "乳交",
      "女上位",
      "騎乗位",
      "情趣內衣"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://sex8sex8sex8.com/20250225/adHTJfJq/1.jpg",
    "actress": [
      "宝田萌奈美",
      "虹色久美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-667"
  },
  {
    "id": 177579,
    "IDcode": "HEZ-712",
    "title": "ずっとNTRを妄想してて…。不貞行為を自ら望んで応募してきた美人ヤリ妻のイケない完堕ち性交 一条みお",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/10/12/4f7195ea/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-712"
  },
  {
    "id": 183588,
    "IDcode": "HEZ-742",
    "title": "日替わりNTRパート妻 妻のパート先は にこにこ笑顔で帰ってくる妻はお店で毎日男を替えて不倫SEXしていた 末広純",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/27/4850097d/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-742"
  },
  {
    "id": 449530,
    "IDcode": "HEZ-776",
    "title": "【合法NTR】旦那に内緒で托卵希望でやって来た人妻に種付けプレスで濃厚精子をご提供。貴女の子宮を",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20250718-1/65031107be03aec04d140d62dd2724a0.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-776"
  },
  {
    "id": 62181,
    "IDcode": "HEZ-816",
    "title": "【合法NTR】旦那に内緒で托卵希望でやって来た人妻に種付けプレスで濃厚精子をご提供。貴女の子宮を100\\%孕ませます！？2",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "已婚妇女",
      "出轨",
      "淫妻",
      "业余",
      "中出",
      "巨乳"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250816-1/7739ba62831bc6801810ede4b20b17f3.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-816"
  },
  {
    "id": 60700,
    "IDcode": "HEZ-825",
    "title": "業務中に社内不倫に勤しむ男女のNTR性交 vol.1",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "羞耻",
      "OL",
      "出轨",
      "淫妻",
      "情侣",
      "中出"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/15/de0d6eaabdb9ad63b4a4f48f6aa5dbf4.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HEZ-825"
  },
  {
    "id": 523641,
    "IDcode": "HFD-185",
    "title": "嫌々だったはず…なNTR",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20190520-1/5325b6f44d485266dc327a6361b83fe0.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HFD-185"
  },
  {
    "id": 566292,
    "IDcode": "HFD-189",
    "title": "紧缚NTR 手荒な他人棒に溺れる縄酔い巨乳妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/5578f8fd509c5af7a3a66f2f98136b23.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HFD-189"
  },
  {
    "id": 516166,
    "IDcode": "HHOY-007",
    "title": "「不行…我已經有男友了…」NTR",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202510/03/68ded99a631cc64eb5937bba/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HHOY-007"
  },
  {
    "id": 563081,
    "IDcode": "HJBB-172",
    "title": "爱する男に见られながらイカされ続ける大絶顶NTRベスト",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20231014/TmUIdhF1/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJBB-172"
  },
  {
    "id": 549770,
    "IDcode": "HJBB-185",
    "title": "～あなた许して～夫の目の前でデカチンに溺れる禁断羞耻アクメ…背徳NTR即ハメ罚ゲーム",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240521/sETwopcz/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJBB-185"
  },
  {
    "id": 595281,
    "IDcode": "HJMO-402",
    "title": "接吻NTR！老公VS男优！哪边的吻让人更湿润SHOW 3",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20190520-1/708b9f1716f171d12a419229fe4d9a9d.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-402"
  },
  {
    "id": 594983,
    "IDcode": "HJMO-417",
    "title": "普通夫妇观察！！魔镜NTR“请大家看我的妻子被别人上的瞬间！”",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://imgsiwa.com:5278/upload/vod/20210806-1/22382fab55658f52a4ae58d7d9b55094.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-417"
  },
  {
    "id": 71842,
    "IDcode": "HJMO-424",
    "title": "一般男女モニタリング！VR鑑賞中の旦那30cm隣で連続中出しNTR",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "巨大阴茎",
      "已婚妇女",
      "羞耻",
      "白天出轨",
      "淫妻",
      "中出"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230918-1/2303f4c2efa79e35d1ee5df94a8ee4aa.jpg",
    "actress": [
      "羽月希",
      "今井夏帆",
      "逢泽真里亚"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-424"
  },
  {
    "id": 408389,
    "IDcode": "HJMO-488",
    "title": "殘酷淫魔鏡 在男友面前被巨屌男優睡走肏到中出2連發！ 6",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/01/688c6e6d98bc99dfdde5fccb/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-488"
  },
  {
    "id": 566288,
    "IDcode": "HJMO-491",
    "title": "夫妻挑战。老公被川上奈奈美的绝技榨出两次，妻子就要被NTR无套中出",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://imgsiwa.com:5278/cvjpg/l8hrTtQ4.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-491"
  },
  {
    "id": 566280,
    "IDcode": "HJMO-501",
    "title": "夫妻挑战。老公在若宫叶月的绝技下射两回，妻子就要被NTR干无套中出",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/50e2664dfbd237417f51238c7490b424.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-501"
  },
  {
    "id": 561824,
    "IDcode": "HJMO-637",
    "title": "ラブラブ新婚カップル限定 固定バイブ手繋ぎ背徳NTRゲーム 壁越しに夫と手を握ったまま妻はどこ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240218/dYumPV7s/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-637"
  },
  {
    "id": 517041,
    "IDcode": "HJMO-652",
    "title": "殘酷淫魔鏡 在老公面前被巨屌男優",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202511/11/69127fdc6b81af1f85475bf0/poster2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-652"
  },
  {
    "id": 407776,
    "IDcode": "HJMO-655",
    "title": "僅限想要戴綠帽的情侶！ 巨乳家庭主婦無手口交丈夫雞巴匹配！ 如果僅憑嘴的感覺從10隻生雞中獲勝,您將贏得100萬日元！失敗立即NTROO遊戲",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202510/12/68ea980b2c5ed64ee9e654c1/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-655"
  },
  {
    "id": 68989,
    "IDcode": "HJMO-678",
    "title": "寝取られ願望のある夫婦限定！ 巨乳人妻ノーハンドフェラ旦那チ〇ポ当てマッチング！2 生チン10本からお口の感触だけで当てたら100万円！失敗で即ズボNTR罰ゲーム",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "已婚妇女",
      "淫妻",
      "白天出轨",
      "中出",
      "巨乳",
      "口交"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250703-1/ac59b700c0a0e8713ecfad60e66d5078.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-678"
  },
  {
    "id": 180606,
    "IDcode": "HJMO-688",
    "title": "寝取られ願望のある夫婦限定！ 巨乳人妻ノーハンドフェラ旦那チ〇ポ当てマッチング！4 生チン10本からお口の感触だけで当てたら100万円！失敗で即ズボNTR罰ゲーム",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/20/a6ce26f1/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-688"
  },
  {
    "id": 175263,
    "IDcode": "HJMO-689",
    "title": "寝取られ願望のある夫婦限定！巨乳人妻ノーハンドフェラ旦那チ○ポ当てマッチング！5 生チン10本からお口の感触だけで当てたら100万円！失敗で即ズボNTR罰ゲーム",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "HAJIME-KIKAKU",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/10/23/678b518e/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HJMO-689"
  },
  {
    "id": 516338,
    "IDcode": "HKC-087",
    "title": "素人情侶搭訕！在男友面前被幹的女友",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "素人",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202511/10/69114b47312f492881525a71/poster2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HKC-087"
  },
  {
    "id": 173625,
    "IDcode": "HMDNV-732",
    "title": "【レスで欲求不満】むっつり淫乱性欲ガチ強奥様28歳。担当美容師に浮気ち●ぽをおねだり！連続スプラッシュ生ハメイキ狂い中出しNTR！！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/11/08/d1d9bb452ae89033b37a74c0327d4fda.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-732"
  },
  {
    "id": 73076,
    "IDcode": "HMDNV-774",
    "title": "【美容サロン勤務】クール系むっつり美人妻 欲求不満ムラムラ性欲MAX ハードピストンでイキ狂う淫乱中出しNTR",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫乱，真实",
      "人妻",
      "NTR",
      "已婚妇女",
      "淫妻",
      "业余",
      "中出",
      "各种职业"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/23/68a8f0007f3b7c929073f647/cover.jpg",
    "actress": [
      "爱乃零"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-774"
  },
  {
    "id": 408237,
    "IDcode": "HMDNV-792",
    "title": "【同學會NTR】2OO,二十多歲的漂亮妻子,十年來首次與高中老師重逢,直奔酒店。他們瘋狂地渴望著彼此,並發生了他們有生以來第一次出軌和懷孕性交！ ！ [燒焦的木樁著火了]",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/21/68a7a93d8cce1a927aff3e32/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-792"
  },
  {
    "id": 408325,
    "IDcode": "HMDNV-831",
    "title": "328 【接受NTR委託】美巨乳大屁肉感S級年輕妻子。在肌肉操中尖叫高潮快感生內射【知曉性愛的喜悅】",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/10/6897d5cf55337d7f7bbc249f/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-831"
  },
  {
    "id": 61062,
    "IDcode": "HMDNV-833",
    "title": "フィジカル最強ジムトレーナー人妻32歳。アドレナリンMAXマッスルクレイジーファックでイキッパ吹きっぱNTRパワーファック！！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250811-1/0e7fd42d0a87f3ff1e1968318a4b5c53.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-833"
  },
  {
    "id": 186635,
    "IDcode": "HMDNV-843",
    "title": "【即イキ敏感体質】禁欲爆乳奥様 旦那の言いつけでオナ禁＆SEX禁止で爆発寸前 マッスルファック生中NTR！！【変態夫婦の狂気】",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/13/9c96bd22/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-843"
  },
  {
    "id": 174525,
    "IDcode": "HMDNV-869",
    "title": "【計画的NTR】美白美ボディむっつり奥様 SNSで知り合った男にハメ撮り依頼 即会い即ハメ即中出し【リベンジ浮気ハメ撮り】",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/11/01/f177525d488820f71a58a72247a366de.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMDNV-869"
  },
  {
    "id": 80419,
    "IDcode": "HMN-144",
    "title": "不倫命令立場逆転逆NTR-JULIA",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "已婚妇女",
      "出轨",
      "白天出轨",
      "淫妻",
      "无码破解",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://cktu02.sbs/images/2022/03/30/d47e29f815ebb08c6e3febd8dcc7ff4b.jpg",
    "actress": [
      "JULIA",
      "谷梓"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-144"
  },
  {
    "id": 80447,
    "IDcode": "HMN-145",
    "title": "彼女の親友に中出しさせられた後 賢者タイムも与えてもらえず追撃メスイキ逆NTRでアナルとチ○ポを犯●れ続けた僕。 白桃はな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "M男",
      "淫妻",
      "白天出轨",
      "肛交",
      "中出",
      "美少女电影",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "2022-03-22",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20220904-1/16707fee82774e702dc311b1d7aff88f.jpg",
    "actress": [
      "白桃はな"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-145"
  },
  {
    "id": 84553,
    "IDcode": "HMN-175",
    "title": "無碼破解版旅行地搭讪NTR脱下戒指和女性友人去温泉旅行的妻子被轻浮男搭讪播种",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "戏剧",
      "多P",
      "白天出轨",
      "淫妻",
      "中出",
      "巨乳",
      "单体作品",
      "无码"
    ],
    "type": "无码",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://img1.souavzy.org/upload/vod/20240924-1/5118c254f45c1b40dd55eeb5b2dd70ee.jpg",
    "actress": [
      "JULIA"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-175"
  },
  {
    "id": 84571,
    "IDcode": "HMN-176",
    "title": "情侶一起墮落NTR脅迫配信一念看著最愛的女友在眼前被中出連我也被一起搞痴女玩法中出",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫乱，真实",
      "NTR",
      "深喉",
      "白天出轨",
      "淫妻",
      "中出",
      "滥交",
      "兔女郎",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://fqjpg4.top/upload/vod/20240919-1/9277023cd8a1531b35cd590b5101ffbc.jpg",
    "actress": [
      "夏树カオル",
      "白桃はな",
      "白桃花"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-176"
  },
  {
    "id": 67282,
    "IDcode": "HMN-303",
    "title": "反转NTR后的斗争-浜崎真緒",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "荡妇",
      "白天出轨",
      "淫妻",
      "中出",
      "巨乳",
      "女生",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250512-6/292230448b9d951ba7ec77fb962284ef.jpg",
    "actress": [
      "タイ",
      "浜崎真绪"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-303"
  },
  {
    "id": 579256,
    "IDcode": "HMN-342",
    "title": "种付けされた后の制服射精で2度污す连射マーキングNTR 桜もこ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20230928/hmn342pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-342"
  },
  {
    "id": 167972,
    "IDcode": "HMN-361",
    "title": "深爱的女友被朋友们NTR-森下琴乃",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250512-3/437cd7c18ba9d03cd12b199ccdff5455.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-361"
  },
  {
    "id": 168165,
    "IDcode": "HMN-372",
    "title": "痴汉电车NTR-北野未奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202501/18/678a684689def9b1b80dbc88/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-372"
  },
  {
    "id": 168398,
    "IDcode": "HMN-419",
    "title": "兒子的母親出軌NTR告白-彌生美月",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "乱伦",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202505/19/682b25f2e7e672bea5f12ac1/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-419"
  },
  {
    "id": 168748,
    "IDcode": "HMN-424",
    "title": "一年已經沒有被碰的苗條身材人妻…跟公公在一個屋頂下 在密室空間裡 偷偷汗水直流下種NTR性愛 倉本菫",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202505/28/6836b0c5a0b87615b2d380ad/cover.jpg",
    "actress": [
      "倉本菫"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-424"
  },
  {
    "id": 60825,
    "IDcode": "HMN-444",
    "title": "這麼喜歡胸部到去摸摸茶？ 對結婚紀念日前晚去摸摸茶的老公嫉妬乳交！隔天到摸摸茶體驗入店與客人無套抽插報復中出逆NTR JULIA",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "已婚妇女",
      "淫妻",
      "白天出轨",
      "乳交",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202505/28/6836ee27a0b87615b2d63d7b/cover.jpg",
    "actress": [
      "JULIA"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-444"
  },
  {
    "id": 169037,
    "IDcode": "HMN-456",
    "title": "產後處女性愛高潮NTR 老公不在家被討厭的公公下藥的人妻 高潮一次不夠 體液直流 痙攣中出 玉城夏帆",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202505/28/6836b69fa0b87615b2d38351/cover.jpg",
    "actress": [
      "玉城夏帆"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-456"
  },
  {
    "id": 563405,
    "IDcode": "HMN-473",
    "title": "彼女の帰りが遅いと思ったら…逆バニー姿で生ハメしてました社内追奸NTR 职场恋爱していた他部署の",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20230917/YOC5sYRF/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-473"
  },
  {
    "id": 16767,
    "IDcode": "HMN-504",
    "title": "M性感風俗通俱樂部女孩嫉妬並用男人的雞巴炫耀她誘人的中出作爲懲罰的反向 NTR JOI 體驗",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "癡女",
      "蠻橫嬌羞",
      "淫妻",
      "勾引・誘惑",
      "出軌",
      "中出",
      "巨乳",
      "口交",
      "性感"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202501/18/678a4e60ac813dc779d9625f/cover.jpg",
    "actress": [
      "彌生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-504"
  },
  {
    "id": 15906,
    "IDcode": "HMN-533",
    "title": "你所有的精液都會射入我體內，彌生美月會勾引你的！逆向NTR自慰支持體驗！ ！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "胸控・戀乳癖",
      "自宅",
      "美乳",
      "按摩棒",
      "巨乳",
      "口交",
      "性感",
      "熟女",
      "潮吹",
      "人妻",
      "NTR",
      "淫亂",
      "內衣",
      "淫妻",
      "中出",
      "蕩婦",
      "後入",
      "絕頂高潮",
      "女優",
      "手指插入",
      "無毛",
      "乳交",
      "女上位",
      "騎乗位",
      "情趣內衣"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "2024-03-26",
    "cover_url": "https://picture.yoshiclub.xyz/20240323/20240323034006345345.jpg",
    "actress": [
      "彌生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-533"
  },
  {
    "id": 11155,
    "IDcode": "HMN-597",
    "title": "电车痴汉NTR-藤森里穗",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P・4P",
      "巨尻",
      "倉庫",
      "猥亵",
      "報復",
      "痴漢",
      "凌辱",
      "美腳",
      "強姦",
      "羞恥",
      "色白",
      "美乳",
      "變態",
      "亂交 • 群P",
      "口交",
      "性感",
      "熟女",
      "形象俱樂部",
      "兩男一女",
      "痴汉",
      "NTR",
      "人妻",
      "美人妻",
      "性騷擾",
      "淫亂",
      "淫妻",
      "特效",
      "中出",
      "後入",
      "美腿",
      "美臀",
      "劇情",
      "絕頂高潮",
      "輪姦",
      "上司女友・妻子",
      "電車",
      "黑絲",
      "女上位",
      "騎乗位"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202501/15/67876216c179ffb1db907be2/cover.jpg",
    "actress": [
      "藤森里穂"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-597"
  },
  {
    "id": 8997,
    "IDcode": "HMN-655",
    "title": "电车痴汉NTR-五日市芽依",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨尻",
      "若妻",
      "猥亵",
      "臀控",
      "美腳",
      "OL",
      "胸控・戀乳癖",
      "色白",
      "美乳",
      "制服",
      "巨乳",
      "口交",
      "性感",
      "潮吹",
      "痴汉",
      "人妻",
      "NTR",
      "美人妻",
      "淫妻",
      "中出",
      "蕩婦",
      "美人",
      "後入",
      "美臀",
      "劇情",
      "絕頂高潮",
      "上司女友・妻子",
      "電車",
      "脅迫做愛",
      "黑絲",
      "女上位",
      "偷窺",
      "騎乗位"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202502/24/67bb400c4e7d663df4a10204/cover.jpg",
    "actress": [
      "五日市芽依"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-655"
  },
  {
    "id": 8859,
    "IDcode": "HMN-670",
    "title": "访问女大学生NTR-静河",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "女學生",
      "巨尻",
      "身體換業務",
      "新人面試",
      "飯店",
      "辦公室",
      "肉絲",
      "OL",
      "羞恥",
      "寢取",
      "制服",
      "口交",
      "形象俱樂部",
      "NTR",
      "地味",
      "淫妻",
      "中出",
      "美人",
      "後入",
      "劇情",
      "脅迫做愛",
      "誘騙女性",
      "女上位",
      "騎乗位",
      "女同事"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://lust103.cc/upload/vod/20250209-1/6a1782ed9665dbe14d24e5dc1728eea7.jpg",
    "actress": [
      "静河"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-670"
  },
  {
    "id": 61596,
    "IDcode": "HMN-728",
    "title": "结婚纪念日全裸模春药中出群交NTR-五日市芽衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "多P",
      "白天出轨",
      "淫妻",
      "中出",
      "美少女电影",
      "巨乳",
      "单体作品"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/25/aa81cf72/vod.jpg",
    "actress": [
      "五日市芽依",
      "大志",
      "向理来"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-728"
  },
  {
    "id": 2808,
    "IDcode": "HMN-733",
    "title": "世界奇妙的幽灵NTR在凶宅里的地缚灵知道了我有女朋友-香水纯",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "奇聞趣事",
      "艷遇",
      "小隻馬",
      "慾求不滿",
      "苗條",
      "美少女",
      "美腳",
      "心理驚悚",
      "勾引・誘惑",
      "色白",
      "美乳",
      "口交",
      "性感",
      "接吻",
      "形象俱樂部",
      "潮吹",
      "單體作品",
      "NTR",
      "高顏值",
      "貧乳",
      "極品美人",
      "蠻橫嬌羞",
      "淫妻",
      "中出",
      "美人",
      "美腿",
      "後入",
      "少女",
      "美臀",
      "劇情",
      "奇異的",
      "絕頂高潮",
      "清純",
      "舔陰",
      "脚控・戀足癖",
      "手指插入",
      "女鬼・女妖",
      "無毛",
      "乳交",
      "女上位",
      "騎乗位"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/24/049250600ea345b20c924bec07493eb0.jpg",
    "actress": [
      "香水純"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-733"
  },
  {
    "id": 174557,
    "IDcode": "HMN-741",
    "title": "逆NTR 私をいじめてた女達の最愛の人を目の前で乳首開発チ○ポがバカになるまで中出しを奪ってやる 沙月恵奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "本中",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/11/01/46503b0274980f7147f753ed2e109272.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMN-741"
  },
  {
    "id": 13143,
    "IDcode": "HMRK-015",
    "title": "【兄妹情侶NTR性愛】美少女妹妹有着魔鬼蜜桃臀！勾引睡着的哥哥 ~ 小那海綾",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "素人作品",
      "飯店",
      "苗條",
      "亂倫",
      "感官作品",
      "4K",
      "美少女",
      "美腳",
      "姐弟・兄妹",
      "勾引・誘惑",
      "美乳",
      "口交",
      "性感",
      "形象俱樂部",
      "潮吹",
      "NTR",
      "淫妻",
      "出軌",
      "中出",
      "蕩婦",
      "姐姐・妹妹",
      "美腿",
      "美臀",
      "劇情",
      "顏射",
      "絕頂高潮",
      "脚控・戀足癖",
      "美少女電影",
      "乱伦",
      "黑絲",
      "女上位"
    ],
    "type": "",
    "company": "DOC",
    "publish_date": "2024-07-19",
    "cover_url": "https://picture.yoshiclub.xyz/20240722/4028678e-0d45-4dcd-a7cd-bcf0e409153e.jpg",
    "actress": [
      "小那海綾"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMRK-015"
  },
  {
    "id": 565058,
    "IDcode": "HMRK-026",
    "title": "【I乳エロむちボディ】结婚间近のリア充カップルが登场！自慢の爆乳彼女が他人にNTR！彼氏より上",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻",
      "巨乳"
    ],
    "type": "",
    "company": "DOC",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20241224/9auBbL9Q/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HMRK-026"
  },
  {
    "id": 174977,
    "IDcode": "HNAMH-023",
    "title": "2年ぶりの真正中出しNTR 旦那に無許可で3発受入 まい（妻）",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "SOD",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/10/28/f3b1aabb/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HNAMH-023"
  },
  {
    "id": 521168,
    "IDcode": "HND-256",
    "title": "被大雪困在东京的气象女神！阴湿制作人借机同房NTR胁迫中出 淫水流满摄制现场",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20250813-1/7625955771692d6e81bc3347050ce04f.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HND-256"
  },
  {
    "id": 209414,
    "IDcode": "HND-526",
    "title": "社員旅行NTRAI 佐々木あき",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2020/06/25/QQ202006252121012efe2.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HND-526"
  },
  {
    "id": 534602,
    "IDcode": "HND-596",
    "title": "Fカップ超美肌妻がNTRマニアの夫のために生ハメ＆中出し解禁！ 1回目は若いヤリチン男优と同时",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "淫妻"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20190517-1/adfda52f9471c5dea4fa50b60d053a42.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HND-596"
  },
  {
    "id": 71707,
    "IDcode": "HND-608",
    "title": "巨乳女教師と男子生徒禁断の純愛NTR中出し日記 河北麻衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "淫妻",
      "白天出轨",
      "女教师",
      "中出",
      "巨乳",
      "学校作品"
    ],
    "type": "",
    "company": "",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20230918-1/db9bef2c078dd9c4f81d29859f7088a9.jpg",
    "actress": [
      "蓝井优太",
      "河北麻衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HND-608"
  },
  {
    "id": 74498,
    "IDcode": "HND-705",
    "title": "別れた婚約者にアポ電NTR ゲス元カレが婚約者の弟になりすまし、結婚目前に中出ししまくった一部始終。 高杉麻里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "出轨",
      "白天出轨",
      "淫妻",
      "乳房",
      "中出",
      "美少女电影"
    ],
    "type": "",
    "company": "",
    "publish_date": "2019-07-25",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20250103-1/23150839b4183acfd20487f223ec60ff.jpg",
    "actress": [
      "高杉麻里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=HND-705"
  }
];