episodes = {};

seriesInfo = {
  "id": 2083,
  "IDcode": "SONE-935",
  "title": "電車癡漢，絕對不行 ~ 櫻乃莉乃",
  "publish_date": "2025-10-09",
  "type": "有码",
  "company": "S1",
  "genres": [
    "苗條",
    "後入",
    "高顏值",
    "劇情",
    "猥亵",
    "舔腳",
    "二次元",
    "絕頂高潮",
    "4K",
    "傲嬌",
    "校花",
    "脚控・戀足癖",
    "形象俱樂部",
    "電車",
    "女上位",
    "空姐制服",
    "JK校服",
    "口交",
    "運動服裝",
    "小隻馬",
    "騎乗位",
    "蠻橫嬌羞",
    "舔陰",
    "性騷擾",
    "少女",
    "接吻",
    "貧乳",
    "美腳",
    "美少女",
    "清楚系",
    "單體作品",
    "清純",
    "手指插入",
    "美人",
    "阪道系",
    "美少女電影",
    "女學生",
    "無毛",
    "網路紅人"
  ],
  "description": "SONE-935为S1出品,2025年10月9日发行的有碼成人影片由櫻乃莉乃出演\n【本来觉得痴汉绝对不能忍，但…】我，櫻乃莉乃，上学坐电车的时候老被痴汉骚扰。心里超想大声喊这家伙是痴汉！但就是不敢开口。最近新闻里那些事看着就怕，万一对方发飙咋办。某天又被痴汉盯上了，但这次感觉不一样！首先是气味，最近那些男人都是一身香水味刺鼻，这哥们儿却满是汗味，超MAN，是我超爱的味道…其次是手法，摸得太牛了！手指灵活得要命，像是完全知道我哪里最敏感…在电车里被弄得高潮迭起，爽到不行。这种感觉第一次体验，恨不得早点遇到！什么用勇气制止痴汉，我做不到啦！姐妹们，你们也试试？＃痴汉我原谅你了！",
  "cover_url": "https://picture.yoshiclub.xyz/compressed/20251009/20251009042738837837_12777_thumbnail.webp",
  "background_img": "https://picture.yoshiclub.xyz/compressed/20251009/20251009042738837837_12777_s.webp",
  "title_play_url": "https://erik7761269084-arch.github.io/-/JAV/player_template.html?series=2083",
  "actresses": [
    {
      "name": "櫻乃莉乃",
      "img_url": "https://picture.yoshiclub.xyz/20250306/88344ec0-e1a4-4e79-b4fa-6efdfc49727f.jpg",
      "profile_url": "https://erik7761269084-arch.github.io/-/AV/AVactressDatas.html?series=2083&name=櫻乃莉乃"
    }
  ]
};
