episodes = {};

seriesInfo = {
  "id": 2305,
  "IDcode": "FPRE-199",
  "title": "肉感爆乳小嬌妻慾火焚身，舔遍全身誘惑難擋 ~ 姫咲華",
  "publish_date": "2025-10-02",
  "type": "有码",
  "company": "FITCH",
  "genres": [
    "後入",
    "黑絲",
    "高顏值",
    "濕身",
    "家庭主妇",
    "劇情",
    "巨尻",
    "絕頂高潮",
    "網襪",
    "超爆乳",
    "臀控",
    "流汗",
    "乳交",
    "大乳暈",
    "中出",
    "美乳",
    "美腿",
    "美臀",
    "形象俱樂部",
    "胸控・戀乳癖",
    "女上位",
    "口交",
    "騎乗位",
    "若妻",
    "性感",
    "不倫",
    "舔陰",
    "慾求不滿",
    "接吻",
    "口爆",
    "勾引・誘惑",
    "鄰居",
    "單體作品",
    "美人妻",
    "情趣內衣",
    "艷遇",
    "癡女",
    "人妻",
    "巨乳",
    "手指插入",
    "出軌",
    "偷竊",
    "抹油",
    "NTR",
    "美人",
    "綠茶婊",
    "豐滿",
    "無毛"
  ],
  "description": "FPRE-199为FITCH出品,2025年10月2日发行的有碼成人影片由姫咲華出演\n姫咲華化身欲求不满的小娇妻，饥渴到不行，见到男人就忍不住舔个不停！穿着超暴露的性感衣服，爆乳深沟一览无遗，在小区里晃悠，简直就是行走的诱惑。老公不在家，她的欲火早就烧到顶点了！这具肉感十足、曲线完美的身材一旦被点燃，就化身舔舐狂魔，根本停不下来！浓烈的舔戏不仅视觉炸裂，连那淫靡的声音都能让人耳朵怀孕，兴奋度直接拉满！",
  "cover_url": "https://picture.yoshiclub.xyz/compressed/20251002/20251002053618713713_92204_thumbnail.webp",
  "background_img": "https://picture.yoshiclub.xyz/compressed/20251002/20251002053618713713_92204_s.webp",
  "title_play_url": "https://erik7761269084-arch.github.io/-/JAV/player_template.html?series=2305",
  "actresses": [
    {
      "name": "姫咲華",
      "img_url": "https://picture.yoshiclub.xyz/20231010/1cb32d64-ec1d-49cb-9f9d-6ad61fe73925.jpg",
      "profile_url": "https://erik7761269084-arch.github.io/-/AV/AVactressDatas.html?series=2305&name=姫咲華"
    }
  ]
};
