window.PAGE_DATA = [
  {
    "id": 516804,
    "IDcode": "CESD-987",
    "title": "CESD-987 我们根本没有停止拍摄！望月绫香（Ayaka Mochizuki）不停的女同性恋地狱责备！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "3P",
      "女同",
      "4P",
      "熟女",
      "女同接吻",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-03-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/CESD-987.jpg",
    "actress": [
      "波多野结衣",
      "望月綾香",
      "葵玲奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=CESD-987"
  },
  {
    "id": 410514,
    "IDcode": "CESD-992",
    "title": "CESD-992 首次女同性恋禁令Mao Watanabe 生平第一次尝试与 Rena Aoi 进行女同性恋性行为！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "女同",
      "美胸",
      "熟女",
      "女同接吻",
      "胸部"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-04-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/CESD-992.jpg",
    "actress": [
      "葵玲奈",
      "有村千佳"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=CESD-992"
  },
  {
    "id": 519717,
    "IDcode": "DGCEMD-002",
    "title": "DGCEMD-002 发行有限！附赠片段★培育一个完全按照我的意愿行事的性玩偶 Hikari Sena",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "合集",
      "素人",
      "单人作品",
      "重口味",
      "精选",
      "熟女",
      "巨乳",
      "拘束"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-04-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-002.jpg",
    "actress": [
      "広瀬藍子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-002"
  },
  {
    "id": 411431,
    "IDcode": "DGCEMD-005",
    "title": "DGCEMD-005 发行有限！包括奖励片段 ★ 喷水是女性之间爱的表达。喷水亲密女同 Mihina Jinno Hina",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "潮吹",
      "女同",
      "素人",
      "精选",
      "熟女",
      "4K",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-05-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-005.jpg",
    "actress": [
      "佐倉陽菜",
      "神野雛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-005"
  },
  {
    "id": 435841,
    "IDcode": "DGCEMD-006",
    "title": "DGCEMD-006 发行有限！附赠片段 ★快感！初次体验！堀北婉 - 第一次在公共场合撒尿 SEX 文档",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "合集",
      "潮吹",
      "素人",
      "单人作品",
      "重口味",
      "精选",
      "放尿",
      "熟女",
      "4K",
      "羞辱"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-05-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-006.jpg",
    "actress": [
      "堀北わん"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-006"
  },
  {
    "id": 411435,
    "IDcode": "DGCEMD-012",
    "title": "★配信限定！特典映像付★初レズ解禁！塩見彩があおいれなからハードレズ調教してもらった件  塩見彩 葵玲奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-012.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-012"
  },
  {
    "id": 559584,
    "IDcode": "DGCEMD-017",
    "title": "DGCEMD-017 发行有限！包括赠送的视频 *来得太匆忙，下得了地狱！来得太多，地狱也太多！提高敏感度的最强黑秘技！ 森泽加奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "胸部",
      "合集",
      "电动按摩器",
      "素人",
      "口交",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "苗条"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-06-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-017.jpg",
    "actress": [
      "森澤佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-017"
  },
  {
    "id": 411439,
    "IDcode": "DGCEMD-018",
    "title": "DGCEMD-018 限量发行！附赠精彩视频★这些女人都是 \"M-women\"！因为她们是女权支配者，所以她们懂得痛苦之外的非凡快感！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "白虎",
      "合集",
      "3P",
      "女同",
      "4P",
      "素人",
      "精选",
      "熟女",
      "4K",
      "指交"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-06-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-018.jpg",
    "actress": [
      "紗紗原百合",
      "塩見彩",
      "有村千佳"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-018"
  },
  {
    "id": 521019,
    "IDcode": "DGCEMD-055",
    "title": "瀬名ひかり- ★配信限定！特典映像付★男をいじめると感じる女子は実在する！瀬名ひかり ～男の苦痛を耐える",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-055.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-055"
  },
  {
    "id": 84300,
    "IDcode": "DGCEMD-086",
    "title": "DGCEMD-086 发行有限！附赠视频 *身心解体，任我摆布 Rina Takase - 把我当成淫荡、贪得无厌的宠物。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "合集",
      "素人",
      "成熟的女人",
      "单人作品",
      "放尿",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "拘束"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-11-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-086.jpg",
    "actress": [
      "高瀬りな"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-086"
  },
  {
    "id": 435757,
    "IDcode": "DGCEMD-087",
    "title": "DGCEMD-087 限量发行！附赠视频 *抱歉尿你一身...... 32 - Hana Shiratomo",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "胸部",
      "合集",
      "素人",
      "单人作品",
      "精选",
      "放尿",
      "熟女",
      "4K",
      "羞辱",
      "拘束"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-11-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-087.jpg",
    "actress": [
      "白桃はな"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-087"
  },
  {
    "id": 84318,
    "IDcode": "DGCEMD-088",
    "title": "DGCEMD-088 发行有限！附赠片段 ★ Nakadashi！Ninnari Goji Maid 2: Satsuki Mei - 我的命令是绝对的！里月媚的身体可以被完全支配！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "女佣",
      "4K",
      "合集",
      "胸部",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "熟女",
      "手交",
      "手淫",
      "素人作品",
      "主观视角",
      "乳房",
      "女仆"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-11-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-088.jpg",
    "actress": [
      "沙月芽衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-088"
  },
  {
    "id": 539149,
    "IDcode": "DGCEMD-089",
    "title": "DGCEMD-089 仅发行！Akari Niimura - 饮酒后变得淫荡的身体通过肛交获得了生命！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "肛门",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "巨乳"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-11-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-089.jpg",
    "actress": [
      "新村朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-089"
  },
  {
    "id": 84296,
    "IDcode": "DGCEMD-090",
    "title": "DGCEMD-090 发行有限！附赠片段 ★住在垃圾房里的大胸美女 Sena Hikari - 在垃圾房里进行的激烈性爱中，她摇晃着淫荡的 H 罩杯，一次又一次地疯狂射精！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "白虎",
      "精选，综合",
      "中出",
      "合集",
      "内射",
      "素人",
      "剧情",
      "成熟的女人",
      "单人作品",
      "戏剧",
      "无毛",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-11-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-090.jpg",
    "actress": [
      "広瀬藍子",
      "瀨名光"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-090"
  },
  {
    "id": 84314,
    "IDcode": "DGCEMD-097",
    "title": "DGCEMD-097 发行有限！附赠视频 ★诱惑丁字裤女管家！ 北野美奈 - 淫荡女管家，用 H 罩杯大奶子和丁字裤屁股榨取精液！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "中出",
      "合集",
      "内射",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2021-12-14",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-097.jpg",
    "actress": [
      "北野未奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-097"
  },
  {
    "id": 539150,
    "IDcode": "DGCEMD-105",
    "title": "新村あかり- ★配信限定！特典映像付★七瀬いおりレズ解禁！×春菜はな×新村あかり～巨乳美女3人が激しく络",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-105.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-105"
  },
  {
    "id": 84316,
    "IDcode": "DGCEMD-119",
    "title": "DGCEMD-119 ★发行有限！附赠片段★ 母子肛交女同性恋望月绫香（Ayaka Mochizuki）岩泽佳代（Kayo Iwasawa）--将婆婆的肛门归咎于一个女人的淫荡变态女儿！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "合集",
      "乱伦",
      "女同",
      "肛交",
      "侮辱",
      "肛门",
      "素人",
      "成熟的女人",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "女同性恋"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-01-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-119.jpg",
    "actress": [
      "望月綾香",
      "岩沢香代"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-119"
  },
  {
    "id": 470671,
    "IDcode": "DGCEMD-132",
    "title": "DGCEMD-132 限量发行！附赠视频 ★我培育了一个随心所欲的性玩偶 vol.8 Meru Ito",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "胸部",
      "合集",
      "内射",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "拘束"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-02-22",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-132.jpg",
    "actress": [
      "Nia"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-132"
  },
  {
    "id": 411489,
    "IDcode": "DGCEMD-133",
    "title": "DGCEMD-133 限量发行！附赠片段★关于年龄差异和女同性恋的课程！Alice Kisaki 与 Chisato Shoda - 第一次体会到女同性恋快感的女性在床上剧烈扭动并高潮！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "4K",
      "女同",
      "素人",
      "精选",
      "熟女",
      "巨臀",
      "巨乳",
      "舔阴"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-02-22",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-133.jpg",
    "actress": [
      "翔田千里",
      "希咲愛莉絲"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-133"
  },
  {
    "id": 84317,
    "IDcode": "DGCEMD-134",
    "title": "DGCEMD-134 送货有限！附赠片段 ★拥有让时间停止的力量的淫荡女人！波多野结衣 - 她用自己的力量让男人多次射精！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "合集",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "戏剧",
      "精选",
      "剧情",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-02-22",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-134.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-134"
  },
  {
    "id": 435914,
    "IDcode": "DGCEMD-144",
    "title": "DGCEMD-144 ★发行有限！附赠视频★全身沾满油污的性爱，她是一个拥有湿滑快感的女性 4 Mei Satsuki.",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "3P",
      "润滑液",
      "坐脸",
      "4P",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "巨乳"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-03-22",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-144.jpg",
    "actress": [
      "沙月芽衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-144"
  },
  {
    "id": 84298,
    "IDcode": "DGCEMD-145",
    "title": "DGCEMD-145 送货有限！附赠片段★住在垃圾房里的大胸美女 2 波多野结衣 - 被垃圾包围的大胸变态女的淫荡，让她的下体湿漉漉的！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "合集",
      "口交",
      "巨大屁股",
      "成熟的女人",
      "单人作品",
      "戏剧",
      "素人",
      "精选",
      "剧情",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-03-22",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-145.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-145"
  },
  {
    "id": 84303,
    "IDcode": "DGCEMD-167",
    "title": "DGCEMD-167 限量发行！附赠视频 - 住在隔壁的年轻淫荡人妻 - Yukari Murasaki",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "合集",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品",
      "主观视角",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-05-10",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-167.jpg",
    "actress": [
      "紫月由香里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-167"
  },
  {
    "id": 539151,
    "IDcode": "DGCEMD-178",
    "title": "新村あかり- ★配信限定！特典映像付★巨乳·淫乱·性獣たちの最狂レズビアン",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-178.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-178"
  },
  {
    "id": 87407,
    "IDcode": "DGCEMD-204",
    "title": "DGCEMD-204 发行有限！附赠视频 ★首个女同性恋禁令！帝国柚子与波多野结衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "精选，综合",
      "合集",
      "潮吹",
      "女同",
      "淫乱，真实",
      "素人",
      "成熟的女人",
      "重口味",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "女同性恋",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-07-26",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-204.jpg",
    "actress": [
      "波多野结衣",
      "皇柚子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-204"
  },
  {
    "id": 87412,
    "IDcode": "DGCEMD-205",
    "title": "DGCEMD-205 发行有限！附赠片段★舔沾满叔叔口水的脸而兴奋的女子星川舞",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "合集",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "淫语",
      "熟女",
      "脏话",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-07-26",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-205.jpg",
    "actress": [
      "安西天"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-205"
  },
  {
    "id": 87423,
    "IDcode": "DGCEMD-206",
    "title": "DGCEMD-206 发行有限！附赠片段★Akari Niimura，勾引我的邻家紧身金发女郎。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "精选，综合",
      "合集",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "淫语",
      "熟女",
      "脏话",
      "4K",
      "人妻",
      "素人作品",
      "巨乳",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-07-26",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-206.jpg",
    "actress": [
      "新村朱里",
      "新村晶"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-206"
  },
  {
    "id": 87411,
    "IDcode": "DGCEMD-207",
    "title": "DGCEMD-207 发行有限！附赠片段★\"我不听！\"所有场景均可立即性交！ 2 Mei Satsuki",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "素人",
      "重口味",
      "熟女",
      "4K",
      "乳房",
      "单体作品",
      "女上位",
      "下流",
      "胸部",
      "3P",
      "4P",
      "单人作品",
      "精选",
      "素人作品",
      "合集",
      "淫乱，真实",
      "精选，综合",
      "成熟的女人",
      "多P"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-07-26",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-207.jpg",
    "actress": [
      "沙月芽衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-207"
  },
  {
    "id": 87436,
    "IDcode": "DGCEMD-209",
    "title": "DGCEMD-209 发行有限！附赠视频 *只有一个肛交复兴！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "巨臀",
      "合集",
      "肛交",
      "肛门",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-07-26",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-209.jpg",
    "actress": [
      "推川悠里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-209"
  },
  {
    "id": 84299,
    "IDcode": "DGCEMD-219",
    "title": "DGCEMD-219 发行有限！附赠片段★让我们在露营车里做爱吧！7 Akari Niimura",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "精选，综合",
      "巨臀",
      "合集",
      "淫乱，真实",
      "车震",
      "巨大屁股",
      "素人",
      "成熟的女人",
      "单人作品",
      "重口味",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品",
      "汽车性爱"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-08-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-219.jpg",
    "actress": [
      "新村朱里",
      "新村晶"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-219"
  },
  {
    "id": 84301,
    "IDcode": "DGCEMD-220",
    "title": "DGCEMD-220 限量发行！附赠片段★搬到隔壁的年轻淫荡人妻被非常色情的内裤女魔头 2 Mei Uesaka 勾引。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "下流",
      "精选，综合",
      "合集",
      "淫乱，真实",
      "内衣",
      "素人",
      "成熟的女人",
      "单人作品",
      "重口味",
      "精选",
      "短裙",
      "熟女",
      "人妻",
      "4K",
      "素人作品",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-08-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-220.jpg",
    "actress": [
      "上坂芽衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-220"
  },
  {
    "id": 84312,
    "IDcode": "DGCEMD-224",
    "title": "DGCEMD-224 限量发行！附赠片段★拥有让时间停止的力量的下流荡妇！3 仓木葵",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "胸部",
      "中出",
      "合集",
      "内射",
      "素人",
      "剧情",
      "成熟的女人",
      "单人作品",
      "戏剧",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "乳房",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-08-23",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-224.jpg",
    "actress": [
      "枢木葵"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-224"
  },
  {
    "id": 87425,
    "IDcode": "DGCEMD-235",
    "title": "DGCEMD-235 限量发行！附赠视频 *抱歉尿你一身...... 38 田名光树",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "精选，综合",
      "合集",
      "潮吹",
      "淫乱，真实",
      "素人",
      "成熟的女人",
      "单人作品",
      "重口味",
      "放尿",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-09-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-235.jpg",
    "actress": [
      "唯奈みつき"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-235"
  },
  {
    "id": 87434,
    "IDcode": "DGCEMD-236",
    "title": "DGCEMD-236 发行有限！附赠视频 ★首个女同性恋禁令！本田瞳与波多野结衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "精选，综合",
      "合集",
      "女同",
      "淫乱，真实",
      "素人",
      "成熟的女人",
      "重口味",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨乳",
      "女同性恋",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-09-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-236.jpg",
    "actress": [
      "波多野结衣",
      "本田瞳"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-236"
  },
  {
    "id": 87437,
    "IDcode": "DGCEMD-237",
    "title": "DGCEMD-237 发行有限！附赠片段 ★尖叫！痛苦晕倒部分开发！子宫深处的女人 7 Akari Minase",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乳液",
      "精选，综合",
      "下流",
      "合集",
      "大鸡巴",
      "润滑液",
      "淫乱，真实",
      "素人",
      "成熟的女人",
      "单人作品",
      "重口味",
      "精选",
      "熟女",
      "4K",
      "素人作品",
      "巨大阴茎",
      "单体作品",
      "子宫颈"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-09-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-237.jpg",
    "actress": [
      "皆瀨明里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-237"
  },
  {
    "id": 87409,
    "IDcode": "DGCEMD-240",
    "title": "DGCEMD-240 发行有限！附赠片段 ★ 住在隔壁的年轻淫荡妻子，被她的情色连裤袜诱惑 3: Momo Minami。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "精选，综合",
      "超乳",
      "合集",
      "乱伦",
      "侮辱",
      "超巨乳",
      "内衣",
      "素人",
      "成熟的女人",
      "单人作品",
      "短裙",
      "精选",
      "熟女",
      "人妻",
      "4K",
      "素人作品",
      "单体作品"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-09-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-240.jpg",
    "actress": [
      "美波桃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-240"
  },
  {
    "id": 535686,
    "IDcode": "DGCEMD-247",
    "title": "DGCEMD-247 发行有限！附赠视频 ★首次女同发行！北野由奈 - 我想被姐姐欺负与新村明里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "女同",
      "素人",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-10-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-247.jpg",
    "actress": [
      "新村朱里",
      "北乃由奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-247"
  },
  {
    "id": 539153,
    "IDcode": "DGCEMD-248",
    "title": "DGCEMD-248 发行有限！附赠片段★拥有让时间停止的力量的淫荡女人！4 Akari Niimura",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "内射",
      "素人",
      "剧情",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-10-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-248.jpg",
    "actress": [
      "新村朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-248"
  },
  {
    "id": 592768,
    "IDcode": "DGCEMD-262",
    "title": "★配信限定特典映像付★絶叫闷絶ポルチオ开発子宫の奥にある奥の奥でイク女8 白花こう",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-262.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-262"
  },
  {
    "id": 535690,
    "IDcode": "DGCEMD-264",
    "title": "大人の极上美女レズビアン2 波多野结衣×枢木あお",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-264.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-264"
  },
  {
    "id": 411536,
    "IDcode": "DGCEMD-276",
    "title": "DGCEMD-276 ★发行有限！附赠片段★大奶、淫荡、性兽最疯狂的女同性恋 2 望月绫香 新村明里 田名光树",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨臀",
      "合集",
      "女同",
      "素人",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2022-12-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-276.jpg",
    "actress": [
      "新村朱里",
      "望月綾香",
      "唯奈みつき"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-276"
  },
  {
    "id": 411537,
    "IDcode": "DGCEMD-292",
    "title": "DGCEMD-292 发行有限！附赠视频 ★首次女同发行！上坂友子与新村明里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "女同",
      "超巨乳",
      "素人",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-02-14",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-292.jpg",
    "actress": [
      "新村朱里",
      "神坂朋子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-292"
  },
  {
    "id": 535697,
    "IDcode": "DGCEMD-301",
    "title": "DGCEMD-301 送货有限！附赠视频 *波多野心身医学：洗脑式女同性恋疗法，解决你的问题。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "女同",
      "素人",
      "剧情",
      "精选",
      "熟女",
      "4K",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-02-28",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-301.jpg",
    "actress": [
      "波多野结衣",
      "緒川春",
      "北乃由奈",
      "唯奈みつき",
      "皆川るい"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-301"
  },
  {
    "id": 533180,
    "IDcode": "DGCEMD-319",
    "title": "DGCEMD-319 发行有限！附赠片段★如果！如果男子一对一烹饪班的老师是个美女、大胸和荡妇呢？ 本冈爱理",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "内射",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "荡妇",
      "裸体围裙"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-04-11",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-319.jpg",
    "actress": [
      "穂花あいり"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-319"
  },
  {
    "id": 535700,
    "IDcode": "DGCEMD-322",
    "title": "DGCEMD-322 限量发行！附赠花絮 ★性怪兽 \"望月绫香 \"教菜鸟女演员 \"花名有菜 \"如何做爱！她们相处融洽，享受无尽的女同快感！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "潮吹",
      "女同",
      "素人",
      "精选",
      "熟女",
      "4K",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-04-11",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-322.jpg",
    "actress": [
      "望月綾香",
      "花芽有朱"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-322"
  },
  {
    "id": 535705,
    "IDcode": "DGCEMD-323",
    "title": "DGCEMD-323 限量发行！附赠片段★互相凝视的幸福女同性恋 - SEX 文件 Aoi Kurugi 和 Jun Suehiro。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "女同",
      "女同接吻",
      "素人",
      "精选",
      "熟女",
      "4K",
      "舔阴",
      "纪录片"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-04-25",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-323.jpg",
    "actress": [
      "末広純",
      "枢木葵"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-323"
  },
  {
    "id": 572346,
    "IDcode": "DGCEMD-331",
    "title": "DGCEMD-331 *发行有限！附赠片段★自律神经系统被震撼！汗流浃背的高潮硬汉性爱！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "出汗",
      "合集",
      "3P",
      "大鸡巴",
      "4P",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-05-09",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-331.jpg",
    "actress": [
      "花柳杏奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-331"
  },
  {
    "id": 535713,
    "IDcode": "DGCEMD-345",
    "title": "DGCEMD-345 限量发行！附赠花絮 ★望月绫香（Ayaka Mochizuki）培养和训练女同性恋！Mio Ichijo 带着呆萌的眼神跌入快感女同沼泽！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "潮吹",
      "女同",
      "素人",
      "精选",
      "熟女",
      "4K",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-06-13",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-345.jpg",
    "actress": [
      "一条美緒",
      "望月綾香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-345"
  },
  {
    "id": 535725,
    "IDcode": "DGCEMD-351",
    "title": "DGCEMD-351 发行有限！附赠视频 ★后庭发情！～凭直觉感受！美丽的女同性恋在呻吟，在快乐中疯狂 - Anzu Komatsu x Akari Niimura",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "女同",
      "肛门",
      "素人",
      "精选",
      "熟女",
      "4K",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-06-27",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-351.jpg",
    "actress": [
      "新村朱里",
      "小松杏"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-351"
  },
  {
    "id": 548825,
    "IDcode": "DGCEMD-360",
    "title": "DGCEMD-360 发行有限！附赠片段★让我们在露营车里做爱吧！10 Haruna Hana",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "车震",
      "素人",
      "单人作品",
      "精选",
      "熟女",
      "4K",
      "巨乳",
      "纪录片"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-07-11",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-360.jpg",
    "actress": [
      "春菜华"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-360"
  },
  {
    "id": 535729,
    "IDcode": "DGCEMD-376",
    "title": "DGCEMD-376 限量发行！附赠送片段★不间断的女同性恋不间断的女同性恋性爱，Mei Satsuki 和 Ayaka Mochizuki 不断折磨她，让她射精，直到让她说 \"对不起\"。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "高清画质",
      "合集",
      "女同",
      "素人",
      "精选",
      "放尿",
      "4K",
      "舔阴",
      "女同接吻"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-08-08",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-376.jpg",
    "actress": [
      "沙月芽衣",
      "望月綾香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-376"
  },
  {
    "id": 539152,
    "IDcode": "DGCEMD-446",
    "title": "DGCEMD-446 限量发行！附赠花絮★每天用性爱诱惑我的婆婆，帮助我重新站起来的婆婆2 Akari Niimura",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "继母",
      "侮辱",
      "素人",
      "剧情",
      "单人作品",
      "精选",
      "熟女",
      "4K"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-12-12",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-446.jpg",
    "actress": [
      "新村朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-446"
  },
  {
    "id": 562657,
    "IDcode": "DGCEMD-448",
    "title": "DGCEMD-448 发行有限！附赠视频 ★\"Mizuki Yayoi \"教变性人 \"Nurumayu \"如何成为女孩！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "合集",
      "女同",
      "跨性别",
      "素人",
      "重口味",
      "精选",
      "4K",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2023-12-12",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-448.jpg",
    "actress": [
      "彌生美月",
      "ヌルマユ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-448"
  },
  {
    "id": 539103,
    "IDcode": "DGCEMD-524",
    "title": "DGCEMD-524 发行有限！附赠视频 ★欺负男人时有感觉的女孩是真实存在的 9 新村明里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "下流",
      "合集",
      "素人",
      "单人作品",
      "重口味",
      "精选",
      "放尿",
      "4K",
      "巨乳",
      "荡妇"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2024-05-14",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-524.jpg",
    "actress": [
      "新村朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-524"
  },
  {
    "id": 538195,
    "IDcode": "DGCEMD-540",
    "title": "DGCEMD-540 发行有限！附赠片段★突然抢走普通女职员，将其变为性工作者 5 白石桃子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "合集",
      "恶女",
      "内射",
      "素人",
      "单人作品",
      "药物",
      "精选",
      "4K",
      "拘束"
    ],
    "type": "有码",
    "company": "セレブの友",
    "publish_date": "2024-06-11",
    "cover_url": "https://raw.githubusercontent.com/erik7761269084-arch/JAV_COVER/main/日本AV/正式封面/DGCEMD-540.jpg",
    "actress": [
      "白石桃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DGCEMD-540"
  }
];