window.PAGE_DATA = [
  {
    "id": 11872,
    "IDcode": "5805",
    "title": "绞肉姬 葛城美里",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/66ed6eb6d83406817edd5.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11871,
    "IDcode": "5804",
    "title": "绞肉姬 玛奇玛逆兔女郎",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[\"兽耳娘\"]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/5ff13c1be686a549cf5d9.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11870,
    "IDcode": "5803",
    "title": "絞肉姬Walküre 芽亚里兔女郎",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[\"兽耳娘\"]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/e8913b255ec4139c92a0e.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11869,
    "IDcode": "5802",
    "title": "絞肉姬Walküre 喜多川海梦",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/c0537a8b27a4a8f6bf495.png",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11868,
    "IDcode": "5801",
    "title": "比奇堡黄塞方块 甘雨玉桂狗",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[\"原神\"]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/4a8e0c5a8ffab3bbee492.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11867,
    "IDcode": "5800",
    "title": "絞肉姬Walküre 明日方舟W愚夜密函",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://telegra.ph/file/b415383ffc0d7b5fe18f2.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11864,
    "IDcode": "5799",
    "title": "絞肉姬Walküre - 2024.09 牧濑红莉栖",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2024/10/19/Makise-Kurisu-46.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11863,
    "IDcode": "5798",
    "title": "絞肉姬Walküre - 宝多六花校服 41P",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[\"校服\"]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2024/10/26/1-41.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11862,
    "IDcode": "5797",
    "title": "絞肉姬Walküre - 骸音囚人与纸飞机",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2024/11/04/1-10db649e12c3b1e80a.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11861,
    "IDcode": "5796",
    "title": "絞肉姬Walküre - Asuka",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2024/11/04/01-291087e247da2dbdf7.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11860,
    "IDcode": "5795",
    "title": "絞肉姬Walküre - Hoshimi Miyabi",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2025/05/07/01_miyabi_1.jpg",
    "actress": [],
    "title_play_url": null
  },
  {
    "id": 11859,
    "IDcode": "5794",
    "title": "絞肉姬Walküre - Magia Baiser",
    "year": null,
    "country": null,
    "genre": null,
    "genres": "[]",
    "type": null,
    "company": null,
    "publish_date": null,
    "cover_url": "https://image.acg.lol/file/2025/06/05/1-1027d1218dbffca63.jpg",
    "actress": [],
    "title_play_url": null
  }
];