const comicData = {
    "IDcode": 41857,
    "title": "Aery Tiefling - Nami (One Piece)",
    "sourceUrl": "https://telegra.ph/Galería-de-imágenes-08-20-10",
    "images": [
        "https://i.ibb.co/8p9KwhL/00-Aery-Tiefling-Nami.jpg",
        "https://i.ibb.co/tTNvyXbd/01-Aerytiefling-Nami-01.jpg",
        "https://i.ibb.co/xSJGrkKx/02-Aerytiefling-Nami.jpg",
        "https://i.ibb.co/XfQDVzTv/Aerytiefling-Nami.jpg",
        "https://i.ibb.co/p6R3srFN/Aerytiefling-Nami-01.jpg",
        "https://i.ibb.co/0R2yZP4Y/Aerytiefling-Nami-02.jpg",
        "https://i.ibb.co/RZK2kWx/Aerytiefling-Nami-03.jpg",
        "https://i.ibb.co/tPc3q9VC/Aerytiefling-Nami-04.jpg",
        "https://i.ibb.co/8Ds4T1Mw/Aerytiefling-Nami-05.jpg",
        "https://i.ibb.co/YByfmBhT/Aerytiefling-Nami-06.jpg",
        "https://i.ibb.co/1k70N74/Aerytiefling-Nami-07.jpg",
        "https://i.ibb.co/S4YWmJVF/Aerytiefling-Nami-08.jpg",
        "https://i.ibb.co/k6h4L4gm/Aerytiefling-Nami-09.jpg",
        "https://i.ibb.co/rK3jFWp0/Aerytiefling-Nami-10.jpg",
        "https://i.ibb.co/nN1tvQw5/Aerytiefling-Nami-11.jpg",
        "https://i.ibb.co/gb5zVWBK/Aerytiefling-Nami-12.jpg",
        "https://i.ibb.co/fzjYQJQy/Aerytiefling-Nami-13.jpg",
        "https://i.ibb.co/0vdRyzn/Aerytiefling-Nami-14.jpg",
        "https://i.ibb.co/JWgw2HgF/Aerytiefling-Nami-15.jpg",
        "https://i.ibb.co/dw562ks2/Aerytiefling-Nami-16.jpg",
        "https://i.ibb.co/yFm2QByN/Aerytiefling-Nami-17.jpg",
        "https://i.ibb.co/20hxFcPf/Aerytiefling-Nami-18.jpg",
        "https://i.ibb.co/Gfjdkq1c/Aerytiefling-Nami-19.jpg",
        "https://i.ibb.co/NnyddDmG/Aerytiefling-Nami-20.jpg",
        "https://i.ibb.co/MDfKKqdw/Aerytiefling-Nami-21.jpg",
        "https://i.ibb.co/mV9PFWbC/Aerytiefling-Nami-22.jpg",
        "https://i.ibb.co/C3XyrcZ3/Aerytiefling-Nami-23.jpg",
        "https://i.ibb.co/21BCvzpL/Aerytiefling-Nami-24.jpg",
        "https://i.ibb.co/WmRD8tP/Aerytiefling-Nami-25.jpg",
        "https://i.ibb.co/Gvn9xNC5/Aerytiefling-Nami-26.jpg",
        "https://i.ibb.co/1tSsFnNf/Aerytiefling-Nami-27.jpg",
        "https://i.ibb.co/3mB9vYb6/Aerytiefling-Nami-28.jpg",
        "https://i.ibb.co/932ydSFn/Aerytiefling-Nami-29.jpg",
        "https://i.ibb.co/dJsC4Pqm/Aerytiefling-Nami-30.jpg",
        "https://i.ibb.co/4nGvvZ52/Aerytiefling-Nami-31.jpg",
        "https://i.ibb.co/mCXDhtvb/Aerytiefling-Nami-33.jpg",
        "https://i.ibb.co/HLZLcSTN/Aerytiefling-Nami-34.jpg"
    ]
};
