const comicData = {
    "IDcode": 41950,
    "title": "Kiki Rose - Lady Dimitrescu Lingerie (Resident Evil)",
    "sourceUrl": "https://telegra.ph/Galería-de-imágenes-09-11-6",
    "images": [
        "https://i.ibb.co/ZzSvVzR7/01-Lady-Dimitrescu-Lingerie-1.jpg",
        "https://i.ibb.co/5gf52yZT/02-Lady-Dimitrescu-Lingerie-2.jpg",
        "https://i.ibb.co/HQCWDf2/03-Lady-Dimitrescu-Lingerie-3.jpg",
        "https://i.ibb.co/b53nV5c7/04-Lady-Dimitrescu-Lingerie-4.jpg",
        "https://i.ibb.co/TBFP1z8R/05-Lady-Dimitrescu-Lingerie-5.jpg",
        "https://i.ibb.co/0RZq760W/06-Lady-Dimitrescu-Lingerie-6.jpg",
        "https://i.ibb.co/S4t4LnZ7/07-Lady-Dimitrescu-Lingerie-7.jpg",
        "https://i.ibb.co/3qPb3W4/08-Lady-Dimitrescu-Lingerie-8.jpg",
        "https://i.ibb.co/hxQW4fGr/09-Lady-Dimitrescu-Lingerie-9.jpg",
        "https://i.ibb.co/0VhnPBgb/10-Lady-Dimitrescu-Lingerie-10.jpg",
        "https://i.ibb.co/C5KLz9mj/11-Lady-Dimitrescu-Lingerie-11.jpg",
        "https://i.ibb.co/FbQVSLvy/12-Lady-Dimitrescu-Lingerie-12.jpg",
        "https://i.ibb.co/S2dqP4Z/13-Lady-Dimitrescu-Lingerie-13.jpg",
        "https://i.ibb.co/8DHnDXzw/14-Lady-Dimitrescu-Lingerie-14.jpg",
        "https://i.ibb.co/DHmZ2n90/15-Lady-Dimitrescu-Lingerie-15.jpg",
        "https://i.ibb.co/Y4y6P2VC/16-Lady-Dimitrescu-Lingerie-16.jpg",
        "https://i.ibb.co/q3VDL5Hf/17-Lady-Dimitrescu-Lingerie-17.jpg",
        "https://i.ibb.co/5gphCfDB/18-Lady-Dimitrescu-Lingerie-18.jpg",
        "https://i.ibb.co/bSR8GM1/19-Lady-Dimitrescu-Lingerie-19.jpg",
        "https://i.ibb.co/nqNTjGW6/20-Lady-Dimitrescu-Lingerie-20.jpg",
        "https://i.ibb.co/Myb6zRPD/21-Lady-Dimitrescu-Lingerie-21.jpg",
        "https://i.ibb.co/5gYw3xyc/22-Lady-Dimitrescu-Lingerie-22.jpg",
        "https://i.ibb.co/1YLvhdhy/23-Lady-Dimitrescu-Lingerie-23.jpg",
        "https://i.ibb.co/MypMPt9F/24-Lady-Dimitrescu-Lingerie-24.jpg",
        "https://i.ibb.co/mV2WHB4J/25-Lady-Dimitrescu-Lingerie-25.jpg",
        "https://i.ibb.co/TB8fQfYN/26-Lady-Dimitrescu-Lingerie-26.jpg",
        "https://i.ibb.co/1txWm8dh/27-Lady-Dimitrescu-Lingerie-27.jpg",
        "https://i.ibb.co/N6DSd4wy/28-Lady-Dimitrescu-Lingerie-28.jpg",
        "https://i.ibb.co/QFJrKZkH/29-Lady-Dimitrescu-Lingerie-29.jpg",
        "https://i.ibb.co/xqY9ZMpB/30-Lady-Dimitrescu-Lingerie-30.jpg",
        "https://i.ibb.co/1fXmgzQS/31-Lady-Dimitrescu-Lingerie-31.jpg",
        "https://i.ibb.co/6cQFTT9N/32-Lady-Dimitrescu-Lingerie-32.jpg",
        "https://i.ibb.co/kvCc0Tj/33-Lady-Dimitrescu-Lingerie-33.jpg",
        "https://i.ibb.co/N65F3jnr/34-Lady-Dimitrescu-Lingerie-34.jpg",
        "https://i.ibb.co/Sw7886rv/35-Lady-Dimitrescu-Lingerie-35.jpg"
    ]
};
