const comicData = {
    "IDcode": 42191,
    "title": "Atelier Roro - Cynthia (Pokemon)",
    "sourceUrl": "https://telegra.ph/Galería-de-imágenes-11-11-6",
    "images": [
        "https://i.ibb.co/XZdCFqXw/01-Shirona-Cynthia-01-compress85.jpg",
        "https://i.ibb.co/dwJR35xS/02-Shirona-Cynthia-48-compress18.jpg",
        "https://i.ibb.co/1GSRnkhP/03-Shirona-Cynthia-02-compress72.jpg",
        "https://i.ibb.co/Jj129hyM/04-Shirona-Cynthia-03-compress11.jpg",
        "https://i.ibb.co/7x41PkT5/05-Shirona-Cynthia-04-compress61.jpg",
        "https://i.ibb.co/QvzzpxHm/06-Shirona-Cynthia-05-compress11.jpg",
        "https://i.ibb.co/gFFpVvB8/07-Shirona-Cynthia-06-compress64.jpg",
        "https://i.ibb.co/ccbr03bg/08-Shirona-Cynthia-07-compress17.jpg",
        "https://i.ibb.co/wNjqcwgg/09-Shirona-Cynthia-08-compress79.jpg",
        "https://i.ibb.co/Fbrh4Tjz/10-Shirona-Cynthia-09-compress19.jpg",
        "https://i.ibb.co/m5cwg3jY/11-Shirona-Cynthia-10-compress64.jpg",
        "https://i.ibb.co/B5s8YN1M/12-Shirona-Cynthia-11-compress17.jpg",
        "https://i.ibb.co/G4ZT7MFF/13-Shirona-Cynthia-12-compress67.jpg",
        "https://i.ibb.co/qM1ftWCr/14-Shirona-Cynthia-13-compress21.jpg",
        "https://i.ibb.co/Df45mD5v/15-Shirona-Cynthia-14-compress78.jpg",
        "https://i.ibb.co/rGT94sRh/16-Shirona-Cynthia-15-compress33.jpg",
        "https://i.ibb.co/Kc3Nw5cQ/17-Shirona-Cynthia-16-compress92.jpg",
        "https://i.ibb.co/QFfskCT9/18-Shirona-Cynthia-17-compress39.jpg",
        "https://i.ibb.co/yndpZFz7/19-Shirona-Cynthia-18-compress8.jpg",
        "https://i.ibb.co/Zp6VsJ5T/20-Shirona-Cynthia-19-compress57.jpg",
        "https://i.ibb.co/JRRBcK70/21-Shirona-Cynthia-20-compress12.jpg",
        "https://i.ibb.co/Qv3yCtm2/22-Shirona-Cynthia-21-compress87.jpg",
        "https://i.ibb.co/n8D6Wq1R/23-Shirona-Cynthia-22-compress46.jpg",
        "https://i.ibb.co/zhhKZ0Dp/24-Shirona-Cynthia-23-compress12.jpg",
        "https://i.ibb.co/1t8wq3NX/25-Shirona-Cynthia-24-compress55.jpg",
        "https://i.ibb.co/dJMSbDpT/26-Shirona-Cynthia-25-compress2.jpg",
        "https://i.ibb.co/21kHp6Z3/27-Shirona-Cynthia-26-compress48.jpg",
        "https://i.ibb.co/8n5Cwrvf/28-Shirona-Cynthia-27-compress8.jpg",
        "https://i.ibb.co/XZSdbTtq/29-Shirona-Cynthia-28-compress80.jpg",
        "https://i.ibb.co/PvsYggYK/30-Shirona-Cynthia-29-compress47.jpg",
        "https://i.ibb.co/0RcPzHDq/31-Shirona-Cynthia-30-compress99.jpg",
        "https://i.ibb.co/5gzQXqSm/32-Shirona-Cynthia-31-compress47.jpg",
        "https://i.ibb.co/cXKJdC3w/33-Shirona-Cynthia-32-compress2.jpg",
        "https://i.ibb.co/TDmFQZcd/34-Shirona-Cynthia-33-compress70.jpg",
        "https://i.ibb.co/cXK0rDZn/35-Shirona-Cynthia-34-compress29.jpg",
        "https://i.ibb.co/zCKzkch/36-Shirona-Cynthia-35-compress95.jpg",
        "https://i.ibb.co/gMchv8c4/37-Shirona-Cynthia-36-compress6.jpg",
        "https://i.ibb.co/Kj5N5w7G/38-Shirona-Cynthia-37-compress54.jpg",
        "https://i.ibb.co/RTyySmPy/39-Shirona-Cynthia-38-compress22.jpg",
        "https://i.ibb.co/HTXFT5QD/40-Shirona-Cynthia-39-compress53.jpg",
        "https://i.ibb.co/4n9z8f1n/41-Shirona-Cynthia-40-compress74.jpg",
        "https://i.ibb.co/nq1stNhw/42-Shirona-Cynthia-41-compress12.jpg",
        "https://i.ibb.co/bM3kTb1t/43-Shirona-Cynthia-42-compress54.jpg",
        "https://i.ibb.co/7dVX2fBz/44-Shirona-Cynthia-43-compress92.jpg",
        "https://i.ibb.co/RTbjPkDb/45-Shirona-Cynthia-44-compress60.jpg",
        "https://i.ibb.co/svn44hY4/46-Shirona-Cynthia-45-compress95.jpg",
        "https://i.ibb.co/DDbKH10f/47-Shirona-Cynthia-46-compress53.jpg",
        "https://i.ibb.co/0RpNXtZk/48-Shirona-Cynthia-47-compress94.jpg"
    ]
};
