window.PAGE_DATA = [
  {
    "id": 561991,
    "IDcode": "DOKS-591",
    "title": "絶伦アナルオナニーモンスター どの穴よりもアナルが一番感じるドM変态女",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240203/kxAs6iNe/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-591"
  },
  {
    "id": 546966,
    "IDcode": "DOKS-592",
    "title": "【水责め快楽#窒息溺れイキ】闷絶潮バシャバシャ源泉かけ流し 苦しくて濡れるドMマ●コ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240104/ikrskU0g/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-592"
  },
  {
    "id": 546970,
    "IDcode": "DOKS-593",
    "title": "私の污い体液买ってくれませんか？お金のためなら経血にオシッコ、ゲロでもなんでも出す女の子。気が",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240104/cHSmnUpH/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-593"
  },
  {
    "id": 518736,
    "IDcode": "DOKS-594",
    "title": "直饮专业梦想体液食堂 - 加贺美沙罗",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240403/Z6TYgL8S/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-594"
  },
  {
    "id": 561993,
    "IDcode": "DOKS-595",
    "title": "ドSがゲロイラマに目覚めて连続大量呕吐！吐泻物涂りたくってゲロ手コキにゲロパイズリと男の性癖好",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240203/8YKX30f8/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-595"
  },
  {
    "id": 546189,
    "IDcode": "DOKS-596",
    "title": "女子校生のザーメンぶっかけられオナニー",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240307/FeBy4hlz/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-596"
  },
  {
    "id": 546218,
    "IDcode": "DOKS-597",
    "title": "美脚OL 仕事帰りの変态パンスト倶楽部 美人経理部 玲衣さん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240304/Hf9YTtfL/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-597"
  },
  {
    "id": 545821,
    "IDcode": "DOKS-598",
    "title": "パンチラ诱惑してくる変态女にセンズリ见せつけ返し",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240411/kCq19zsb/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-598"
  },
  {
    "id": 545561,
    "IDcode": "DOKS-599",
    "title": "お姊さんの蒸れた足里コッキング游戏",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240507/pKbZikVx/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-599"
  },
  {
    "id": 545581,
    "IDcode": "DOKS-600",
    "title": "清楚妻のくせに浣肠喷射しながらマ●コSEX",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240503/sgwxyzD3/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-600"
  },
  {
    "id": 15088,
    "IDcode": "DOKS-601",
    "title": "想要讓乳頭被玩弄到死的變態女人櫻茉日，只爲乳頭而瘋狂",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "戀物癖",
      "口交",
      "巨乳",
      "絕頂高潮",
      "兩男一女",
      "淫亂",
      "乳交",
      "中出",
      "女優",
      "企畫",
      "美少女電影",
      "蕩婦",
      "亂交 • 群P",
      "多P",
      "性感",
      "3P・4P",
      "美乳"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2024-05-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240502/bfd9854b-521d-48c0-9e67-90dd30dbb6d2.jpg",
    "actress": [
      "堀北実来"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-601"
  },
  {
    "id": 545564,
    "IDcode": "DOKS-602",
    "title": "尿道がバカになるほどイキ狂いおしっこが止まらないスプラッシュオナニー",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240507/dFMU1427/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-602"
  },
  {
    "id": 545584,
    "IDcode": "DOKS-603",
    "title": "口の中の感触をじっくりと味わう、优しいスロ～フェラチオ 3",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240503/KlTCdRtj/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-603"
  },
  {
    "id": 14223,
    "IDcode": "DOKS-604",
    "title": "想要高潮後被中出 ~ 天乃のあ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "美腳",
      "蘿莉控",
      "女學生",
      "美臀",
      "亂交 • 群P",
      "舔陰",
      "淫亂",
      "中出",
      "貧乳",
      "美少女電影",
      "自宅",
      "美少女",
      "無毛",
      "色白",
      "企畫",
      "苗條",
      "騎乗位",
      "羞恥",
      "口交",
      "潮吹",
      "清純",
      "自慰",
      "女上位",
      "放尿",
      "後入"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2024-06-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240603/ceeed5a8-41ff-4daf-bdc4-3809f7e5648e.jpg",
    "actress": [
      "天乃のあ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-604"
  },
  {
    "id": 14233,
    "IDcode": "DOKS-605",
    "title": "無限潮吹女孩月美りょう",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "美腳",
      "蘿莉控",
      "女學生",
      "美臀",
      "舔陰",
      "淫亂",
      "中出",
      "美少女電影",
      "自宅",
      "美少女",
      "按摩棒",
      "絕頂高潮",
      "無毛",
      "企畫",
      "苗條",
      "騎乗位",
      "羞恥",
      "美乳",
      "口交",
      "巨乳",
      "潮吹",
      "乳交",
      "情趣內衣",
      "自慰",
      "女上位",
      "內衣",
      "放尿",
      "後入",
      "性感",
      "不倫"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2024-06-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240603/6b597c5e-c536-4259-98f0-93da8d3570df.jpg",
    "actress": [
      "月美りょう"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-605"
  },
  {
    "id": 545404,
    "IDcode": "DOKS-606",
    "title": "ガチイキクンニリングス実习",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240607/47rJIlZG/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-606"
  },
  {
    "id": 13502,
    "IDcode": "DOKS-607",
    "title": "肉便器小姐 ~ 生田りん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "性虐癖",
      "美腳",
      "拘束・拷問",
      "口爆",
      "SM",
      "深喉",
      "癡女",
      "重口味",
      "口球",
      "淫亂",
      "中出",
      "美少女電影",
      "殘忍畫面",
      "劇情",
      "調教",
      "美少女",
      "按摩棒",
      "緊縛",
      "苗條",
      "變態",
      "顏射",
      "暗黑系",
      "騎乗位",
      "導尿",
      "羞恥",
      "吞精",
      "口交",
      "潮吹",
      "清純",
      "女上位",
      "白眼失神",
      "唾液敷面"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2024-07-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240707/e1d324b7-0b3b-48ca-b31f-efe367a0ca7b.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-607"
  },
  {
    "id": 13504,
    "IDcode": "DOKS-608",
    "title": "女子學生敏感乳頭健康檢查第二期",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "故事集",
      "口交",
      "巨乳",
      "美少女",
      "中出",
      "企畫",
      "看病・住院",
      "苗條",
      "美少女電影",
      "女學生",
      "JK校服",
      "羞恥",
      "醫院・診所",
      "癡女",
      "美乳"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2024-07-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240707/da6b7be2-b331-45a8-bc16-3a63f238c3af.jpg",
    "actress": [
      "逢月日葵",
      "桐香悠裡",
      "岬櫻",
      "夏白麻矢",
      "天海一華"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-608"
  },
  {
    "id": 13505,
    "IDcode": "DOKS-609",
    "title": "美麗的剛毛制服女孩 ~ 五十嵐美月",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "戀物癖",
      "口交",
      "蠻橫嬌羞",
      "中出",
      "局部特寫",
      "女優",
      "企畫",
      "苗條",
      "清純",
      "美少女電影",
      "鬃毛",
      "手指插入",
      "騎乗位",
      "美少女",
      "癡女"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202509/30/68db0058d6fbef4e90d2670a/cover.jpg",
    "actress": [
      "五十嵐美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-609"
  },
  {
    "id": 560559,
    "IDcode": "DOKS-610",
    "title": "ワキで感じる女たち",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240806/qhnSfJTY/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-610"
  },
  {
    "id": 545095,
    "IDcode": "DOKS-611",
    "title": "ドM美少女レズ调教 伊织ひなの 水责め 打撃调教 野外羞耻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240803/sHpihsZv/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-611"
  },
  {
    "id": 545094,
    "IDcode": "DOKS-612",
    "title": "肛门中毒ド変态アナルファッカー",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240803/AIJQqYnW/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-612"
  },
  {
    "id": 525425,
    "IDcode": "DOKS-613",
    "title": "美尻·巨尻美女の激イキ杭打ちピストンディルドオナニー 4",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240926/0nATeLgo/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-613"
  },
  {
    "id": 525424,
    "IDcode": "DOKS-614",
    "title": "“勃起乳首”と“感じる颜”をじっくりと魅せる乳首だけでイッちゃう8人の女たち 3",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240926/Jief2q4M/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-614"
  },
  {
    "id": 525423,
    "IDcode": "DOKS-615",
    "title": "美脚がすぎるOLの诱惑黒パンティストッキング",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20240926/Bgept6wu/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-615"
  },
  {
    "id": 492963,
    "IDcode": "DOKS-616",
    "title": "爱好摩擦阴蒂的女子洋溢淫臭的丝袜桌角自慰 泉莉音,安堂はるの,香月えりさ等演员",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251110-1/0dc4399acb23d22cb79c2c7cce32da4e.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-616"
  },
  {
    "id": 483386,
    "IDcode": "DOKS-617",
    "title": "白浊液止不住！认真打桩假屌抽插自慰 2 千石もなか,有加里乃乃花,加贺美沙罗等演员",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251110-1/1c515a93423706e3d337e2fd0af45cec.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-617"
  },
  {
    "id": 483644,
    "IDcode": "DOKS-618",
    "title": "后宫天国！！自慰俱乐部1愛瀬ゆうり,如月りいさ,若宫はずき等演员",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20251023-1/0dc6ec59a4cc8c58dbf913779ff91472.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-618"
  },
  {
    "id": 466413,
    "IDcode": "DOKS-619",
    "title": "上班女子的淫蕩內褲遊戲",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/25/68acad3a5f03a092cf745da8/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-619"
  },
  {
    "id": 456906,
    "IDcode": "DOKS-620",
    "title": "爱情汁出来了！女学生活塞假阳具自慰3 冬爱琴音,皆月光,由良かな等演员",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250914-1/c2ddb5ea05c589d4d248c0ef140c5959.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-620"
  },
  {
    "id": 9472,
    "IDcode": "DOKS-621",
    "title": "ハーレムでヘブン状態！！視線が気持ち良すぎるセンズリ見せつけ倶楽部（2）",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "蠻橫嬌羞",
      "蕩婦",
      "兩女一男",
      "癡女",
      "淫語",
      "比基尼",
      "美少女電影",
      "美少女",
      "打手槍",
      "企畫",
      "精選總編集",
      "形象俱樂部",
      "無做愛場面",
      "雙飛",
      "女僕制服",
      "口交",
      "巨乳",
      "情趣內衣",
      "足交",
      "後宮系",
      "COSPLAY服飾"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/30/4fef8e07/vod.jpg",
    "actress": [
      "由良佳奈",
      "绫濑心",
      "宇流木沙羅",
      "千石もなか",
      "真木今日子",
      "朝比ゆの",
      "祈山愛",
      "美泉咲",
      "華澄結愛",
      "杉崎みさき"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-621"
  },
  {
    "id": 9471,
    "IDcode": "DOKS-622",
    "title": "死ぬまでずっと乳首をイジられたい、乳首だけでイキ狂う変態性癖女 桐香ゆうり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "網襪",
      "亂交 • 群P",
      "兩男一女",
      "淫亂",
      "中出",
      "猥褻穿著",
      "美少女電影",
      "按摩棒",
      "戀物癖",
      "絕頂高潮",
      "女優",
      "企畫",
      "手指插入",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "口交",
      "巨乳",
      "潮吹",
      "局部特寫",
      "女優訪談",
      "胸控・戀乳癖",
      "女上位",
      "多P",
      "後入",
      "性感",
      "3P・4P"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/20250101/f1c261ea-b546-41d4-86df-82980eec298b.jpg",
    "actress": [
      "桐香悠裡"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-622"
  },
  {
    "id": 184063,
    "IDcode": "DOKS-623",
    "title": "よつんばいフェラチオ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-623"
  },
  {
    "id": 440210,
    "IDcode": "DOKS-624",
    "title": "极端的乳头折磨 末広纯,一条美绪,兼咲みう等演员",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250916-1/eadf2bfd71e89c16a28415108b3d9964.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-624"
  },
  {
    "id": 8576,
    "IDcode": "DOKS-625",
    "title": "新人OLの乳首を狙った猥褻医師の不適切検診",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "蠻橫嬌羞",
      "大乳暈",
      "美少女電影",
      "劇情",
      "M男・M女",
      "地味",
      "企畫",
      "看病・住院",
      "變態",
      "素人作品",
      "黑絲",
      "精選總編集",
      "制服",
      "羞恥",
      "形象俱樂部",
      "無做愛場面",
      "美乳",
      "美人",
      "口交",
      "巨乳",
      "局部特寫",
      "4K",
      "OL",
      "性感",
      "醫院・診所"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/20250203/9007d42f-cbf2-4f09-b581-fcd31e031356.jpg",
    "actress": [
      "绫濑心",
      "宇流木沙羅",
      "千石もなか",
      "朝比ゆの",
      "華澄結愛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-625"
  },
  {
    "id": 8577,
    "IDcode": "DOKS-626",
    "title": "幸福的美人口爆，不知不覺得就射了 ~ 桜木美音 有棲舞衣 円井萌華 加賀美さら",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "肉絲",
      "蠻橫嬌羞",
      "美腳",
      "蕩婦",
      "口爆",
      "癡女",
      "舔腳",
      "美少女電影",
      "辦公室",
      "戀物癖",
      "女優",
      "企畫",
      "飯店",
      "苗條",
      "素人作品",
      "黑絲",
      "精選總編集",
      "制服",
      "形象俱樂部",
      "無做愛場面",
      "美人",
      "脚控・戀足癖",
      "美腿",
      "口交",
      "巨乳",
      "4K",
      "足交",
      "OL",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2025-02-01",
    "cover_url": "https://picture.yoshiclub.xyz/20250203/248b02db-2e19-4dd4-8519-2dac639f109b.jpg",
    "actress": [
      "有栖舞衣",
      "美澄玲衣",
      "円井萌華",
      "桜木美音",
      "加賀美さら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-626"
  },
  {
    "id": 7809,
    "IDcode": "DOKS-627",
    "title": "乳首玩弄融入日常的世界 女學生渾然不覺被弄到乳首高潮的敏感乳首學園日常 ~ 乙羽あむ 雅子里菜 柏木小夏 藤田梢 宇流木沙羅",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "清楚系",
      "蘿莉控",
      "女學生",
      "小隻馬",
      "奇異的",
      "奇聞趣事",
      "美少女電影",
      "校園生活",
      "劇情",
      "美少女",
      "戀物癖",
      "絕頂高潮",
      "性騷擾",
      "學校",
      "羞恥",
      "形象俱樂部",
      "美乳",
      "校花",
      "慾求不滿",
      "猥亵",
      "清純",
      "胸控・戀乳癖",
      "JK校服"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202510/03/68dedc3cdbf24d4ed317dd3d/cover.jpg",
    "actress": [
      "柏木小夏",
      "宇流木沙羅",
      "雅子裡菜",
      "藤田梢",
      "乙羽あむ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-627"
  },
  {
    "id": 457224,
    "IDcode": "DOKS-628",
    "title": "ヤリマンAV女優の自宅に童貞クン達を送り込んでみたら…",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250826-1/55ab60825ea9e2630468fa3d476eaa56.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-628"
  },
  {
    "id": 7806,
    "IDcode": "DOKS-629",
    "title": "天然剛毛失禁JK少女 ~ 花音うらら",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "清楚系",
      "女學生",
      "美臀",
      "癡女",
      "中出",
      "美少女電影",
      "鬃毛",
      "按摩・美容店",
      "美少女",
      "戀物癖",
      "絕頂高潮",
      "學校",
      "色白",
      "企畫",
      "飯店",
      "黑絲",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "短髮",
      "美乳",
      "故事集",
      "口交",
      "巨乳",
      "校花",
      "慾求不滿",
      "局部特寫",
      "女上位",
      "放尿",
      "後入",
      "JK校服",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/19/68a4b4315f03a092cf66ecae/cover.jpg",
    "actress": [
      "花音うらら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-629"
  },
  {
    "id": 412379,
    "IDcode": "DOKS-630",
    "title": "美脚OL仕事帰りの変態パンスト倶楽部美人営業部杏さん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250826-1/7380e26f1f0fea281512f0cf91db749f.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-630"
  },
  {
    "id": 7642,
    "IDcode": "DOKS-631",
    "title": "美尻早漏顏面騎乘2 ~ 桐香悠里 和久井美兎 祈山愛 百永紗里奈 千鶴えま",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "巨尻",
      "精選綜合",
      "淫亂",
      "局部特寫",
      "女優",
      "美人",
      "企畫",
      "美人妻",
      "胸控・戀乳癖",
      "放尿",
      "蕩婦",
      "精選總編集",
      "形象俱樂部",
      "無做愛場面",
      "顔面騎乘",
      "淫語"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2025-03-01",
    "cover_url": "https://picture.yoshiclub.xyz/20250310/b1d7cadb-fe05-4276-a253-81afa5f850c9.jpg",
    "actress": [
      "百永纱里奈",
      "和久井美兎",
      "桐香悠裡",
      "千鶴えま",
      "祈山愛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-631"
  },
  {
    "id": 69709,
    "IDcode": "DOKS-632",
    "title": "密着添い寝手コキ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "巨乳",
      "恋物癖",
      "乳房",
      "手淫"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "皆月光",
      "椎叶みくる",
      "弥生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-632"
  },
  {
    "id": 69693,
    "IDcode": "DOKS-634",
    "title": "口の中の感触をじっくりと味わう、優しいスロ～フェラチオ 4",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "口交",
      "恋物癖",
      "内衣",
      "淫语"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "宇流木沙羅",
      "雅子裡菜",
      "橘日向",
      "藤田梢",
      "乙羽あむ",
      "朝比ゆの"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-634"
  },
  {
    "id": 6522,
    "IDcode": "DOKS-635",
    "title": "パイフレに見つめられながら密着乳揉みしだき",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精選綜合",
      "主觀視角",
      "口爆",
      "癡女",
      "淫語",
      "美少女電影",
      "美少女",
      "後入",
      "企畫",
      "素人作品",
      "騎乗位",
      "形象俱樂部",
      "美人",
      "美乳",
      "故事集",
      "巨乳",
      "乳交",
      "4K",
      "女上位",
      "抹油",
      "濕身"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250501/20250501053851323323_thumbnail.webp",
    "actress": [
      "绫濑心",
      "尾崎惠梨香",
      "若宮穂乃",
      "小梅惠奈",
      "月見若葉",
      "祈山愛",
      "皐月ゆら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-635"
  },
  {
    "id": 69692,
    "IDcode": "DOKS-636",
    "title": "美人OLの匂い立つ黒パンスト脚コキ（2） 皆月ひかるさんのパンティと生写真付き",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "恋物癖",
      "连裤袜",
      "足交",
      "淫语"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "皆月光",
      "椎叶みくる",
      "弥生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-636"
  },
  {
    "id": 67519,
    "IDcode": "DOKS-637",
    "title": "プリ尻J系の激イキ杭打ちピストンディルドオナニー",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "屁股",
      "自慰",
      "高中女生",
      "淫语",
      "局部特写"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250709-1/bba679dee213e46aa760cd46c65564c8.jpg",
    "actress": [
      "绫濑心",
      "若宮穂乃",
      "小梅惠奈",
      "月見若葉",
      "皐月ゆら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-637"
  },
  {
    "id": 6521,
    "IDcode": "DOKS-638",
    "title": "オナサポ商事 働く女の密着囁きストリップ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "清楚系",
      "精選綜合",
      "主觀視角",
      "美腳",
      "小隻馬",
      "口爆",
      "深喉",
      "癡女",
      "淫語",
      "中出",
      "拜金女",
      "劇情",
      "絕頂高潮",
      "高顏值",
      "苗條",
      "企畫",
      "顏射",
      "黑絲",
      "應召・援交",
      "騎乗位",
      "制服",
      "形象俱樂部",
      "美人",
      "故事集",
      "口交",
      "飯店小姐・援交妹",
      "巨乳",
      "風俗娘",
      "乳交",
      "4K",
      "自慰",
      "女上位",
      "OL",
      "後入"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250501/202505010538466161_thumbnail.webp",
    "actress": [
      "前田美波",
      "倉木詩織",
      "天晴乃愛",
      "市川りく",
      "廣瀬好美",
      "仓木诗织"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-638"
  },
  {
    "id": 438475,
    "IDcode": "DOKS-639",
    "title": "神级深喉绝技！最佳角度慢镜头特写，让你一吹就射的极致口交体验",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250616-1/dd88975ac705fce7a8d15c6236b83a0f.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-639"
  },
  {
    "id": 4666,
    "IDcode": "DOKS-640",
    "title": "慢慢品味嘴裏的極致快感 溫柔慢節奏口暴大合集",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "豐滿",
      "精選綜合",
      "自拍性愛",
      "高妹",
      "姐姐・妹妹",
      "口爆",
      "美臀",
      "癡女",
      "淫語",
      "舔陰",
      "奇聞趣事",
      "極品美人",
      "大姐姐",
      "自宅",
      "美少女",
      "明星臉",
      "女友・妻子",
      "色白",
      "高顏值",
      "企畫",
      "顏射",
      "游戲COSPLAY",
      "手指插入",
      "形象俱樂部",
      "無做愛場面",
      "美人",
      "美乳",
      "美腿",
      "素人",
      "吞精",
      "巨尻",
      "巨乳",
      "口交",
      "放尿",
      "4小時以上作品",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2025-07-01",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250706/20250706100310785785_86905_thumbnail.webp",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-640"
  },
  {
    "id": 4636,
    "IDcode": "DOKS-641",
    "title": "辦公室裡偷偷喘氣，慾求不滿OL的絲襪角自慰 ~ 末広純 福田もも 美泉咲 和久井美兎 幾田真知",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "肉絲",
      "清楚系",
      "少女",
      "美腳",
      "高妹",
      "美臀",
      "人妻",
      "眼鏡",
      "職場",
      "極品美人",
      "貧乳",
      "美少女電影",
      "辦公室",
      "劇情",
      "美少女",
      "高顏值",
      "黑絲",
      "制服",
      "形象俱樂部",
      "無做愛場面",
      "美人",
      "美乳",
      "美腿",
      "故事集",
      "脚控・戀足癖",
      "巨尻",
      "巨乳",
      "慾求不滿",
      "局部特寫",
      "4K",
      "清純",
      "自慰",
      "OL",
      "熟女",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2025-07-01",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250707/20250707033017383383_42750_thumbnail.webp",
    "actress": [
      "末広純",
      "和久井美兎",
      "幾田真知",
      "美泉咲",
      "福田もも"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-641"
  },
  {
    "id": 4631,
    "IDcode": "DOKS-642",
    "title": "龜頭玩弄快感爆射的極致口技 ~ 戶川奈美 白河花清 大橋裏緒 花裏明理 岬櫻 及川海",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "清楚系",
      "精選綜合",
      "美腳",
      "高妹",
      "口爆",
      "野性",
      "深喉",
      "人妻",
      "舔陰",
      "貧乳",
      "美少女",
      "企畫",
      "苗條",
      "顏射",
      "角色扮演",
      "精選總編集",
      "形象俱樂部",
      "無做愛場面",
      "美人",
      "唾液敷面",
      "美乳",
      "吞精",
      "巨尻",
      "巨乳",
      "口交",
      "4K",
      "清純",
      "4小時以上作品",
      "OL",
      "熟女",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "2025-07-01",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250707/20250707033027204204_98522_thumbnail.webp",
    "actress": [
      "花里明理",
      "岬櫻",
      "戶川奈美",
      "及川海",
      "白河花清",
      "大橋里緒"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-642"
  },
  {
    "id": 540662,
    "IDcode": "DOKS-643",
    "title": "“勃起乳首”と“感じる颜”をじっくりと魅せる乳首だけでイッちゃう7人の女たち 4",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://tuaskbgnekr.com/20250726/N9P9g8V4/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-643"
  },
  {
    "id": 61119,
    "IDcode": "DOKS-644",
    "title": "美尻・巨尻美女の激イキ杭打ちピストンディルドオナニー 5",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "荡妇",
      "恋物癖",
      "屁股",
      "巨大屁股",
      "4K",
      "自慰",
      "素人作品",
      "姐姐",
      "淫语",
      "局部特写"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/08/6895cf8c55337d7f7ba4262d/cover.jpg",
    "actress": [
      "永野鈴",
      "花音うらら",
      "菜月光",
      "雨宮あや花",
      "白石環奈",
      "弥生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-644"
  },
  {
    "id": 3843,
    "IDcode": "DOKS-645",
    "title": "超赤面 おま〇こ丸出しまんぐりアクメ 「恥ずかしいけど何度もイッちゃう…」",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "少女",
      "清楚系",
      "美腳",
      "二次元",
      "人妻",
      "舔陰",
      "大姐姐",
      "美少女",
      "淫蕩・硬核",
      "企畫",
      "手指插入",
      "騎乗位",
      "超爆乳",
      "羞恥",
      "美人",
      "形象俱樂部",
      "故事集",
      "巨尻",
      "巨乳",
      "口交",
      "4K",
      "清純",
      "女上位",
      "胸控・戀乳癖",
      "熟女",
      "後入",
      "性感"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202508/08/6895cf5655337d7f7ba3e40f/cover.jpg",
    "actress": [
      "彌生美月",
      "有岡みう",
      "逢月日葵",
      "大浦真奈美",
      "野上しおり",
      "椎叶みくる",
      "弥生美月"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-645"
  },
  {
    "id": 3051,
    "IDcode": "DOKS-646",
    "title": "至極の乳首責め2-天馬ゆい 花衣つばき 雪代美鳳 藤浦安里 湊波流 五十嵐清華",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "清楚系",
      "美腳",
      "小隻馬",
      "癡女",
      "極品美人",
      "大姐姐",
      "美少女電影",
      "港區女子",
      "色白",
      "苗條",
      "高顏值",
      "企畫",
      "形象俱樂部",
      "美人",
      "無做愛場面",
      "風俗娘",
      "4K",
      "清純",
      "JK校服"
    ],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202509/24/68d3098779f1ac4ec4700182/cover.jpg",
    "actress": [
      "天馬唯",
      "五十嵐清華",
      "花衣つばき",
      "雪代一鳳",
      "湊波流"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-646"
  },
  {
    "id": 181534,
    "IDcode": "DOKS-647",
    "title": "感覚遮断絶頂",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-647"
  },
  {
    "id": 178268,
    "IDcode": "DOKS-648",
    "title": "へこへこ腰が止まらない ピンピンこりっこり勃起乳首オナニー",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202510/15/68ef1fbc52c12b4e684bb164/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-648"
  },
  {
    "id": 178278,
    "IDcode": "DOKS-649",
    "title": "愛液出まくり！女子〇生のイキ過ぎピストンディルドオナニー 4",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-649"
  },
  {
    "id": 173580,
    "IDcode": "DOKS-650",
    "title": "乳首いじりが日常に溶け込んだ世界でイジられていることには気づかないまま皆の前で乳首絶頂してしまう敏感女たち",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-650"
  },
  {
    "id": 173578,
    "IDcode": "DOKS-651",
    "title": "完全撮りおろし ムチムチ肉感ディルドオナニー2",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-651"
  },
  {
    "id": 173606,
    "IDcode": "DOKS-652",
    "title": "チ〇ポがトロけちゃうくらいに気持ちイィィーー!!!!!挟み撃ち 下品Wフェラチオ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "OFFICE K’S",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS-652"
  },
  {
    "id": 574421,
    "IDcode": "DOKS186",
    "title": "安田美纪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS186"
  },
  {
    "id": 530751,
    "IDcode": "DOKS624",
    "title": "【多人激战】末広纯、一条美绪、兼咲みう敏感点极限调教 乳头折磨高潮不断",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://fan.lefhao20250923.top/20250921/DbLYkKsJ/1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS624"
  },
  {
    "id": 530626,
    "IDcode": "DOKS628",
    "title": "饥渴荡妇女优私宅性事！多位处男轮流上门服务…",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS628"
  },
  {
    "id": 521123,
    "IDcode": "DOKS630",
    "title": "番号营业部美人OL杏小姐下班后饥渴难耐！美腿丝袜淫乱俱乐部任君玩弄",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS630"
  },
  {
    "id": 517433,
    "IDcode": "DOKS639",
    "title": "神级深喉绝技！最佳角度慢镜头特写，",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202507/26/688428d1c92318f97dd96f02/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKS639"
  },
  {
    "id": 522154,
    "IDcode": "DOKSCD1",
    "title": "DOKScd1 厳选 パンティストッキングマニア 美脚ばかりの脚コキスペシャル",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20230227-1/39224a4f688e6500a9c99a5f7470a347.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKSCD1"
  },
  {
    "id": 522155,
    "IDcode": "DOKSCD2",
    "title": "DOKScd2 厳选 パンティストッキングマニア 美脚ばかりの脚コキスペシャル",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20230227-1/fcb3ea695f4d968c8bc5766f3966ac08.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOKSCD2"
  },
  {
    "id": 525187,
    "IDcode": "DOM",
    "title": "Footjob in Black",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOM"
  },
  {
    "id": 66676,
    "IDcode": "DOM-040",
    "title": "想做多少就做多少-綾瀬れん",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "凌辱",
      "单体作品",
      "颜射"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://sbzytpimg1.com:3519/upload/vod/20250422-1/082724ad1513a07f9cce53c6eb5066d4.jpg",
    "actress": [
      "大冢れん"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOM-040"
  },
  {
    "id": 518263,
    "IDcode": "DOM-040-C",
    "title": "福咲れんの誘惑授業 ～優等生",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://voddadaizi.com:52866/videos/202507/13/6872af0c3ed39b57c0e7e1ca/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOM-040-C"
  },
  {
    "id": 96322,
    "IDcode": "DOM-045",
    "title": "巨乳放題-彩美旬果",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "单体作品",
      "巨乳",
      "无码破解",
      "乳房",
      "女优按摩棒",
      "颜射"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "彩美旬果"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOM-045"
  },
  {
    "id": 595034,
    "IDcode": "DOMD-001",
    "title": "离过一次婚并且缺乏女人的我NTR的机会到来～没什么邂逅的人妻用眼前的老二安慰郁闷小穴 用着外遇肉棒高潮不断，真的只是想做爱的好色人妻。",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "淫妻"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20191121-1/5c301291c65ff290c3cb1ec0073037d9.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-001"
  },
  {
    "id": 593306,
    "IDcode": "DOMD-003",
    "title": "CN “そんなとこにオクチつけちゃ污いよぉ…”クンニの意味すら知らない黒髪少女のションベン臭い未熟マ●コを无理クリ舐め啜ってやると数秒后には完堕ちし自らパックリ股を开いて中年チ●ポをオネダリする パンティと生写真付き",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20200211-1/368a9b406accbc15d7faf1a036c048cd.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-003"
  },
  {
    "id": 523799,
    "IDcode": "DOMD-004",
    "title": "“デカい女が好きなんでしょ”美人でエロくて高身长…",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20191214-1/d17b32eadea4bf844f91174de2f09e3f.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-004"
  },
  {
    "id": 164498,
    "IDcode": "DOMD-006",
    "title": "「揉んでくれるだけでもいいから…」清楚ヅラし",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://ll.lasha250923.top/upload/vod/20191121-1/a6a748dc64a13400b7b18de672bb53f5.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-006"
  },
  {
    "id": 98458,
    "IDcode": "DOMD-007",
    "title": "「実は私、脅迫されてて…",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "口交",
      "中文字幕",
      "素人作品",
      "调教",
      "手指插入",
      "秘书"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "原千尋",
      "江波りゅう（RYU)",
      "香澄果穗",
      "本田莉子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-007"
  },
  {
    "id": 98452,
    "IDcode": "DOMD-008",
    "title": "「私なんてポチャだし…」",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "精选，综合",
      "口交",
      "巨乳",
      "恋乳癖",
      "中文字幕",
      "素人作品",
      "胖女人"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "七草千歲",
      "尾上若叶",
      "永瀬里美",
      "小西美香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOMD-008"
  },
  {
    "id": 540009,
    "IDcode": "DONN-007",
    "title": "クレイジープッシーハイパーアクメ～丸见え拘束强●絶顶拷问～",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240522/donn007sopl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DONN-007"
  },
  {
    "id": 540008,
    "IDcode": "DONN-008",
    "title": "ブッ飞びVOLTAGE女体电気クラゲ～拘束闷絶絶叫限界絶顶～",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240522/donn008sopl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DONN-008"
  },
  {
    "id": 539985,
    "IDcode": "DONN-010",
    "title": "大开脚拘束イキ狂う女体～汗だく痉挛プッシーORGA～",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240504/donn010sopl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DONN-010"
  },
  {
    "id": 210867,
    "IDcode": "DOPP-013",
    "title": "美人嫁-北条麻妃 加藤ツバキ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOPP-013"
  },
  {
    "id": 101317,
    "IDcode": "DOPP-014",
    "title": "相互出轨的艳情剧-加藤椿 北条麻妃",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "单体作品",
      "成熟的女人",
      "白天出轨"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "北条麻妃",
      "夏树カオル"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOPP-014"
  },
  {
    "id": 210818,
    "IDcode": "DOPP-021",
    "title": "相互干渉系背徳相姦エロ艶劇",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOPP-021"
  },
  {
    "id": 210868,
    "IDcode": "DOPP-022",
    "title": "美尻母-羽賀そら美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DOPP-022"
  },
  {
    "id": 539916,
    "IDcode": "DORI-035",
    "title": "パコ撮りNo.35 生エッチを受け入れてくれた清楚お嬢様风なJ●の刚毛マ●コのギャップに兴奋して同时イキ中出し！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240321/h_491dori035pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-035"
  },
  {
    "id": 87417,
    "IDcode": "DORI-061",
    "title": "パコ撮りNo.61 生チンをギュゥっと締め付けてくる細身白ギャルJ●のマン●に「オジサンの精子、オマン●に出して下さい♪」とお願いさせて、結局3回中出しした！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中出",
      "校服",
      "高中女生",
      "女生",
      "泡泡袜"
    ],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "2022-08-12",
    "cover_url": "https://fm.sl25914.com/upload/vod/20230726-1/16985f43e9f50ddf85375ed7dd1830ba.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-061"
  },
  {
    "id": 539630,
    "IDcode": "DORI-063",
    "title": "パコ撮りNo.63 エロく分厚い唇で勃起させる吹奏楽部J●の生マンに2回中出し！3回目はスカートの上に発射して苦笑された…",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20231105/h_491dori063pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-063"
  },
  {
    "id": 566484,
    "IDcode": "DORI-067",
    "title": "パコ撮り No．67",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/c0346742659c7559295f43510ebf5f0b.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-067"
  },
  {
    "id": 566483,
    "IDcode": "DORI-068",
    "title": "パコ撮り No．68",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/1447740ed6ec34de3cb8e98f167dd3b3.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-068"
  },
  {
    "id": 566482,
    "IDcode": "DORI-069",
    "title": "パコ撮り No．69",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/c5246a6412419dd571da0b0ea2e7a2f7.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-069"
  },
  {
    "id": 566481,
    "IDcode": "DORI-070",
    "title": "パコ撮り No．70",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/f65a08b0e92a52a539f5f46072c30ad8.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-070"
  },
  {
    "id": 566480,
    "IDcode": "DORI-071",
    "title": "パコ撮り No．71",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/d9114efe68b501924a2c5f1bfa55c182.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-071"
  },
  {
    "id": 566479,
    "IDcode": "DORI-072",
    "title": "パコ撮り No．72",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://www.jkuntp.com/upload/vod/20230314-1/66678b002d5a19749b7fad83aefd52e9.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-072"
  },
  {
    "id": 539460,
    "IDcode": "DORI-073",
    "title": "パコ撮りNo.73 “私だけに优しい人が好き◆”と男を翻弄させる小悪魔J●のツルマンに3回中出し！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20230812/h_491dori073pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-073"
  },
  {
    "id": 167344,
    "IDcode": "DORI-076",
    "title": "我还在射精",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-076"
  },
  {
    "id": 522609,
    "IDcode": "DORI-076-C",
    "title": "娇小敏感体女高生被开发日记 佐久良咲希高潮教学",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-076-C"
  },
  {
    "id": 69534,
    "IDcode": "DORI-078",
    "title": "与她的赤裸裸的插入",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "口交",
      "中出",
      "校服",
      "高中女生",
      "女生"
    ],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "https://yunvgong.com/cover.jpg",
    "actress": [
      "今井夏帆"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-078"
  },
  {
    "id": 534850,
    "IDcode": "DORI-080",
    "title": "パコ撮りNo.80 イク时にマン●でチン●をめっちゃ缔め付けて来る爆乳J●に“このチンチ●めっちゃ良い♪”と言わせて3回中出",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20231027/h_491dori080pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-080"
  },
  {
    "id": 535379,
    "IDcode": "DORI-085",
    "title": "パコ撮りNo.85 “乳首…凄く硬くなってる◆”Gカップで巨乳なJ●に“ナマでヤリたい♪”と言われて2回も中出しした！",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "巨乳"
    ],
    "type": "有码",
    "company": "FIRST STAR",
    "publish_date": "",
    "cover_url": "http://15.155250922.com/upload/vod/20240611/h_491dori085pl.jpg!320x216.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=DORI-085"
  }
];