window.PAGE_DATA = [
  {
    "id": 9835,
    "IDcode": "MVG-114",
    "title": "巨乳シ○ブ漬け緊縛肉奴● 田中ねね",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "手指插入",
      "SM",
      "人妻",
      "女上位",
      "拘束・拷問",
      "熟女",
      "乳釘、穿孔、乳環",
      "淫亂",
      "豐滿",
      "乳交",
      "按摩棒",
      "中出",
      "慾求不滿",
      "調教",
      "短髮",
      "巨尻",
      "白眼失神",
      "顏射",
      "絕頂高潮",
      "潮吹",
      "胸控・戀乳癖",
      "女奴",
      "性感",
      "無毛",
      "巨乳",
      "跳蛋",
      "企畫",
      "羞恥",
      "後入",
      "口爆",
      "緊縛",
      "辣妹/GAL系",
      "女優",
      "口交",
      "凌辱",
      "深喉",
      "騎乗位"
    ],
    "type": "有码",
    "company": "GLORY QUEST",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/03/fdcc6151/vod.jpg",
    "actress": [
      "田中寧寧"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVG-114"
  },
  {
    "id": 5085,
    "IDcode": "MVG-133",
    "title": "超級抖M淫話女神 ~ 三岳祐奈",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "大奶头",
      "美乳",
      "手指插入",
      "肌肉",
      "淫蕩・硬核",
      "人妻",
      "吞精",
      "女上位",
      "拘束・拷問",
      "美人",
      "熟女",
      "淫語",
      "插入異物",
      "美腿",
      "打屁股",
      "御姐系",
      "清楚系",
      "形象俱樂部",
      "中出",
      "重口味",
      "清純",
      "調教",
      "單體作品",
      "白眼失神",
      "顏射",
      "脚控・戀足癖",
      "絕頂高潮",
      "潮吹",
      "胸控・戀乳癖",
      "性感",
      "高顏值",
      "美腳",
      "巨乳",
      "羞恥",
      "性虐癖",
      "後入",
      "唾液敷面",
      "明星臉",
      "鬼畜片",
      "口爆",
      "緊縛",
      "辣妹/GAL系",
      "舔陰",
      "女優",
      "口交",
      "野性",
      "凌辱",
      "美人妻",
      "騎乗位",
      "膚黑"
    ],
    "type": "有码",
    "company": "GLORY QUEST",
    "publish_date": "2025-06-21",
    "cover_url": "https://picture.yoshiclub.xyz/compressed/20250621/20250621065936268268_thumbnail.webp",
    "actress": [
      "三岳祐奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVG-133"
  },
  {
    "id": 225954,
    "IDcode": "MVSD-290",
    "title": "欲求不满男的寂寞巨乳人妻-水野朝陽",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "巨乳"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-5/c243bb327a1ec4e7ad98591d1a0c4021.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-290"
  },
  {
    "id": 105201,
    "IDcode": "MVSD-383",
    "title": "新婚旅行NTR的人妻凛音桃花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "NTR",
      "淫妻",
      "人妻",
      "中出",
      "白天出轨",
      "浴衣",
      "巨乳"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20240505-1/d439b5278864a34ac245fe420eda170d.jpg",
    "actress": [
      "凛音とうか",
      "前田あこ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-383"
  },
  {
    "id": 74087,
    "IDcode": "MVSD-394",
    "title": "患者の精液を飲み散らかすザーメン依存症人妻痴女医のバキュームごっくん痴療 メディカルザーメンイーター 小日向先生 小日向まい",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "吞精",
      "口交",
      "女医生",
      "荡妇"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "2019-07-19",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20250118-1/a5541bc5bc1e9287a9fd67cfee9fb6e4.jpg",
    "actress": [
      "鲛岛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-394"
  },
  {
    "id": 165132,
    "IDcode": "MVSD-401",
    "title": "神尻人妻のいる中出し専门ビキ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "中文字幕"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/2022/09/zdr14qtwz52.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-401"
  },
  {
    "id": 76048,
    "IDcode": "MVSD-408",
    "title": "人妻永井玛丽亚的催眠暗示吞精调教",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "催眠",
      "人妻",
      "吞精",
      "白天出轨",
      "巨乳"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/21/7a8ac25fc1c6bc73668afa633e6882d2.jpg",
    "actress": [
      "永井瑪麗亞"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-408"
  },
  {
    "id": 77106,
    "IDcode": "MVSD-413",
    "title": "性感姐妹人妻逆3P内射性交被痴女持续榨干精液的我",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "口交",
      "多P",
      "荡妇"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/02/2119f905/vod.jpg",
    "actress": [
      "通野未帆",
      "吉泽ひかり"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-413"
  },
  {
    "id": 85631,
    "IDcode": "MVSD-494",
    "title": "上級国民美人妻-三尾めぐ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "白天出轨",
      "凌辱",
      "多P"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2022/02/06/11e1a9dfcdb93f1b6a61c890b5e676be.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-494"
  },
  {
    "id": 81202,
    "IDcode": "MVSD-501",
    "title": "通奸的妻子-推川ゆうり 有岡みう",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "两女一男",
      "人妻",
      "中出",
      "淫乱，真实",
      "巨乳",
      "荡妇"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2022/03/26/849bc93cefa4ce60eb9ae13d394066a1.jpg",
    "actress": [
      "推川悠里",
      "椎叶みくる"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-501"
  },
  {
    "id": 225241,
    "IDcode": "MVSD-545",
    "title": "欲求不满人妻的丰满巨尻-泷结菜",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-7/483026998763d8becdadbc434640fa5d.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-545"
  },
  {
    "id": 225235,
    "IDcode": "MVSD-546",
    "title": "人妻自宅沙龙-心花友纪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-7/08546f5ff99108b17509c98a38ce9116.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-546"
  },
  {
    "id": 90731,
    "IDcode": "MVSD-551",
    "title": "人妻自宅沙龙-根尾明里",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "白天出轨",
      "按摩",
      "单体作品"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240819-2/7fcbdc5d753226361066724c93fa6259.jpg",
    "actress": [
      "根尾朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-551"
  },
  {
    "id": 90733,
    "IDcode": "MVSD-571",
    "title": "人妻自宅沙龙-佐野由真",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "白天出轨",
      "巨乳",
      "单体作品",
      "苗条"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-2/2c2cfe02419b0221bd2f22830e9b2d3c.jpg",
    "actress": [
      "佐野由真"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-571"
  },
  {
    "id": 16198,
    "IDcode": "MVSD-583",
    "title": "华丽淫荡人妻的玩弄男人游戏",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美乳",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "貴婦",
      "劇情",
      "乳交",
      "中出",
      "兩女一男",
      "多P",
      "3P・4P",
      "內衣",
      "絕頂高潮",
      "胸控・戀乳癖",
      "性感",
      "巨乳",
      "後入",
      "口交"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20240313-1/63ec58cac3b529e58b46ef4b05906f9e.jpg",
    "actress": [
      "橘瑪麗",
      "推川悠里",
      "タツ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-583"
  },
  {
    "id": 14630,
    "IDcode": "MVSD-603",
    "title": "大屁股的年轻妻子美容师月野江美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "劇情",
      "亂交 • 群P",
      "淫亂",
      "黑絲",
      "按摩女郎",
      "乳交",
      "中出",
      "苗條",
      "內衣",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "出軌",
      "胸控・戀乳癖",
      "抹油",
      "感官作品",
      "性感",
      "美腳",
      "巨乳",
      "企畫",
      "羞恥",
      "後入",
      "風俗娘",
      "口交",
      "按摩・物理治療・美容",
      "鄰居",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20240819-1/76c72d88a7c799d8ee980547bee6bc55.jpg",
    "actress": [
      "月野江翠"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-603"
  },
  {
    "id": 11320,
    "IDcode": "MVSD-621",
    "title": "淫荡抖S女上司-水澄せいら",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "飯店",
      "肉絲",
      "人妻",
      "女上位",
      "艷遇",
      "劇情",
      "美腿",
      "黑絲",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "短髮",
      "巨尻",
      "抹油",
      "女王",
      "性感",
      "美腳",
      "女上司",
      "眼鏡",
      "辦公室",
      "後入",
      "蕩婦",
      "口交",
      "臀控",
      "野性",
      "加班",
      "OL",
      "制服",
      "美人妻",
      "勾引・誘惑",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20241027-1/1c9e295c0d940b622755d8b68c22c39f.jpg",
    "actress": [
      "水澄せいら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-621"
  },
  {
    "id": 10592,
    "IDcode": "MVSD-623",
    "title": "产后敏感度暴增的早漏人母-安斉愛結",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "手指插入",
      "人妻",
      "女上位",
      "劇情",
      "按摩・美容店",
      "亂交 • 群P",
      "美腿",
      "淫亂",
      "豐滿",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "慾求不滿",
      "巨尻",
      "3P・4P",
      "家庭主妇",
      "老頭子",
      "胸控・戀乳癖",
      "抹油",
      "性感",
      "美腳",
      "巨乳",
      "兩男一女",
      "羞恥",
      "後入",
      "蕩婦",
      "舔陰",
      "口交",
      "按摩・物理治療・美容",
      "誘騙女性",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20241201-1/1e6041a28432c2d232da50ec6baf804d.jpg",
    "actress": [
      "安斉愛結"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-623"
  },
  {
    "id": 11280,
    "IDcode": "MVSD-626",
    "title": "無依無靠的我被30歲的酒鬼姐姐包養",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "人妻",
      "女上位",
      "熟女",
      "艷遇",
      "劇情",
      "酒後亂性",
      "乳交",
      "中出",
      "慾求不滿",
      "奇異的",
      "絕頂高潮",
      "女王",
      "性感",
      "眼鏡",
      "酒醉",
      "巨乳",
      "後入",
      "奇聞趣事",
      "蕩婦",
      "口交",
      "美人妻",
      "乱伦",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20241027-1/7b8987a81decad0b5c6c73beda82ece2.jpg",
    "actress": [
      "宝田萌奈美",
      "Qべぇ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-626"
  },
  {
    "id": 9012,
    "IDcode": "MVSD-630",
    "title": "对女性失去信心的我-根尾あかり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "純粹的慾望",
      "美人",
      "情趣內衣",
      "艷遇",
      "過膝襪・小腿襪",
      "劇情",
      "美腿",
      "癡女",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "苗條",
      "若妻",
      "脚控・戀足癖",
      "網襪",
      "絕頂高潮",
      "潮吹",
      "出軌",
      "美腳",
      "後入",
      "明星臉",
      "口爆",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250215-1/8036d87526d425f5b56c80aecc77f5e4.jpg",
    "actress": [
      "根尾朱里"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-630"
  },
  {
    "id": 8287,
    "IDcode": "MVSD-631",
    "title": "人妻家庭沙龙-小坂七香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "劇情",
      "按摩・美容店",
      "美腿",
      "舔腳",
      "清楚系",
      "按摩女郎",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "色白",
      "獵豔",
      "蠻橫嬌羞",
      "苗條",
      "若妻",
      "脚控・戀足癖",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "出軌",
      "抹油",
      "性感",
      "高顏值",
      "美腳",
      "羞恥",
      "後入",
      "舔陰",
      "口交",
      "按摩・物理治療・美容",
      "鄰居",
      "美人妻",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250310-1/1b6ce83bd9b4bf83525ca43265fbc1eb.jpg",
    "actress": [
      "小坂七香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-631"
  },
  {
    "id": 9031,
    "IDcode": "MVSD-633",
    "title": "禁慾一个月-水川润",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "情趣內衣",
      "約炮",
      "劇情",
      "美腿",
      "淫亂",
      "黑絲",
      "御姐系",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "色白",
      "調教",
      "巨尻",
      "苗條",
      "若妻",
      "內衣",
      "絕頂高潮",
      "家庭主妇",
      "自宅",
      "潮吹",
      "出軌",
      "胸控・戀乳癖",
      "性感",
      "美腳",
      "巨乳",
      "後入",
      "蕩婦",
      "舔陰",
      "口交",
      "美人妻",
      "勾引・誘惑",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250211-1/557fdc0e327bb6225cf5f5a00cae84ac.jpg",
    "actress": [
      "水川潤",
      "由爱可奈",
      "ダンディ",
      "アリト"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-633"
  },
  {
    "id": 8938,
    "IDcode": "MVSD-634",
    "title": "人妻自家沙龙店-逢泽美优",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "劇情",
      "按摩・美容店",
      "美腿",
      "舔腳",
      "癡女",
      "按摩女郎",
      "形象俱樂部",
      "中出",
      "清純",
      "苗條",
      "脚控・戀足癖",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "老頭子",
      "抹油",
      "高顏值",
      "美腳",
      "羞恥",
      "後入",
      "風俗娘",
      "明星臉",
      "口爆",
      "舔陰",
      "口交",
      "按摩・物理治療・美容",
      "鄰居",
      "美少女電影",
      "制服",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250211-1/ac62065e0dd79abbadcfd1634f15a01e.jpg",
    "actress": [
      "逢澤美優"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-634"
  },
  {
    "id": 8307,
    "IDcode": "MVSD-635",
    "title": "コンプレックスの爆乳を変態上司に毎日毎日、揉みしだかれ乳イキを覚えてしまった人妻地味OL 浜辺栞帆",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "手指插入",
      "人妻",
      "吞精",
      "女上位",
      "美人",
      "劇情",
      "濕身",
      "黑絲",
      "乳交",
      "形象俱樂部",
      "中出",
      "巨尻",
      "脅迫做愛",
      "顏射",
      "脚控・戀足癖",
      "絕頂高潮",
      "潮吹",
      "早漏",
      "女同事",
      "胸控・戀乳癖",
      "抹油",
      "變態",
      "性感",
      "美腳",
      "眼鏡",
      "巨乳",
      "辦公室",
      "企畫",
      "羞恥",
      "後入",
      "唾液敷面",
      "口爆",
      "口交",
      "加班",
      "OL",
      "凌辱",
      "深喉",
      "美人妻",
      "寢取",
      "制服",
      "騎乗位",
      "地味"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250806-1/7f83a3aacabf9e1a628ca71f32fd3650.jpg",
    "actress": [
      "浜辺栞帆",
      "田渊正浩"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-635"
  },
  {
    "id": 6034,
    "IDcode": "MVSD-641",
    "title": "上流社会的美丽妻子-工藤ゆり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "貴婦",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "美腿",
      "濕身",
      "淫亂",
      "舔腳",
      "御姐系",
      "欠債肉償",
      "清楚系",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "高妹",
      "色白",
      "脅迫做愛",
      "單體作品",
      "蠻橫嬌羞",
      "3P・4P",
      "絕頂高潮",
      "家庭主妇",
      "潮吹",
      "老頭子",
      "胸控・戀乳癖",
      "三十路",
      "感官作品",
      "變態",
      "性感",
      "高顏值",
      "巨乳",
      "兩男一女",
      "羞恥",
      "後入",
      "明星臉",
      "舔陰",
      "流汗",
      "口交",
      "凌辱",
      "美人妻",
      "寢取",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250615-2/9d7550147c191d8d411e27085e33aec1.jpg",
    "actress": [
      "工藤百合"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-641"
  },
  {
    "id": 6075,
    "IDcode": "MVSD-646",
    "title": "用身体报复消失的丈夫-三池小春",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "美乳",
      "手指插入",
      "淫蕩・硬核",
      "SM",
      "人妻",
      "女上位",
      "拘束・拷問",
      "美人",
      "熟女",
      "監禁",
      "亂交 • 群P",
      "劇情",
      "淫亂",
      "御姐系",
      "欠債肉償",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "色白",
      "調教",
      "多P",
      "脅迫做愛",
      "單體作品",
      "3P・4P",
      "白眼失神",
      "顏射",
      "殘忍畫面",
      "絕頂高潮",
      "猥褻穿著",
      "感官作品",
      "蒙面・面罩",
      "性感",
      "美腳",
      "兩男一女",
      "羞恥",
      "性虐癖",
      "後入",
      "口爆",
      "緊縛",
      "舔陰",
      "口交",
      "凌辱",
      "深喉",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250703-1/52c64cea42a313f02761c3327e1eae2d.jpg",
    "actress": [
      "三池小春"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-646"
  },
  {
    "id": 62942,
    "IDcode": "MVSD-649",
    "title": "喉射！口射！大量精飲！白目を剥くほど喉奥えぐる喉姦ごっくんイラマチオ 上品なマゾ美人妻の喉奥と膣奥を完膚無きまで嬲って●す串刺しハードFUCK 三池小春",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "白天出轨",
      "淫乱，真实",
      "深喉",
      "单体作品"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250624-1/5c2343e2b203093b467ebeb4041c3512.jpg",
    "actress": [
      "三池小春"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-649"
  },
  {
    "id": 3566,
    "IDcode": "MVSD-653",
    "title": "被隔壁垃圾邻居的肮脏巨根征服的年轻美容师妻子-五芭",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "大奶头",
      "NTR",
      "手指插入",
      "肉絲",
      "人妻",
      "女上位",
      "美人",
      "極品美人",
      "按摩・美容店",
      "劇情",
      "美腿",
      "黑絲",
      "猥亵",
      "清楚系",
      "按摩女郎",
      "少女",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "清純",
      "色白",
      "脅迫做愛",
      "單體作品",
      "蠻橫嬌羞",
      "美少女",
      "若妻",
      "脚控・戀足癖",
      "性騷擾",
      "自宅",
      "老頭子",
      "抹油",
      "感官作品",
      "變態",
      "高顏值",
      "美腳",
      "羞恥",
      "後入",
      "舔陰",
      "流汗",
      "臀控",
      "口交",
      "按摩・物理治療・美容",
      "鄰居",
      "美少女電影",
      "制服",
      "寢取",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/31/8408bd75/vod.jpg",
    "actress": [
      "五芭"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-653"
  },
  {
    "id": 4453,
    "IDcode": "MVSD-657",
    "title": "年轻妻子美容师爱上邻居的淫荡大屌-二羽紗愛",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "劇情",
      "按摩・美容店",
      "美腿",
      "豐滿",
      "黑絲",
      "御姐系",
      "超爆乳",
      "清楚系",
      "按摩女郎",
      "少女",
      "形象俱樂部",
      "色白",
      "巨尻",
      "脅迫做愛",
      "單體作品",
      "若妻",
      "自宅",
      "老頭子",
      "胸控・戀乳癖",
      "三十路",
      "變態",
      "性感",
      "無毛",
      "高顏值",
      "巨乳",
      "羞恥",
      "後入",
      "舔陰",
      "痴漢",
      "流汗",
      "口交",
      "按摩・物理治療・美容",
      "鄰居",
      "制服",
      "凌辱",
      "美人妻",
      "寢取",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "/upload/vod/20250801-1/a4de0cec8bc423a8892ecd1d9a742111.jpg",
    "actress": [
      "二羽紗愛"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-657"
  },
  {
    "id": 175509,
    "IDcode": "MVSD-658",
    "title": "人妻自宅サロン 底辺クズ隣人の汚らわしいデカマラに堕ちた若妻エステティシャン 黒島玲衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/10/24/541f678e/vod.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-658"
  },
  {
    "id": 2715,
    "IDcode": "MVSD-661",
    "title": "人妻在家开店被渣男邻居的肮脏巨根征服的年轻妻子美容师-竹内有纪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "正統派",
      "NTR",
      "手指插入",
      "肌肉",
      "肉絲",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "極品美人",
      "按摩・美容店",
      "劇情",
      "美腿",
      "濕身",
      "黑絲",
      "舔腳",
      "御姐系",
      "按摩女郎",
      "形象俱樂部",
      "中出",
      "高妹",
      "清純",
      "單體作品",
      "蠻橫嬌羞",
      "苗條",
      "若妻",
      "絕頂高潮",
      "脚控・戀足癖",
      "自宅",
      "潮吹",
      "老頭子",
      "三十路",
      "抹油",
      "變態",
      "性感",
      "高顏值",
      "美腳",
      "羞恥",
      "後入",
      "口爆",
      "舔陰",
      "痴漢",
      "流汗",
      "口交",
      "按摩・物理治療・美容",
      "野性",
      "制服",
      "鄰居",
      "美人妻",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MVG GROUP",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/29/37df6321/vod.jpg",
    "actress": [
      "竹内有紀"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MVSD-661"
  },
  {
    "id": 225668,
    "IDcode": "MXGS-1098",
    "title": "被来访的义兄侵犯丰满肉体的美人妻",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-6/31ff4aa7414b5b8fdc896b5e956bb3f1.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1098"
  },
  {
    "id": 13906,
    "IDcode": "MXGS-1336",
    "title": "迷戀丈夫的下屬…在家背叛NTR波多野結衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "NTR",
      "人妻",
      "女上位",
      "熟女",
      "劇情",
      "淫亂",
      "乳交",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "巨尻",
      "絕頂高潮",
      "淫妻",
      "出軌",
      "性感",
      "上司女友・妻子",
      "巨乳",
      "蕩婦",
      "口交",
      "勾引・誘惑"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "2024-06-01",
    "cover_url": "https://picture.yoshiclub.xyz/20240616/20240616040536953953.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1336"
  },
  {
    "id": 12676,
    "IDcode": "MXGS-1344",
    "title": "丈夫的下属逼迫她在家背叛NTR-森沢かな",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "人妻",
      "女上位",
      "劇情",
      "美腿",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "脚控・戀足癖",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "淫妻",
      "出軌",
      "性感",
      "高顏值",
      "美腳",
      "上司女友・妻子",
      "後入",
      "明星臉",
      "蕩婦",
      "口交",
      "美少女電影",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/28/1f1959f9f8d766f52fbc823082598661.jpg",
    "actress": [
      "森澤佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1344"
  },
  {
    "id": 10544,
    "IDcode": "MXGS-1357",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 月野かすみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "劇情",
      "乳交",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "若妻",
      "自宅",
      "潮吹",
      "淫妻",
      "胸控・戀乳癖",
      "性感",
      "美腳",
      "巨乳",
      "羞恥",
      "後入",
      "同事女友・妻子",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/25/c667f31e8476d20772f345022bb830ac.jpg",
    "actress": [
      "月野香澄"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1357"
  },
  {
    "id": 9830,
    "IDcode": "MXGS-1360",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 小春まり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "劇情",
      "美腿",
      "癡女",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "短髮",
      "苗條",
      "若妻",
      "顏射",
      "絕頂高潮",
      "脚控・戀足癖",
      "自宅",
      "家庭主妇",
      "潮吹",
      "淫妻",
      "出軌",
      "美腳",
      "上司女友・妻子",
      "羞恥",
      "後入",
      "口爆",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/05/6a25ee3b/vod.jpg",
    "actress": [
      "上戶真理"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1360"
  },
  {
    "id": 9104,
    "IDcode": "MXGS-1364",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 大槻ひびき",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "貴婦",
      "極品美人",
      "劇情",
      "美腿",
      "淫亂",
      "舔腳",
      "御姐系",
      "足交",
      "癡女",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "巨尻",
      "絕頂高潮",
      "家庭主妇",
      "脚控・戀足癖",
      "自宅",
      "潮吹",
      "淫妻",
      "出軌",
      "胸控・戀乳癖",
      "性感",
      "高顏值",
      "美腳",
      "上司女友・妻子",
      "巨乳",
      "羞恥",
      "後入",
      "明星臉",
      "口爆",
      "蕩婦",
      "舔陰",
      "流汗",
      "口交",
      "美人妻",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250816-1/f551faab4f4f9d6d8ad1779f4b181f60.jpg",
    "actress": [
      "大槻响"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1364"
  },
  {
    "id": 8234,
    "IDcode": "MXGS-1369",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 大浦真奈美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "NTR",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "貴婦",
      "劇情",
      "淫亂",
      "豐滿",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "色白",
      "巨尻",
      "性感睡衣",
      "淫妻",
      "出軌",
      "胸控・戀乳癖",
      "性感",
      "上司女友・妻子",
      "巨乳",
      "後入",
      "蕩婦",
      "口交",
      "美人妻",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250806-1/b2b523aa6aeaa558fc9be71742fc6ce7.jpg",
    "actress": [
      "大浦真奈美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1369"
  },
  {
    "id": 7475,
    "IDcode": "MXGS-1372",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 小松杏",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "大奶头",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "劇情",
      "淫亂",
      "御姐系",
      "清楚系",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "苗條",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "淫妻",
      "出軌",
      "美腳",
      "上司女友・妻子",
      "後入",
      "口爆",
      "貧乳",
      "蕩婦",
      "舔陰",
      "口交",
      "美人妻",
      "寢取",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250723-1/597809a7f76cb4f491a8c121210898ed.jpg",
    "actress": [
      "小松杏"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1372"
  },
  {
    "id": 7476,
    "IDcode": "MXGS-1373",
    "title": "ナンパした露出高めの美女が生意気すぎる絶倫痴女でエロマンガみたいに搾精されてしまった 波多野結衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美乳",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "搭訕",
      "艷遇",
      "女神",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "淫亂",
      "豐滿",
      "御姐系",
      "足交",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "巨尻",
      "獵豔",
      "3P・4P",
      "胸控・戀乳癖",
      "性感",
      "巨乳",
      "兩男一女",
      "後入",
      "明星臉",
      "口爆",
      "蕩婦",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250723-1/f97e10263d7a44de46196cfa0df88b60.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1373"
  },
  {
    "id": 7474,
    "IDcode": "MXGS-1375",
    "title": "エステ店開業を目指す友達の母に、開発された僕 橘京花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "艷遇",
      "劇情",
      "按摩・美容店",
      "豐滿",
      "御姐系",
      "按摩女郎",
      "乳交",
      "形象俱樂部",
      "中出",
      "不倫",
      "巨尻",
      "絕頂高潮",
      "抹油",
      "性感",
      "後入",
      "風俗娘",
      "口爆",
      "蕩婦",
      "口交",
      "按摩・物理治療・美容",
      "朋友母親",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250723-1/f4fb2ef262a5019e6fa6af1451b23acb.jpg",
    "actress": [
      "橘京花"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1375"
  },
  {
    "id": 6827,
    "IDcode": "MXGS-1379",
    "title": "エステ店開業を目指す友達の母に、開発された僕 波多野結衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "母親",
      "艷遇",
      "女神",
      "儿子的朋友",
      "極品美人",
      "按摩・美容店",
      "劇情",
      "豐滿",
      "芸能人",
      "御姐系",
      "按摩女郎",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "色白",
      "巨尻",
      "絕頂高潮",
      "性感睡衣",
      "胸控・戀乳癖",
      "抹油",
      "性感",
      "巨乳",
      "後入",
      "風俗娘",
      "明星臉",
      "口爆",
      "蕩婦",
      "口交",
      "按摩・物理治療・美容",
      "朋友母親",
      "美人妻",
      "勾引・誘惑",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250710-3/3cb3fcba7b13cfc4a6aab491cda83cc1.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1379"
  },
  {
    "id": 5274,
    "IDcode": "MXGS-1386",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 工藤ゆり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "劇情",
      "美腿",
      "淫亂",
      "御姐系",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "色白",
      "巨尻",
      "單體作品",
      "絕頂高潮",
      "家庭主妇",
      "自宅",
      "性感睡衣",
      "淫妻",
      "三十路",
      "性感",
      "無毛",
      "上司女友・妻子",
      "高顏值",
      "巨乳",
      "羞恥",
      "後入",
      "蕩婦",
      "舔陰",
      "口交",
      "臀控",
      "美人妻",
      "寢取",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250624-1/cf43a860cc70ca0c6cb1edb5cff981c8.jpg",
    "actress": [
      "工藤百合"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1386"
  },
  {
    "id": 5270,
    "IDcode": "MXGS-1387",
    "title": "ナンパした清楚系美人女子大生が生意気すぎる絶倫痴女でエロマンガみたいに搾精されてしまった 吉澤友貴",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "手指插入",
      "肌肉",
      "人妻",
      "女上位",
      "美人",
      "搭訕",
      "艷遇",
      "劇情",
      "亂交 • 群P",
      "美腿",
      "淫亂",
      "御姐系",
      "癡女",
      "乳交",
      "形象俱樂部",
      "混血",
      "中出",
      "慾求不滿",
      "單體作品",
      "獵豔",
      "蠻橫嬌羞",
      "3P・4P",
      "絕頂高潮",
      "寫真女郎",
      "潮吹",
      "三十路",
      "性感",
      "無毛",
      "兩男一女",
      "後入",
      "辣妹/GAL系",
      "舔陰",
      "口交",
      "野性",
      "寫真偶像",
      "美人妻",
      "騎乗位",
      "女學生"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250624-1/0a2632560b012b0b9b2ae01c010a7727.jpg",
    "actress": [
      "吉泽友贵"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1387"
  },
  {
    "id": 4369,
    "IDcode": "MXGS-1388",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 宮城りえ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "大奶头",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "極品美人",
      "劇情",
      "美腿",
      "淫亂",
      "癡女",
      "形象俱樂部",
      "中出",
      "清純",
      "不倫",
      "色白",
      "阪道系",
      "小隻馬",
      "巨尻",
      "單體作品",
      "苗條",
      "若妻",
      "脚控・戀足癖",
      "自宅",
      "潮吹",
      "淫妻",
      "出軌",
      "性感",
      "高顏值",
      "美腳",
      "上司女友・妻子",
      "巨乳",
      "羞恥",
      "後入",
      "明星臉",
      "口爆",
      "舔陰",
      "口交",
      "美少女電影",
      "美人妻",
      "騎乗位",
      "偷竊"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250723-1/2398b47b51ae0ebed8f0352ddd5d98d3.jpg",
    "actress": [
      "宮城理惠"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1388"
  },
  {
    "id": 4370,
    "IDcode": "MXGS-1390",
    "title": "被讨厌的同事抓住把柄为所欲为后堕落的美人OL-吉澤友貴",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "美腿",
      "淫亂",
      "御姐系",
      "風俗夜場",
      "按摩女郎",
      "癡女",
      "拜金女",
      "乳交",
      "形象俱樂部",
      "混血",
      "中出",
      "不倫",
      "調教",
      "脅迫做愛",
      "單體作品",
      "蠻橫嬌羞",
      "3P・4P",
      "顏射",
      "脚控・戀足癖",
      "寫真女郎",
      "女同事",
      "性感",
      "高顏值",
      "美腳",
      "辦公室",
      "職場",
      "兩男一女",
      "羞恥",
      "後入",
      "綠茶婊",
      "風俗娘",
      "口爆",
      "緊縛",
      "舔陰",
      "口交",
      "加班",
      "OL",
      "凌辱",
      "制服",
      "寫真偶像",
      "寢取",
      "美人妻",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/28/882c17782fd39673ea9890a47e28d517.jpg",
    "actress": [
      "吉泽友贵"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1390"
  },
  {
    "id": 3486,
    "IDcode": "MXGS-1392",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 沙月ふみの",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "大奶头",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "極品美人",
      "劇情",
      "美腿",
      "淫亂",
      "御姐系",
      "清楚系",
      "乳交",
      "形象俱樂部",
      "中出",
      "清純",
      "不倫",
      "色白",
      "阪道系",
      "巨尻",
      "單體作品",
      "蠻橫嬌羞",
      "若妻",
      "絕頂高潮",
      "家庭主妇",
      "脚控・戀足癖",
      "自宅",
      "淫妻",
      "出軌",
      "三十路",
      "高顏值",
      "美腳",
      "上司女友・妻子",
      "巨乳",
      "後入",
      "口爆",
      "蕩婦",
      "舔陰",
      "口交",
      "臀控",
      "鬃毛",
      "美人妻",
      "騎乗位",
      "偷竊"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/08/21/a675833f4fcbf03323d7d45f5945a94a.jpg",
    "actress": [
      "沙月文乃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1392"
  },
  {
    "id": 3485,
    "IDcode": "MXGS-1393",
    "title": "クズな彼氏と私の言いなりNTR記録 柏木こなつ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "M男・M女",
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "淫蕩・硬核",
      "人妻",
      "SM",
      "女上位",
      "拘束・拷問",
      "美人",
      "接吻",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "美腿",
      "淫亂",
      "清楚系",
      "少女",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "清純",
      "色白",
      "調教",
      "小隻馬",
      "單體作品",
      "蠻橫嬌羞",
      "苗條",
      "美少女",
      "蘿莉",
      "3P・4P",
      "絕頂高潮",
      "潮吹",
      "早漏",
      "淫妻",
      "猥褻穿著",
      "女友・妻子",
      "高顏值",
      "美腳",
      "巨乳",
      "兩男一女",
      "羞恥",
      "後入",
      "鬼畜片",
      "口爆",
      "奇聞趣事",
      "舔陰",
      "口交",
      "美少女電影",
      "凌辱",
      "美人妻",
      "蘿莉控",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/21/1195c9b7/vod.jpg",
    "actress": [
      "柏木小夏"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1393"
  },
  {
    "id": 3488,
    "IDcode": "MXGS-1395",
    "title": "ナンパした色白で巨乳なお姉さんが生意気すぎる絶倫痴女でエロマンガみたいに搾精されてしまった 有村のぞみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "純粹的慾望",
      "艷遇",
      "約炮",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "美腿",
      "淫亂",
      "豐滿",
      "癡女",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "色白",
      "小隻馬",
      "大姐姐",
      "巨尻",
      "單體作品",
      "短髮",
      "蠻橫嬌羞",
      "3P・4P",
      "金髮",
      "絕頂高潮",
      "家庭主妇",
      "潮吹",
      "出軌",
      "胸控・戀乳癖",
      "猥褻穿著",
      "性感",
      "無毛",
      "美腳",
      "高顏值",
      "巨乳",
      "兩男一女",
      "後入",
      "綠茶婊",
      "口爆",
      "辣妹/GAL系",
      "舔陰",
      "口交",
      "臀控",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/21/9ad6b974/vod.jpg",
    "actress": [
      "有村希"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1395"
  },
  {
    "id": 2686,
    "IDcode": "MXGS-1396",
    "title": "絶対痴女 色気ムンムン豊満お姉さんの誘惑SEX 波多野結衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "情趣內衣",
      "艷遇",
      "女神",
      "極品美人",
      "亂交 • 群P",
      "劇情",
      "美腿",
      "淫亂",
      "豐滿",
      "黑絲",
      "御姐系",
      "癡女",
      "乳交",
      "按摩棒",
      "形象俱樂部",
      "中出",
      "高妹",
      "慾求不滿",
      "色白",
      "大姐姐",
      "巨尻",
      "單體作品",
      "3P・4P",
      "絕頂高潮",
      "網襪",
      "家庭主妇",
      "自宅",
      "潮吹",
      "故事集",
      "胸控・戀乳癖",
      "猥褻穿著",
      "三十路",
      "性感",
      "無毛",
      "高顏值",
      "巨乳",
      "辦公室",
      "職場",
      "兩男一女",
      "後入",
      "明星臉",
      "口爆",
      "蕩婦",
      "舔陰",
      "口交",
      "臀控",
      "OL",
      "制服",
      "美人妻",
      "勾引・誘惑",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/22/a791623103038dc7f578700cd03e8a3c.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1396"
  },
  {
    "id": 2683,
    "IDcode": "MXGS-1399",
    "title": "夫の部下に言い寄られ…自宅で裏切りのNTR 友田彩也香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "美人",
      "極品美人",
      "劇情",
      "美腿",
      "豐滿",
      "御姐系",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "單體作品",
      "蠻橫嬌羞",
      "內衣",
      "絕頂高潮",
      "家庭主妇",
      "自宅",
      "性感睡衣",
      "潮吹",
      "淫妻",
      "出軌",
      "性感",
      "高顏值",
      "美腳",
      "上司女友・妻子",
      "巨乳",
      "羞恥",
      "後入",
      "口爆",
      "舔陰",
      "口交",
      "臀控",
      "美人妻",
      "寢取",
      "騎乗位",
      "偷竊"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/09/22/894b0d3ebad4c3a1a619d99c2e1ec5ca.jpg",
    "actress": [
      "友田彩也香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-1399"
  },
  {
    "id": 104729,
    "IDcode": "MXGS-845",
    "title": "人妻吉泽明步感冒了需要用同事们的肉棒打针治疗",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "美少女",
      "OL"
    ],
    "type": "有码",
    "company": "MAXING",
    "publish_date": "",
    "cover_url": "/upload/vod/20240624-1/49dcf304abd3b0242a3f75c2c4f3a6ae.jpg",
    "actress": [
      "吉沢明歩",
      "森林原人"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS-845"
  },
  {
    "id": 170119,
    "IDcode": "MXGS1111",
    "title": "美人妻的猥褻情事 鄉下工廠可憐太太被巨根搞成瘋狂女人 瀨戶菫",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/20250118-1/5614567046e6de2e1a9a444bb6ba503a.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MXGS1111"
  },
  {
    "id": 213740,
    "IDcode": "MY-465",
    "title": "巨乳人妻-金子仁菜",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "巨乳"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2021/10/05/f6c787b53eec94ba038c78ece984ea32.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MY-465"
  },
  {
    "id": 213820,
    "IDcode": "MY-495",
    "title": "通奸的欲望",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2021/10/10/47af83e8b2450f113e957778cb49db01.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MY-495"
  },
  {
    "id": 88507,
    "IDcode": "MYBA-032",
    "title": "人妻の花びらめくり 黒木美沙",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "巨乳"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2021-03-19",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20231011-1/986577f9d7f7baffae21d05b48d0b401.jpg",
    "actress": [
      "市川润",
      "黒木美沙"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-032"
  },
  {
    "id": 90737,
    "IDcode": "MYBA-061",
    "title": "人妻の花びらめくり 若宮穂乃",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2023-08-15",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20240205-1/998803dfcb8bc637aa2657cc140103f8.jpg",
    "actress": [
      "若宫穂乃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-061"
  },
  {
    "id": 17721,
    "IDcode": "MYBA-064",
    "title": "妻子翻瓣 藤木佐惠",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "出軌",
      "人妻",
      "熟女",
      "中出",
      "巨乳"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2023-11-21",
    "cover_url": "https://picture.yoshiclub.xyz/20231120/20231120003715365365.jpg",
    "actress": [
      "藤木紗英",
      "莲美柚香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-064"
  },
  {
    "id": 14604,
    "IDcode": "MYBA-070",
    "title": "人妻之花 ~ 紺野光",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美乳",
      "NTR",
      "人妻",
      "女上位",
      "熟女",
      "艷遇",
      "約炮",
      "劇情",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "絕頂高潮",
      "出軌",
      "性感",
      "蕩婦",
      "口交",
      "美少女電影"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2024-05-21",
    "cover_url": "https://picture.yoshiclub.xyz/20240519/20240519041152121121.jpg",
    "actress": [
      "绀野光"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-070"
  },
  {
    "id": 13292,
    "IDcode": "MYBA-072",
    "title": "人妻之花 ~ 黑木奈美",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美乳",
      "人妻",
      "熟女",
      "感官作品",
      "形象俱樂部",
      "女優",
      "中出",
      "色白",
      "性感",
      "女上位",
      "口交",
      "企畫",
      "巨乳",
      "美腿",
      "內衣"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2024-07-16",
    "cover_url": "https://picture.yoshiclub.xyz/20240714/20240714024327396396.jpg",
    "actress": [
      "黒木奈美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-072"
  },
  {
    "id": 93330,
    "IDcode": "MYBA-073",
    "title": "人妻の花びらめくり 藤咲紫",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "中出",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "2024-08-20",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20241011-1/4bbe694ff8c7a16a00e3b6162c8183f3.jpg",
    "actress": [
      "藤咲紫"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-073"
  },
  {
    "id": 11254,
    "IDcode": "MYBA-075",
    "title": "人妻の花びらめくり 友田彩也香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美乳",
      "人妻",
      "女上位",
      "熟女",
      "美腿",
      "乳交",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "短髮",
      "美腳",
      "企畫",
      "後入",
      "女優",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/10/21/3930d219/vod.jpg",
    "actress": [
      "友田彩也香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-075"
  },
  {
    "id": 95193,
    "IDcode": "MYBA-076",
    "title": "人妻の花びらめくり 春原未来",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/25/1cb3bc9c/vod.jpg",
    "actress": [
      "春原未来"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-076"
  },
  {
    "id": 8948,
    "IDcode": "MYBA-078",
    "title": "人妻の花びらめくり 葵百合香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "真實拍攝",
      "肉絲",
      "人妻",
      "女上位",
      "熟女",
      "大乳暈",
      "美腿",
      "形象俱樂部",
      "中出",
      "不倫",
      "女優訪談",
      "內衣",
      "性感",
      "美腳",
      "巨乳",
      "企畫",
      "後入",
      "蕩婦",
      "女優",
      "口交",
      "真人秀",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250816-1/4faea9e411e00b174e66e96dd849fa27.jpg",
    "actress": [
      "葵百合香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-078"
  },
  {
    "id": 72503,
    "IDcode": "MYBA-079",
    "title": "人妻の花びらめくり 天宮かすみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250806-1/5c03d3276ba52abaeb9b16a18d7c0ebd.jpg",
    "actress": [
      "天宮かすみ"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-079"
  },
  {
    "id": 7480,
    "IDcode": "MYBA-080",
    "title": "人妻の花びらめくり 多田有花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "真實拍攝",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "巨尻",
      "女優訪談",
      "家庭主妇",
      "內衣",
      "性感",
      "美腳",
      "巨乳",
      "企畫",
      "後入",
      "女優",
      "口交",
      "真人秀",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250806-2/9ab3bb57bcdf902ded3a38c6141d2b82.jpg",
    "actress": [
      "多田有花"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-080"
  },
  {
    "id": 68785,
    "IDcode": "MYBA-081",
    "title": "人妻の花びらめくり 雪代一鳳",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250710-2/96d5a773d33fa49986035b5e7b55fc29.jpg",
    "actress": [
      "雪代一鳳"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-081"
  },
  {
    "id": 5963,
    "IDcode": "MYBA-082",
    "title": "人妻の花びらめくり 藤原真帆",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美臀",
      "大奶头",
      "美乳",
      "手指插入",
      "真實拍攝",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "熟女",
      "大乳暈",
      "美腿",
      "御姐系",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "不倫",
      "巨尻",
      "單體作品",
      "苗條",
      "家庭主妇",
      "胸控・戀乳癖",
      "三十路",
      "性感",
      "高顏值",
      "美腳",
      "巨乳",
      "企畫",
      "後入",
      "口爆",
      "蕩婦",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250615-2/98f830eff4346abe48e66f14117d67c6.jpg",
    "actress": [
      "藤原真帆"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-082"
  },
  {
    "id": 63025,
    "IDcode": "MYBA-083",
    "title": "人妻の花びらめくり 芦名ほのか",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "成熟的女人",
      "人妻",
      "中出",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250624-1/e2b0a91c9e127bb6c43a1d82957722ca.jpg",
    "actress": [
      "蘆名穗花",
      "真琴"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-083"
  },
  {
    "id": 4435,
    "IDcode": "MYBA-084",
    "title": "人妻の花びらめくり 三池小春",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "美人",
      "貴婦",
      "純粹的慾望",
      "劇情",
      "美腿",
      "素人",
      "淫亂",
      "御姐系",
      "清楚系",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "清純",
      "不倫",
      "巨尻",
      "單體作品",
      "家庭主妇",
      "出軌",
      "三十路",
      "後入",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20250723-1/eb3c5b7137f61c0b98c95484880a75c9.jpg",
    "actress": [
      "三池小春"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-084"
  },
  {
    "id": 3500,
    "IDcode": "MYBA-085",
    "title": "人妻の花びらめくり 沙月ふみの",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "正統派",
      "大奶头",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "貴婦",
      "熟女",
      "極品美人",
      "美腿",
      "豐滿",
      "御姐系",
      "清楚系",
      "癡女",
      "乳交",
      "形象俱樂部",
      "中出",
      "慾求不滿",
      "清純",
      "色白",
      "不倫",
      "巨尻",
      "單體作品",
      "絕頂高潮",
      "家庭主妇",
      "潮吹",
      "出軌",
      "三十路",
      "高顏值",
      "美腳",
      "巨乳",
      "企畫",
      "後入",
      "舔陰",
      "口交",
      "美人妻",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/08/21/b2b0d92b/vod.jpg",
    "actress": [
      "沙月文乃"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-085"
  },
  {
    "id": 2672,
    "IDcode": "MYBA-086",
    "title": "人妻の花びらめくり 吉澤友貴",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "飯店",
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "接吻",
      "美人",
      "熟女",
      "純粹的慾望",
      "極品美人",
      "美腿",
      "豐滿",
      "御姐系",
      "乳交",
      "形象俱樂部",
      "中出",
      "不倫",
      "色白",
      "單體作品",
      "苗條",
      "顏射",
      "脚控・戀足癖",
      "寫真女郎",
      "絕頂高潮",
      "潮吹",
      "三十路",
      "性感",
      "御姐控",
      "美腳",
      "高顏值",
      "企畫",
      "後入",
      "口爆",
      "舔陰",
      "口交",
      "臀控",
      "寫真偶像",
      "美人妻",
      "騎乗位",
      "阪道系"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/video/m3u8/2025/09/17/f503f1e2/vod.jpg",
    "actress": [
      "吉泽友贵"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-086"
  },
  {
    "id": 175165,
    "IDcode": "MYBA-087",
    "title": "人妻の花びらめくり 工藤ゆり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2025/10/29/55f2ea3170c8ee4b136320749f6319b3.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=MYBA-087"
  },
  {
    "id": 73431,
    "IDcode": "NACR-247",
    "title": "隔壁的美丽人妻 喝醉弄错房间「我回来啦～！」 南真由",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "口交",
      "烂醉如泥的"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/20241005-1/e60dc2c203bb1308b585926a3db9ca10.jpg",
    "actress": [
      "南真悠"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-247"
  },
  {
    "id": 165328,
    "IDcode": "NACR-269",
    "title": "隣人に私生活を覗かれ、そして犯された美人妻 中村知恵",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "中文字幕"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "http://p.155250718p.com/upload/vod/2022/09/mj5bli4uzjh.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-269"
  },
  {
    "id": 76988,
    "IDcode": "NACR-286",
    "title": "夫とマッサージ師が企てた罠 美人妻NTR計画 白咲花",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕",
      "已婚妇女",
      "NTR",
      "淫妻",
      "素人作品",
      "人妻",
      "中出",
      "白天出轨",
      "按摩",
      "苗条"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/2022/09/23dvz0z3teu.jpg",
    "actress": [
      "白咲花"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-286"
  },
  {
    "id": 83765,
    "IDcode": "NACR-306",
    "title": "隣の美人妻泥●し部屋を間違え「ただいま～！」紗々原ゆり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "中文字幕",
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "乳房"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://1.15250719pic.com/upload/vod/2022/09/qpwcnzuflf1.jpg",
    "actress": [
      "纱々原ゆり"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-306"
  },
  {
    "id": 221861,
    "IDcode": "NACR-314",
    "title": "一喝醉酒的邻居人妻-永井マリア",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-11/b2ea324fe003b3e9da64a2551d0b57e6.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-314"
  },
  {
    "id": 210432,
    "IDcode": "NACR-329",
    "title": "母乳人妻 羽田希",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2020/10/01/efd248e06962973b23f442d7ff23a19a.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-329"
  },
  {
    "id": 78623,
    "IDcode": "NACR-421",
    "title": "隣の美人妻 泥●し部屋を間違え「ただいま～！」 新村あかり",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "潮吹",
      "已婚妇女",
      "无毛",
      "人妻",
      "中出",
      "口交",
      "巨乳",
      "自慰",
      "荡妇"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "2021-05-01",
    "cover_url": "https://fmtu.sl2025p.com/upload/vod/20220903-1/9090ab8deca9fc244fd73e24a3178323.jpg",
    "actress": [
      "新村晶"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-421"
  },
  {
    "id": 79808,
    "IDcode": "NACR-465",
    "title": "隣の美人妻-舞原聖",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "荡妇",
      "乳房"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2021/12/05/73f83cd6d8f97ba2b292f28addc0650f.jpg",
    "actress": [
      "舞原圣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-465"
  },
  {
    "id": 85712,
    "IDcode": "NACR-511",
    "title": "美人妻-佐伯由美香",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "放尿",
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "单体作品"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2022/04/03/fa63aed76aa4b4254a0a3f68b59eb707.jpg",
    "actress": [
      "佐伯由美香"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-511"
  },
  {
    "id": 218137,
    "IDcode": "NACR-541",
    "title": "美人妻-市川愛茉",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2022/06/05/f8bf79230d3901979b6f4b1a6d13d610.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-541"
  },
  {
    "id": 67989,
    "IDcode": "NACR-616",
    "title": "享受通奸的快感-乃水音",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "出轨",
      "人妻",
      "中出",
      "口交",
      "自慰",
      "单体作品"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://tutu1.space/images/2023/01/07/9511f417bfd483a27fadd68a34e91e68.jpg",
    "actress": [
      "ニック",
      "星乃水音"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-616"
  },
  {
    "id": 69128,
    "IDcode": "NACR-630",
    "title": "美人妻的過錯 小野寺真優",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "单体作品",
      "苗条"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20250715-3/1e1e9851e62bea771be2f02d2514f188.webp",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-630"
  },
  {
    "id": 92977,
    "IDcode": "NACR-659",
    "title": "被50岁小说家圈养的人妻编辑",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "单体作品",
      "乳房",
      "苗条"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-8/3a4e2f3dedf6669b79d02eb0406168a7.jpg",
    "actress": [
      "美咲佳奈"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-659"
  },
  {
    "id": 92978,
    "IDcode": "NACR-661",
    "title": "隔壁的美人妻错进到我家-月岛樱",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "巨乳",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-7/90d769af72c9f84d3249ebcf4f46835b.jpg",
    "actress": [
      "月岛さくら"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-661"
  },
  {
    "id": 225391,
    "IDcode": "NACR-666",
    "title": "把我玩弄于鼓掌的嫂子-北川美久",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-6/574f83778761aa38f46377191309d52e.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-666"
  },
  {
    "id": 168469,
    "IDcode": "NACR-669",
    "title": "温柔美人妻-一条美绪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240819-2/cfc0a8262b65c5d319e45f4c4274b28b.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-669"
  },
  {
    "id": 168352,
    "IDcode": "NACR-671",
    "title": "诱惑隔壁大学生的美人妻-水川枫",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240819-2/52d97668a2e3c77f50e475cbea179a3c.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-671"
  },
  {
    "id": 226054,
    "IDcode": "NACR-683",
    "title": "淫乱人妻-南条宫子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-5/a810d5e9fcd4b5a9bafa95063d3c31ef.jpg",
    "actress": [],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-683"
  },
  {
    "id": 107025,
    "IDcode": "NACR-702",
    "title": "傳聞住在附近的美人妻 是個貪食肉棒的淫亂妻子... 澤乃香菜",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "中出",
      "自慰",
      "单体作品",
      "荡妇"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20250715-2/5995c078e0f873799fab9ad54cef7fed.webp",
    "actress": [
      "澤乃明日香",
      "岩下たろう"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-702"
  },
  {
    "id": 106830,
    "IDcode": "NACR-706",
    "title": "久违的高人气人妻-纱纱原百合",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "乳液",
      "已婚妇女",
      "人妻",
      "中出",
      "口交",
      "巨乳",
      "单体作品"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-3/2fd1870e9c2be6ef61fa579bb7c2f9d9.jpg",
    "actress": [
      "纱々原ゆり"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-706"
  },
  {
    "id": 18628,
    "IDcode": "NACR-709",
    "title": "性欲绝伦主妇-波多野结衣",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "人妻",
      "蕩婦",
      "猥褻穿著",
      "吞精",
      "中出",
      "無毛",
      "巨乳"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "https://avtdc107.cc/upload/vod/20240118-3/25da60151c3730cd3432b47d2110d8eb.jpg",
    "actress": [
      "波多野结衣"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-709"
  },
  {
    "id": 106320,
    "IDcode": "NACR-734",
    "title": "變態巨乳人妻-織田真子",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "成熟的女人",
      "人妻",
      "戏剧",
      "巨乳",
      "自慰",
      "单体作品"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240109-1/d7667e02b3e0a7997f6b23a6e534d082.jpg",
    "actress": [
      "織田真子"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-734"
  },
  {
    "id": 16174,
    "IDcode": "NACR-767",
    "title": "媚药加倍黑发美女孕育强暴-鈴木さとみ",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美乳",
      "手指插入",
      "人妻",
      "女上位",
      "拘束・拷問",
      "熟女",
      "乳交",
      "中出",
      "巨尻",
      "苗條",
      "潮吹",
      "女同事",
      "性感",
      "巨乳",
      "後入",
      "口交",
      "OL",
      "制服",
      "騎乗位"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240327-1/2082a585dcf1d377f25c69faed4573a8.jpg",
    "actress": [
      "铃木里美"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-767"
  },
  {
    "id": 15635,
    "IDcode": "NACR-790",
    "title": "被绝伦公公侵犯-天马圭",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "美臀",
      "美乳",
      "NTR",
      "手指插入",
      "人妻",
      "女上位",
      "熟女",
      "劇情",
      "亂交 • 群P",
      "淫亂",
      "中出",
      "調教",
      "兒媳",
      "苗條",
      "顏射",
      "內衣",
      "脚控・戀足癖",
      "絕頂高潮",
      "自宅",
      "潮吹",
      "出軌",
      "胸控・戀乳癖",
      "性感",
      "無毛",
      "美腳",
      "羞恥",
      "後入",
      "亂倫",
      "蕩婦",
      "舔陰",
      "口交",
      "凌辱",
      "深喉",
      "公公",
      "騎乗位",
      "強姦"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240502-1/d49ca1f855b30d402780085a4891c34f.jpg",
    "actress": [
      "天馬唯"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-790"
  },
  {
    "id": 15210,
    "IDcode": "NACR-794",
    "title": "为了深爱的丈夫-五日市芽依",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "身體換業務",
      "美乳",
      "人妻",
      "蕩婦",
      "下屬女友・妻子",
      "中出",
      "口交",
      "色白",
      "無毛",
      "心機婊",
      "美少女電影",
      "勾引・誘惑",
      "劇情",
      "絕頂高潮"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240521-1/d353ff02e90d2cdc693f0ccd3ab5bf8b.jpg",
    "actress": [
      "五日市芽依"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-794"
  },
  {
    "id": 104290,
    "IDcode": "NACR-795",
    "title": "不被满足的人妻沉溺于和义父的中出SEX",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "已婚妇女",
      "人妻",
      "中出",
      "自慰",
      "单体作品",
      "乳房",
      "苗条"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240521-1/038a56e26d0ab24f0439089e4ccbc1c6.jpg",
    "actress": [
      "黒木逢夢"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-795"
  },
  {
    "id": 15209,
    "IDcode": "NACR-797",
    "title": "邻居的美人妻-藤子美绪",
    "year": "",
    "country": "",
    "genre": "",
    "genres": [
      "NTR",
      "美乳",
      "出軌",
      "人妻",
      "胸控・戀乳癖",
      "蕩婦",
      "女上位",
      "形象俱樂部",
      "中出",
      "口交",
      "鄰居",
      "艷遇",
      "短髮",
      "巨乳",
      "自慰",
      "劇情",
      "騎乗位",
      "絕頂高潮"
    ],
    "type": "有码",
    "company": "PLANETPLUS",
    "publish_date": "",
    "cover_url": "/upload/vod/20240609-1/3750aaa505df401dd04107e1c1cd1584.jpg",
    "actress": [
      "藤子未央"
    ],
    "title_play_url": "https://yunvgong.com/JAV/player_template.html?series=NACR-797"
  }
];